### ISSUE TITLE
Custom row style  based on data 

### ISSUE THREAD

**Issue by aatia-commits** [TanStack/table#1216]
is there is a way to add css style / classes to table rows  based on the input row data

**Comment by HardcoreParkore** [comment]
Yes. Check out [this example](https://react-table.js.org/#/story/cell-renderers-custom-components)

**Comment by thedustyrover** [comment]
I couldn't find anything in that example that render a custom css style/class on the row specifically. The cell renderers seem to apply to columns only

**Comment by GuySerfaty** [comment]
@thedustyrover I belive the link from 2018 talk about [version 6](https://github.com/tannerlinsley/react-table/tree/v6)
these days you should use [this](https://github.com/tannerlinsley/react-table/tree/master/examples/data-driven-classes-and-styles)

`<tr {...row.getRowProps(getRowProps(row))}>`
