### ISSUE TITLE
[svelte-table] Table component errors on render in sveltekit's ssr

### ISSUE THREAD

**Issue by AdaptingAFM** [TanStack/table#3949]
### Describe the bug

svelte-kit, most popular framework to work with svelte, fails to server-side render the components of svelte-table.

### Your minimal, reproducible example

https://github.com/AdaptingAFM/svelte-table-on-sveltekit

### Steps to reproduce

1. Clone the repo
2. Init the project with your package manager
3. Start the server with the `dev` command
4. Load the index page, which should be located at localhost:3000

### Expected behavior

Out-of-the-box compatibility with svelte-kit, if not possible, consider adding a script to https://github.com/svelte-add/svelte-add

### How often does this bug happen?

Every time

### Platform

Arch Linux

### react-table version

8.0.0-alpha.87

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
@Mokshit06 any ideas here?

**Comment by Mokshit06** [comment]
@tannerlinsley  This error is due to our current build script compiling the `<Placeholder />` component in svelte-table as a client component, but svelte expecting different interface for server. I'll either update the build script to compile it for server as well, or just add the precompiled file to source.

**Comment by KevinVandy** [comment]
Has this been solved in the new beta?

**Comment by Mokshit06** [comment]
yep this has been solved in #3980
