### ISSUE TITLE
expanding example not working and getSubRows break pagination

### ISSUE THREAD

**Issue by brunoti** [TanStack/table#3960]
### Describe the bug

The behavior of the expansion example is breaking. It only renders three rows and I can't paginate. 

On my local, I managed to render all the rows (i guess) but canGoNext and canGoPrevious break. It goes back to normal as soon as I remove the getSubRows. 

### Your minimal, reproducible example

https://codesandbox.io/s/github/TanStack/react-table/tree/alpha/examples/react/expanding?file=/src/main.tsx

### Steps to reproduce

1. clone the repo
2. follow instructions to run the expansion example
3. access the link generated by vite

### Expected behavior

It should be able to paginate and the example should not be broken, rendering only 3 rows.

### How often does this bug happen?

Every time

### Screenshots or Videos

![Uploading Screen Shot 2022-05-24 at 15.16.16.png…]()

### Platform

- macOS

### react-table version

alpha-87

### TypeScript version

latest

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by gguiceuna** [comment]
I upgraded from alpha.72 to alpha.87 and noticed this as well in my own project. As a work around I provided the getCoreRowModel option the old getCoreRowModel function from alpha.72 and it started working again (I'm not sure what side effects this has though).

**Comment by KevinVandy** [comment]
fixed as of alpha 88
