### ISSUE TITLE
Subrow unselect doesn't affect parent checkbox

### ISSUE THREAD

**Issue by Jonyberry** [TanStack/table#3965]
### Describe the bug

If you unselect child row and you already has selected its parent row, parent row stay selected, but it should go to indeterminate state.

### Your minimal, reproducible example

https://codesandbox.io/s/summer-lake-2qklsp?file=/src/App.js

### Steps to reproduce

1. Expand row
2. Select parent row
3. Unselect child row -> parent row stay selected 

### Expected behavior

1. Expand row
2. Select parent row
3. Unselect child row -> parent row go to indeterminate state

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="400" alt="Snímek obrazovky 2022-05-25 v 13 41 35" src="https://user-images.githubusercontent.com/17932351/170254019-0ece2283-d932-42fe-8bc5-760878676682.png">

### Platform

I tried it on

- OS: macOS
- browser: Chrome

But I don't think it is browser issue.

### react-table version

7.7.12

### TypeScript version

4.5.5

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Jonyberry** [comment]
Hi Nelson,

thanks for quick answer!

I updated my sandbox and also I added one more row. When I tried your fix my parent checkbox now selects all rows but it should select only subrows. 

Have you got any other idea how to fix it?

**Comment by nelsonrds** [comment]
Hello Jony,
To be honest, I think that there is something missing on the **row** property, something like this: 

![image](https://user-images.githubusercontent.com/17497085/170469802-a9d3e907-ac97-4e1d-b6f1-f638b1c8bc43.png)

Also, expanding + row selection is not properly connected and you cannot do what you are trying to do, maybe Tan can help us out here.

Good luck Jony!

**Comment by tannerlinsley** [comment]
Feel free to open a discussion or use the Discord for more help!

**Comment by Jonyberry** [comment]
Alright, I create discussion [here](https://github.com/TanStack/table/discussions/3975)

**Comment by itsmejoeeey** [comment]
When following the reproduction steps, this same issue is visible in [the "Expanding" CodeSandbox example from the guide.](https://tanstack.com/table/v8/docs/examples/react/expanding)

This issue seems to have the same/similar symptoms to these other issues: #4720 #4878 #4879 

> This naive UI example here (cascade checking) has the behavior we are expecting:
> https://www.naiveui.com/en-US/os-theme/components/tree#cascade.vue

Could you please advise if we are missing something @tannerlinsley?

**Comment by itsmejoeeey** [comment]
[See my comment on the above linked discussion](https://github.com/TanStack/table/discussions/3975#discussioncomment-7009403) that outlines a way I managed to implement this sort of "cascading" behaviour.

**Comment by VincEnterprise** [comment]
bump

**Comment by R-Bower** [comment]
I've fixed this in a local fork.  The issue stems from a row's selection not propagating to parent rows.

```typescript
/**
 * When child rows are updated, the parent state is not properly synced.
 * Assumptions:
 * When all children are selected, the parent should be selected.
 * When only some children are selected, the parent should be indeterminate.
 * When no children are selected, the parent should not be selected.
 */
function syncParentRowSelection<TData extends RowData>(
  row: Row<TData>,
  selection: RowSelectionState,
  table: Table<TData>,
): RowSelectionState {
  const parentRow = row.getParentRow()
  if (!parentRow) {
    return selection
  }

  const selected = isRowSelected(parentRow, selection)
  const isAllSubRowsSelected =
    isSubRowSelected(parentRow, selection, table) === "all"

  if (isAllSubRowsSelected && !selected) {
    mutateRowIsSelected(selection, parentRow.id, true, false, table)
  } else if (!isAllSubRowsSelected && selected) {
    mutateRowIsSelected(selection, parentRow.id, false, false, table)
  }

  return syncParentRowSelection(parentRow, selection, table)
}
```
