### ISSUE TITLE
[V8] [alpha.88]: Grouping broken: getValue in aggregated cell undefined

### ISSUE THREAD

**Issue by mgm1313** [TanStack/table#3968]
### Describe the bug

It seems that aggregating cells stopped working in [the latest release (alpha.88)](https://github.com/TanStack/table/releases/tag/v8.0.0-alpha.88). 
From debugging it seems that calling `getValue()` now always returns `undefined`, which then breaks rendering. 

I also checked with the [grouping example](https://github.com/TanStack/table/tree/alpha/examples/react/grouping), and that one breaks as well when updating to `.88`.

### Your minimal, reproducible example

https://codesandbox.io/s/tender-johnson-i1wdqh?file=/package.json

### Steps to reproduce

1. Update to `@tanstack/react-table@8.0.0-alpha.88`. 
2. Try grouping a column. 

### Expected behavior

See the aggregated value, based on the `aggegrationFn`. 

### How often does this bug happen?

Every time

### Platform

Every OS and Browser.

### react-table version

8.0.0-alpha.88

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Fixed in latest beta!
