### ISSUE TITLE
Docs: Bad footer positioning making it hard to click codesandbox run button

### ISSUE THREAD

**Issue by anubra266** [TanStack/table#3969]
I'll love to work on this, I just need pointers to the code for footer. I've searched the repo, can't find it.

### Describe the bug

https://user-images.githubusercontent.com/30869823/170808830-451be591-fdbe-4daf-b6c8-d734addc303e.mp4

_No response_

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
I added some padding to help here. Thanks!
