### ISSUE TITLE
npm outdated shows the latest @tanstack/react-table is 0.0.1-alpha.0

### ISSUE THREAD

**Issue by talatkuyuk** [TanStack/table#3970]
### Describe the bug

When you run the command `npm outdated`:
Current: 8.0.0-beta.2
Wanted: 8.0.0-beta.2
Latest: 0.0.1-alpha.0   <------- here

And the default branch is still alpha. I don't know it may be set intentionally.

### Your minimal, reproducible example

none

### Steps to reproduce

run the command `npm outdated`

### Expected behavior

I expected the latest version not to be alpha.0, but at least alpha.88 or better beta.2

### How often does this bug happen?

Every time

### Screenshots or Videos

![1DB6A518-0E4C-4003-BB1B-C3733CB8BDC0_4_5005_c](https://user-images.githubusercontent.com/30029208/170821587-566f0fbc-4fbe-4324-badc-33184149d375.jpeg)

### Platform

macos

### react-table version

v8.0.0-beta.2

### TypeScript version

v.4.6.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
There is no latest/stable release available yet, only alpha and beta, so this is correct.

**Comment by talatkuyuk** [comment]
Okey, then. Thanks for your reply.

**Comment by bunea** [comment]
Sorry to comment on a closed issue, but installing `@tanstack/react-table` with `yarn` causes the `0.0.1-alpha0` version to be installed as it is tagged as `latest` in `npm`. In order to install the latest beta version I had to specify it as `yarn add @tanstack/react-table@8.0.0-beta.3`.  It's not a huge deal, I'll leave this here just in case someone runs into the same thing.

**Comment by xstevenyung** [comment]
The easiest to be sure to be up-to-date is to use the `@beta` tag instead (e.g. `npm install @tanstack/react-table@beta`).

Not sure why the latest tag is not used but this is rather confusing
