### ISSUE TITLE
[v8] columnFilters broken in alpha88 - column.filterFn is undefined

### ISSUE THREAD

**Issue by claudious96** [TanStack/table#3972]
### Describe the bug

Starting from v8 alpha-88 (present in beta-2 too), column filtering is broken. The `getFilterFn()` fails on any column since it access `column.filterFn` which is undefined. Even if the filtersFn is correctly defined in the columnDef, it is not set into the Column object anymore due to [e6c511f](https://github.com/TanStack/table/commit/e6c511f70b75354ab9ada42082619a0391d631b4#diff-ecfb42689379fb8b0ebe6328e01b25aba4a31d2d076b723ff9fcaf502ac9d0f7L101), possibly causing #3968 too.

### Your minimal, reproducible example

https://codesandbox.io/s/icy-fire-pwzbdw

### Steps to reproduce

1. Open the code sandbox
2. Try to filter on any column
3. See warning in the console

### Expected behavior

Correctly get the filterFn.

### Platform

- OS: Ubuntu 20.04 
- Browser: Chrome 101.0.4951.64

### react-table version

v8-alpha-88

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by talatkuyuk** [comment]
+ 1

I don't use any custom filter functions. My both globalFiltering and columnFiltering would work; but suddenly the only columnFiltering is broken, it stops to work. (globalFiltering has no problem.)

**Comment by claudious96** [comment]
@talatkuyuk you're right, it's a more general problem of columnFilters, it's not specific to custom filters. I updated the issue title and description.

**Comment by tannerlinsley** [comment]
Fixed in latest alpha
