### ISSUE TITLE
[8.0.0-beta.3] column.meta is always undefined

### ISSUE THREAD

**Issue by talatkuyuk** [TanStack/table#3983]
### Describe the bug

When you set column meta type;
```ts
const table = createTable()
  .setRowType<User>()
  .setColumnMetaType<string>();
```

I would get the column meta via `column.meta`; and it would work before. But, for the moment, `column.meta` returns always `undefined`.

Is it possible to get back `column.meta` is available?

### Your minimal, reproducible example

none

### Steps to reproduce

- set the meta type
- set the meta info in the column definition
- try to get `column.meta` from the instance

### Expected behavior

As a user, I expected the `column.meta` is available like before

### How often does this bug happen?

Every time

### Platform

macos

### react-table version

beta.3

### TypeScript version

4.7.2

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by zhongjiaguo001** [comment]
> 它应该在 column.columnDef.meta 上可用
I've defined meta in columns, but I'm encountering a type error when using it. How should I resolve this?
![image](https://github.com/TanStack/table/assets/44691489/9d12f189-f49e-4f15-ad7d-24b40e781bd0)
![image](https://github.com/TanStack/table/assets/44691489/2dcaf0cd-82d5-403b-ad24-359c6fa4f898)
Thank you for your time
