### ISSUE TITLE
[8.0.0-beta.3] Grouped rows are sorted when sorting sub rows

### ISSUE THREAD

**Issue by slouchymunchkin** [TanStack/table#3992]
### Describe the bug

As the title says. Is this expected behavior?

### Your minimal, reproducible example

https://codesandbox.io/s/fragrant-cache-so21ko?file=/src/main.tsx

### Steps to reproduce

Sort the column "First Name" and the column grouped column "Status" will also be sorted.

### Expected behavior

Only the rows in the column "First Name" should be sorted.

### How often does this bug happen?

Every time

### Platform

WIndows

### react-table version

8.0.0-beta.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
The Grouped rows are just showing in the order in which they first appear when sorted by another column. I'm not sure this is unexpected behavior, even if its a jaring shift.

**Comment by slouchymunchkin** [comment]
I'm not sure I follow. Did you try to sort other columns (asc/desc) in the codesandbox example? 

Heres the top (grouped) rows are in their default order:

![image](https://user-images.githubusercontent.com/8056729/171929326-4a1f0acd-06bd-42e0-9da0-a199f305b437.png)

Heres the top (grouped) rows sorted when I sort the column "Last Name":

![image](https://user-images.githubusercontent.com/8056729/171930140-f054ebc3-f06a-4c47-8c87-a62c69bb327c.png)

Compare this to ag-grid for example:

https://www.ag-grid.com/example

If you group the column "Language" in the example above, and then sort the column "Name", you'll see that the top (grouped) rows are not sorted, only the sub rows.

Shouldn't this be the expected behavior for grouped rows, since they have undefined values in the other columns?
