### ISSUE TITLE
[8.0.0-beta.8] Original sort order of sub rows is not restored when sorting through columns

### ISSUE THREAD

**Issue by slouchymunchkin** [TanStack/table#4002]
### Describe the bug

When sorting columns with sub rows, either through grouping or sub row arrays, the original sort order of the sub rows is not restored.

### Your minimal, reproducible example

https://codesandbox.io/s/frosty-kepler-x7l5uv

### Steps to reproduce

1. Open codesandbox example
2. Expand any row in "Grouped rows" table or "Sub rows" table
3. Take note of the sub rows order
4. Click on column "First Name" three times to go through asc, desc, no sort (or any other column with sub rows)
5. Compare the sub rows order with the original

### Expected behavior

Sub rows should return to their original order after going through sorting (asc, desc, no sort).

### How often does this bug happen?

Every time

### Screenshots or Videos

Original order of sub rows

![image](https://user-images.githubusercontent.com/8056729/172328065-63672c99-7db6-4501-8ea8-a9c203e15986.png)

Order of sub rows after sorting through column "First Name"

![image](https://user-images.githubusercontent.com/8056729/172328394-f6201ee4-7673-49bb-a88e-c4ddc44da8bd.png)

### Platform

Windows

### react-table version

8.0.0-beta.8

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Fixed in latest version
