### ISSUE TITLE
Setting ColumnsFilters create an error when working with expanded rows

### ISSUE THREAD

**Issue by ceciledelmon** [TanStack/table#4006]
### Describe the bug

When I set a value for a columnFilters I have the following error : 

`Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application.`

This only happens with the expanded configuration (This bug can be found in the example provided for the case in the doc)

### Your minimal, reproducible example

Go to https://tanstack.com/table/v8/docs/examples/react/expanding

### Steps to reproduce

1 . Go to https://tanstack.com/table/v8/docs/examples/react/expanding
2 . type something in one of the column input
3 . 💥 

### Expected behavior

being able to use column filtering and subrows together

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/9010057/172461376-588f75b2-ed8e-46a6-a106-7ca8c2f9269c.png)

### Platform

- MacOs

### react-table version

8.0.0-beta.8

### TypeScript version

4.5.5

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
yes, I'm running into this too. Max call stack size exceeded

Didn't realize it was the expanding rows that were causing it, but I find that to be the case too

**Comment by StarHosea** [comment]
same on 8.0.13

**Comment by tannerlinsley** [comment]
Seems to be fixed in the latest version.
