### ISSUE TITLE
[beta.9] pageCount is not correctly set

### ISSUE THREAD

**Issue by oeddyo** [TanStack/table#4036]
### Describe the bug

I'm allowing users to change between "manualPagination" = true and false. 

Since when it's manualPagination, I'll need to set pageCount as -1, and when user trigger manualPagination = false, I'll need to either clear out pageCount (preferable, but such API does not exist) or set a pageCount by using `Math.ceil(data.length / pageSize)`. 

I'm setting pageCount by using setPageCount function but it doesn't seem to work. When I set the pageCount and get from instance.getPageCount, it's not updated. Unfortunately it's a little involved and from the source code I didn't understand why. 

In the example below (re-using Column Ordering example) I'm simply setting pageCount and console the value of getPageCount directly. It appears pageCount is never changed 

https://codesandbox.io/s/admiring-cherry-eb0ljw?file=/src/main.tsx:2064-2080

### Your minimal, reproducible example

https://codesandbox.io/s/admiring-cherry-eb0ljw?file=/src/main.tsx:2064-2080

### Steps to reproduce

1. go to console
2. see the line "Now getting pageCount" and check it's always -1 despite explicitly setting it to 5 in the code

### Expected behavior

getPageCount should return correct value

### How often does this bug happen?

Every time

### Platform

MacOS

### react-table version

beta.9 

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
This issue is out of date now, and appears to be fixed in the latest version. Thanks!

**Comment by oeddyo** [comment]
@tannerlinsley do you mean beta.9 or another version? The test was done on beta.9

**Comment by WickyNilliams** [comment]
i am still seeing this issue even on latest. here's a minimal reproduction https://codesandbox.io/p/sandbox/beautiful-firefly-n36q4y?file=%2Fsrc%2Fmain.tsx

`setPageCount` sets state inside `pagination`, and only ever reads the previous value from `options.pageCount`: 
https://github.com/TanStack/table/blob/5f667ee4ad186939328b626e735defd7e29a0a79/packages/table-core/src/features/Pagination.ts#L168-L173

and `getPageCount` only ever returns the value from options, never from state:
https://github.com/TanStack/table/blob/5f667ee4ad186939328b626e735defd7e29a0a79/packages/table-core/src/features/Pagination.ts#L245-L251

so between the two, the value in `state.pagination.pageCount` is never used anywhere
