### ISSUE TITLE
The basic v8 react-table example on documentation page is broken

### ISSUE THREAD

**Issue by xJkit** [TanStack/table#4038]
### Describe the bug

The basic react-table example demo page is broken.

![CleanShot 2022-06-19 at 12 35 08@2x](https://user-images.githubusercontent.com/18704345/174466007-55e94ebc-dd25-4005-91c5-db87fbbaca1e.jpg)

### Your minimal, reproducible example

https://codesandbox.io/s/github/tanstack/table/tree/main/examples/react/basic?from-embed

### Steps to reproduce

Open codesandbox example every time.

### Expected behavior

Should show the basic react table V8 as expected.

### Platform

Browser

### react-table version

v8.0.0

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Fixed!
