### ISSUE TITLE
Automatic datetime sorting function crashes when null values exist

### ISSUE THREAD

**Issue by pavlos256** [TanStack/table#4041]
### Describe the bug

A column with mostly `Date` values will automatically use the `datetime` sort function, but that function does not handle nulls and crashes on the call to `getTime()`.

### Your minimal, reproducible example

https://codesandbox.io/s/hardcore-brook-91xtu9?file=/src/main.tsx

### Steps to reproduce

1. Open sandbox
2. Click on the `createdAt` column to sort it
3. App crashes

### Expected behavior

The datetime sorting function should not crash with null / undefined values.

### How often does this bug happen?

Every time

### Platform

All

### react-table version

8.0.0-beta.9

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by abdullahtariq1171** [comment]
Should we check for nullish values in [sortinFns](https://github.com/TanStack/table/blob/main/packages/table-core/src/sortingFns.ts)? @tannerlinsley 


This is where it is crashing 

https://github.com/TanStack/table/blob/cc9ff13e35eef7b4bf6c9ba14c674d02a462c032/packages/table-core/src/sortingFns.ts#L39-L40


---


@pavlos256 A workaround would be to add your own sortingFn and use that, like below:

Define your custom sortingFn
```
let table = createTable()
.setOptions({
  sortingFns: {
    sortNullableDate: (rowA: any, rowB: any, columnId: any): number => {
      function compareBasic(a: any, b: any) {
        return a === b ? 0 : a > b ? 1 : -1
      }

      return compareBasic(
        (rowA.getValue(columnId) as Date)?.getTime(), // added "?." on this line
        (rowB.getValue(columnId) as Date)?.getTime() // added "?." on this line
      )
    },
  },
})
```
use it for desired column
```
table.createDataColumn('createdAt', {
  sortingFn: 'sortNullableDate',
}),

```

**Comment by tannerlinsley** [comment]
I think we should handle it in the core. PRs are welcome :)
