### ISSUE TITLE
V8 Sorting provokes scroll on data change

### ISSUE THREAD

**Issue by greglds** [TanStack/table#4042]
### Describe the bug

Without sorting, scroll position doesn't change when I update my data. With sorting, it does.

### Your minimal, reproducible example

https://codesandbox.io/s/upbeat-dhawan-nsovyy

### Steps to reproduce

The example provided is just React-Table sorting example slightly modified (number of data rows and number of rows displayed).

1. Click on a header in order to sort a column
2. Click on _Refresh Data_ button: sometimes it scrolls, sometimes it does not

### Expected behavior

Scroll position should not change when data changes

### How often does this bug happen?

Often

### Platform

OS: Windows
Browser: Chrome Version 102.0.5005.115

### react-table version

8.0.0-beta.8

### TypeScript version

4.3.5

### Additional context

Same behavior as v7 #3768

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
I can't really explain this. I'll ask around.

**Comment by tannerlinsley** [comment]
I haven't been able to find a solution to this, let alone a reason "why". My best guess is that browsers are basing their scroll position off of an anchoring element, in this case a `tr`. When the sorting/filtering changes and that row changes position, the browser thinks that the upper-bounding content before the `tr` has changed in the same way as a normal layout shift and tries to maintain the viewport position relative to the `tr`. Obviously this is not what we want to happen, but I'm not sure how to fix it without completely destroying the reconciliation perf of React. If we replace the element, it will create unnecessary paints. 

I wish I had better advice for this, but it seems pretty core to how browser scroll state works. We'll keep our ears to the ground on ways to get around this in the future.

**Comment by coalman** [comment]
Turning off [scroll anchoring](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor/Guide_to_scroll_anchoring) fixed this for me:

```css
tr {
  overflow-anchor: none;
}
```

I wasn't able to load the codesandbox, but I was seeing the same issue when using a stable key on the `tr` elements on chrome (firefox and safari didn't have this issue).
