### ISSUE TITLE
[beta.9] enableMultiRowSelection = false is ignored

### ISSUE THREAD

**Issue by oeddyo** [TanStack/table#4057]
### Describe the bug

when setting enableMultiRowSelection =  false, the table still happily allow multirow selection

### Your minimal, reproducible example

https://codesandbox.io/s/busy-fire-zh2r9r?file=/src/main.tsx

### Steps to reproduce

The only change I added to the example is to set allow multiple selection = false (default is true)

Go to the table, and you can still select many rows

### Expected behavior

only one row can be selected at each time

### How often does this bug happen?

Every time

### Platform

codesandbox

### react-table version

beta.9

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by oeddyo** [comment]
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/1943146/175782384-53855ddd-df96-46d3-bef7-98e0e1cccc80.png">

**Comment by tannerlinsley** [comment]
I believe this is fixed in the latest version. Regardless, this example is now out of date with the stable API. If the issue persists, please reopen with the latest version.
