### ISSUE TITLE
The `main` branch requires a case-sensitive file-system

### ISSUE THREAD

**Issue by sampi** [TanStack/table#4058]
### Describe the bug

Trying to check out `TanStack/table.git` results in path collisions on a case-insensitive filesystem

```
➜ git clone https://github.com/TanStack/table.git
Cloning into 'table'...
remote: Enumerating objects: 17131, done.
remote: Counting objects: 100% (218/218), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 17131 (delta 136), reused 211 (delta 134), pack-reused 16913
Receiving objects: 100% (17131/17131), 19.36 MiB | 23.08 MiB/s, done.
Resolving deltas: 100% (12128/12128), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'docs/api/core/Cell.md'
  'docs/api/core/cell.md'
  'docs/api/core/Column.md'
  'docs/api/core/column.md'
  'docs/api/core/Header.md'
  'docs/api/core/header.md'
  'docs/api/core/Row.md'
  'docs/api/core/row.md'
  'docs/api/core/Table.md'
  'docs/api/core/table.md'
```

### Your minimal, reproducible example

https://github.com/TanStack/table/tree/main/docs/api/core

### Steps to reproduce

1. Use Windows, macOS, or any other OS with a case-insensitive filesystem
2. run `git clone https://github.com/TanStack/table.git`
3. try to switch branches, or commit something, etc.

### Expected behavior

As a user/developer, I expect to be able to switch branches in the repo that I've checked out, or at least have a clean staging area after running `git reset --hard`

### How often does this bug happen?

Every time

### Screenshots or Videos

![Screen Shot 2022-06-27 at 12 43 53](https://user-images.githubusercontent.com/524272/175925080-2f1b4dd5-5cfa-4420-a09e-90446cadcdd9.png)
![Screen Shot 2022-06-27 at 12 43 08](https://user-images.githubusercontent.com/524272/175925092-6eea75be-23bf-47c3-ba51-2b7a4bf9c714.png)

### Platform

macOS - APFS

### react-table version

main

### Additional context

a workaround was to check out the `v7` branch directly using:

```
git clone -b v7 https://github.com/TanStack/table.git
```

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
I would suggest tracking casename changes if you haven't already: `git config core.ignorecase false`. Regardless, these case name changes were intentional, so there's not much we can do as far as I know.
