### ISSUE TITLE
[8.0.6]Could not find a declaration file for module '@tanstack/vue-table'

### ISSUE THREAD

**Issue by MingRock** [TanStack/table#4062]
### Describe the bug

Could not find a declaration file for module '@tanstack/vue-table'

### Your minimal, reproducible example

-

### Steps to reproduce

-

### Expected behavior

-

### Platform

-

### react-table version

v8.0.6

### TypeScript version

v4.5.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by wojtekolek** [comment]
Same story with `@tanstack/react-table` (v8.0.6 and TS v4.7.4).

**Comment by mmospanenko** [comment]
8.0.0-beta.9 is last working release. 8.0.0 had wrong metadata (8.0.1 in lock)

**Comment by EvHaus** [comment]
Still seeing similar issues with 8.0.9:

```
error TS7016: Could not find a declaration file for module '@tanstack/table-core'. '/home/runner/work/reservepro/reservepro/node_modules/@tanstack/table-core/build/cjs/index.js' implicitly has an 'any' type.
```

**Comment by Himself65** [comment]
same to me

**Comment by rizwanliaqat97** [comment]
Same to me as well 😞

**Comment by aelfannir** [comment]
I my case, I use  `@tanstack/react-table`, I had to fix the issue temporary, locking the version from `"^8.0.0-beta.9"` to `"8.0.0-beta.9"` works

Rollback to `"^8.0.0-beta.9"` when the issue is fixed

**Comment by Troom** [comment]
@aelfannir  Thanks a lot. Now it work as excepted.
Remember to type "npm install" in terminal to reinstall package.json, after changing @tanstack/react-table to 8.0.0-beta.9

**Comment by Himself65** [comment]
the latest version works

**Comment by EvHaus** [comment]
Confirmed. Seems fixed for me in 8.0.13. Thank you!

**Comment by EvHaus** [comment]
This problem is back again in 8.1.1.

**Comment by tannerlinsley** [comment]
> This problem is back again in 8.1.1.

I can’t replicate. The file is available. https://unpkg.com/browse/@tanstack/react-table@8.1.1/build/types/index.d.ts

**Comment by EvHaus** [comment]
Apologies. It was a different problem:

```
components/DataTable/DataTable.tsx:4:26 - error TS2305: Module '"@tanstack/react-table"' has no exported member 'useTableInstance'.

4 import {getCoreRowModel, useTableInstance} from '@tanstack/react-table';
```

I probably need to update some code.

**Comment by tannerlinsley** [comment]
useReactTable ;)

**Comment by velocityzen** [comment]
this issue is back in 8.5.11

**Comment by refex** [comment]
Same problem for @tanstack/react-table v8.10.3, is there a fix?

**Comment by akhilaravind** [comment]
Same issue for version 8.11.2 ( React)

**Comment by 1UwUL** [comment]
Same issue for @tanstack/react-table 8.20.5

**Comment by marco910** [comment]
For me, restarting the TypeScript server in VS Code solved the issue:
- Windows in VS Code: Press Ctrl + Shift + P and select >TypeScript: Restart TS server.
- macOS in VS Code: Press ⇧ + ⌘ + P or F1 and select >TypeScript: Restart TS server.
