### ISSUE TITLE
[v8.0.8]Could not find a declaration file for module '@tanstack/react-table'

### ISSUE THREAD

**Issue by JeomJeom** [TanStack/table#4070]
### Describe the bug

Error message `Could not find a declaration file for module '@tanstack/react-table'` when importing it.

### Your minimal, reproducible example

-

### Steps to reproduce

I intended to migrate from v7 to v8, however, I got this error message `Could not find a declaration file for module '@tanstack/react-table'` when importing it.

### Expected behavior

As a user, I expect it to work better than react-table v7.

### Screenshots or Videos

> TS7016: Could not find a declaration file for module '@tanstack/react-table'. './node_modules/@tanstack/react-table/build/cjs/react-table/src/index.js' implicitly has an 'any' type.   Try `npm i --save-dev @types/tanstack__react-table` if it exists or add a new declaration (.d.ts) file containing `declare module '@tanstack/react-table';

### Platform

- WebStorm
- macOs 
- Chrome

### react-table version

v8.0.8

### TypeScript version

v4.7.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [x] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Carlos0934** [comment]
I have that problem too, package on node_modules doesn't have type declarations. I just started a new project with version 8.0.8. 

To make sure, I tried to install versions 8.0.3 to 8.0.6 with no results.

**Comment by pencilcheck** [comment]
Still no type information in project install using pnpm, i have the latest ^8.20.5
