### ISSUE TITLE
"build/types/index.d.ts" is not included in the npm package of "@tanstack/match-sorter-utils@8.0.x"

### ISSUE THREAD

**Issue by freewind** [TanStack/table#4071]
### Describe the bug

```
npm i @tanstack/match-sorter-utils
```

Then use in typescript:

```
import {compareItems, rankItem, rankings} from '@tanstack/match-sorter-utils';
```

![image](https://user-images.githubusercontent.com/333781/176399679-9f1411a9-39f9-48d7-893d-9c2cd259700b.png)

Then go to the download package in node_modules:

![image](https://user-images.githubusercontent.com/333781/176399766-ad2068da-df8c-460d-9ed7-c55acf098408.png)

There is no "build/types/index.d.ts" though it's defined in the package.json:

```
{
  "name": "@tanstack/match-sorter-utils",
  "authors": [
    "Kent C. Dodds",
    "Tanner Linsley"
  ],
  "version": "8.0.8",
  // ...
  "types": "build/types/index.d.ts",
  // ...
}

```

### Your minimal, reproducible example

https://codesandbox.io/s/youthful-edison-ul4zxi?file=/src/main.tsx

### Steps to reproduce

Although the official demo is working, the typing is not correct.

![image](https://user-images.githubusercontent.com/333781/176401209-fddd8fe6-1a64-4072-be32-335b545ea002.png)

### Expected behavior

as a user, I want the "build/types/index.d.ts" file to be included in the npm package of "@tanstack/match-sorter-utils@8.0.x"

### How often does this bug happen?

Every time

### Platform

Every type

### react-table version

8.0.8

### TypeScript version

4.5.4

### Additional context

The template is too boring for such kind of issue report

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Fixed in the latest version
