### ISSUE TITLE
[8.0.13] enableSortingRemoval does not work as intended

### ISSUE THREAD

**Issue by DreierF** [TanStack/table#4078]
### Describe the bug

The `enableSortingRemoval` does not seem to work. AFAIU it this should be the inverted version of `disableSortRemove` from react-table v7. However as you can see in the example when clicking on the column header, the first time the sorting order changes to ascending. On the next click it changes to descending, but on the third click with `enableSortingRemoval: false` I would have expected to get back to ascending. Instead the column is stuck at descending on all follow-up clicks.

### Your minimal, reproducible example

https://codesandbox.io/s/serverless-wildflower-khkcu9?file=/src/main.tsx

### Steps to reproduce

The sample is equivalent to https://tanstack.com/table/v8/docs/examples/react/sorting + the option `enableSortingRemoval: false`.

Click on "Profile Progress" for at least three times. The behavior is the same for most columns, but for some strange reason the "Status" column seems to work as expected

### Expected behavior

The sorting order switches between ascending and descending order with every click.

### How often does this bug happen?

Every time

### Screenshots or Videos

https://user-images.githubusercontent.com/5631865/176750185-363325f8-4777-4555-a188-44ef6478371c.mov

### Platform

macOS, Chrome 103

### react-table version

8.0.13

### TypeScript version

4.7.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Fixed in the latest release :)

**Comment by alexalannunes** [comment]
![Image](https://github.com/user-attachments/assets/b613dfc6-3974-40cb-ba2c-328436595929)

@tannerlinsley what happened with this prop?

 "@tanstack/react-table": "^8.21.2",
