### ISSUE TITLE
header.column.columnDef.header return undefined 

### ISSUE THREAD

**Issue by Abdulrahmanelheyb** [TanStack/table#4081]
### Describe the bug

flexRender function is not accept the undefined type

this error is currently on the codesandbox  React Example: Filters

### Your minimal, reproducible example

CodeSandbox 

### Steps to reproduce

1. Go to [React Example Filters](https://tanstack.com/table/v8/docs/examples/react/filters) 
2. Open src folder in codesandbox
3. Scroll to thead jsx element
4. look to thead > tr > th 
5. In the th element header text flexRender function

### Expected behavior

I expect to not see any errors

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/45883300/176955315-138e9a9a-0b16-4ac0-9f16-1994161c29ff.png)

### Platform

Windows

### react-table version

@tanstack/react-table 8.1.1

### TypeScript version

4.8.0

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Good catch. Let’s update that.

**Comment by Abdulrahmanelheyb** [comment]
I currently testing this library I using with my project.
