### ISSUE TITLE
Document Bug ! 

### ISSUE THREAD

**Issue by mohammadgarmroodi** [TanStack/table#4085]
### Describe the bug

https://tanstack.com/table/v8/docs/api/column-ordering.md

some of document items dont show correct content!

### Your minimal, reproducible example

https://tanstack.com/table/v8/docs/api/column-ordering.md

### Steps to reproduce

Just open the link in the description...

### Expected behavior

Show Correct Content!

### Platform

Windows

### react-table version

8.1.1

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
The original link to this page has been fixed.
