### ISSUE TITLE
Documentation bug - pagination api page does not load

### ISSUE THREAD

**Issue by JackMcBride98** [TanStack/table#4091]
### Describe the bug

go to https://tanstack.com/table/v8/docs/api/pagination.md
The page does not load

### Your minimal, reproducible example

https://tanstack.com/table/v8/docs/api/pagination.md

### Steps to reproduce

1. Go to https://tanstack.com/table/v8/docs/api/pagination.md
2. IT doesnt load

### Expected behavior

I would expect it to load

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/37148941/177123812-1b856e6c-a7c8-4a08-af33-eb1f7e0ecae6.png)

### Platform

Microsoft edge

### react-table version

v8

### Additional context

I can read it here for now
https://github.com/TanStack/table/blob/main/docs/api/features/pagination.md

Reloading the page gives this error

Unexpected Server Error

Cannot read properties of null (reading 'title')

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by aisflat439** [comment]
I am experiencing similar issues with most of the react documentation pages. Im on Chrome and don't think this is a browser specific issue.
