### ISSUE TITLE
Row original property is now optional

### ISSUE THREAD

**Issue by ValentinH** [TanStack/table#4102]
### Describe the bug

We just started migrating from v7 to v8 and it's going well so far! 🙂 

One small thing that I noticed is that now the `Row['original']` type is optional:
https://github.com/TanStack/table/blob/51ec83997e5964a82797fc037219a28d108de3cd/docs/api/core/Row.md?plain=1#L35-L41

This forces us to use optional chaining every time we access it. I've checked at runtime and the data is always present though.

On the documentation, the `row.original` property is used [here](https://tanstack.com/table/v8/docs/guide/column-defs#cell-formatting) without optional chaining though:
![image](https://user-images.githubusercontent.com/2678610/177311485-9665ded5-30d0-43df-92d6-15f130827078.png)

Is this correct?

### Your minimal, reproducible example

https://tanstack.com/table/v8/docs/guide/column-defs#cell-formatting

### Steps to reproduce

Check this source: https://github.com/TanStack/table/blob/51ec83997e5964a82797fc037219a28d108de3cd/packages/table-core/src/core/row.ts#L8

### Expected behavior

The property should not be optional (if possible).

### Platform

MacOS

### react-table version

8.0.14

### TypeScript version

4.5.5

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
This undefined possibility is for grouping rows that do not have an original row.

**Comment by ValentinH** [comment]
Do you think there could be a way to detect whether a table uses grouping in order to make it optional or not?

If yes, the lib could also export both a `Row` and a `GroupableRow` type .

**Comment by tannerlinsley** [comment]
Yes, this is possible, but then row types would become a union of normal row and grouped row, and then you would need to condition your way around the potential undefined anyway. I will look into a way to make it better, but it’ll be a while.

**Comment by alainrjacques** [comment]
I had this thought as well, since I am still learning typescript, would be cool to have something like a type like:
`original: TData | never `
Where `never` was inferred for grouped rows otherwise `TData` but understand that this can be difficult

**Comment by tannerlinsley** [comment]
Alright, for the time being, I just released a fix where `original` is never undefined. To be true to that, grouped rows now use their first leaf row's original row as their own original row.
