### ISSUE TITLE
V7 : ReactTable - Need to change Default Behavior :  Column with Input | TextArea always keeps value when changing page by pagination

### ISSUE THREAD

**Issue by Cin-Cyrus** [TanStack/table#4111]
### Describe the bug

# In my project, I use ReactTable V7.

## Page 1 - column [ Comment ] -  Index = 0 => I type a "Test" text.

![image](https://user-images.githubusercontent.com/103924439/177758057-ca9f9337-f3f1-4b9f-a7be-0e77525d6482.png)

## Page 2 - column [ Comment ] - Index = 0 => I still see  "Test" text.

![image](https://user-images.githubusercontent.com/103924439/177758347-d0fa5647-f27d-48dc-91e5-b20d62493caf.png)

### Your minimal, reproducible example

https://react-table-v7.tanstack.com/docs/examples/pagination-controlled

### Steps to reproduce

# In this step, I will use your example.

# https://react-table-v7.tanstack.com/docs/examples/pagination-controlled

## Step 01: I define the Cell of  column [ progress ]

![image](https://user-images.githubusercontent.com/103924439/177759868-70ddb0ce-05e6-45cd-bb66-3031005902e2.png)

## Step 02: Page 1:  I type "Test" to **input 01** & **input 02** in column [ progress ]
![image](https://user-images.githubusercontent.com/103924439/177760311-4f569d74-da79-4cdf-bc8c-4c86acacc86a.png)

## Step 04:  At Page 2: I still see the value "Test" in **input 01** & **input 02** 

![image](https://user-images.githubusercontent.com/103924439/177760615-db794317-fe6c-4796-995f-bc1ce194562a.png)

### Expected behavior

As a user, I expect the value of input will be cleared on new page.

### How often does this bug happen?

Every time

### Platform

All Platforms.

### react-table version

v7

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
This has to do with the `key` you are passing to your row (or cell) objects. If the key stays the same (like an index), it will keep the state for that row/cell. 

In short, if you want the state to reset, use a better key like the row ID or something unique to the row.

**Comment by Cin-Cyrus** [comment]
> 
@tannerlinsley 

Thank you very much !! Here is my solution. The custom key was changed in tr tag

![image](https://user-images.githubusercontent.com/103924439/178090565-5dd21c02-31c8-442e-8cd5-56e2be0f45bc.png)

![image](https://user-images.githubusercontent.com/103924439/178090591-650f3da8-560c-435a-8453-60fb234ca651.png)
