### ISSUE TITLE
Header is defaulting to column ID, when header prop is not provided in column definiiton

### ISSUE THREAD

**Issue by mateuszgazdziak** [TanStack/table#4117]
### Describe the bug

According to docs:
https://tanstack.com/table/v8/docs/api/core/column-def#header

`header` is an optional parameter. I would expect that, if it is not provided, nothing will be shown in header. Current behaviour is that header is filled with column id.

### Your minimal, reproducible example

-

### Steps to reproduce

Define column without `header` prop.

### Expected behavior

Header should be empty.

### How often does this bug happen?

Every time

### Platform

-

### react-table version

8.1.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
You can change the default behavior for this:

```tsx
useReactTable({
  defaultColumn: {
    header: null // or ''
  }
})
```

**Comment by mateuszgazdziak** [comment]
> You can change the default behavior for this:
> 
> ```tsx
> useReactTable({
>   defaultColumn: {
>     header: null // or ''
>   }
> })
> ```

@tannerlinsley Yeah, I know that. I wonder if this should not be documented somehow. In v it worked differently.
