### ISSUE TITLE
Not working with React18.x

### ISSUE THREAD

**Issue by maneetgoyal** [TanStack/table#4120]
### Describe the bug

Build routine has:

```
    ...buildConfigs({
      name: 'react-table',
      packageDir: 'packages/react-table',
      jsName: 'ReactTable',
      outputFile: 'react-table',
      entryFile: 'src/index.tsx',
      globals: {
        react: 'React',
      },
    }),
```

Should ReactDOM be also externalized?

---

Getting the following error while working with React 18.2:

```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

### Your minimal, reproducible example

N/A

### Steps to reproduce

N/A

### Expected behavior

Should work properyl with react 18

### Platform

macOS, Chrome

### react-table version

8.1.3

### TypeScript version

4.7.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
- The examples all use v18
- React Table does not import the `react-dom` package, so there is no need for any bundling options.
 
It's likely you actually have two different version of react being imported, or you are attempting to use an `npm link`-ed version of the library which itself resolves to a different `react` package via node-module resolution (I run into this all the time and it's very annoying)
