### ISSUE TITLE
React controlled pagination sandbox not working

### ISSUE THREAD

**Issue by HermanNygaard** [TanStack/table#4122]
### Describe the bug
[React controlled pagination sandbox](https://tanstack.com/table/v8/docs/examples/react/pagination-controlled
) not working, nothing renders and error shows in console:
```
The above error occurred in the <App> component:


    at App (https://2x8b5w.sse.codesandbox.io/src/main.tsx:26:26)

```

### Your minimal, reproducible example

https://tanstack.com/table/v8/docs/examples/react/pagination-controlled

### Steps to reproduce

Go to https://tanstack.com/table/v8/docs/examples/react/pagination-controlled

### Expected behavior

No errors

### How often does this bug happen?

Every time

### Platform

chrome on macos

### react-table version

n/A

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KerwinMa** [comment]
the controlled example is out of date with new version. pageCount is not in state anymore. Just for others. Ref: https://github.com/TanStack/table/discussions/3999
