### ISSUE TITLE
Grouping is broken

### ISSUE THREAD

**Issue by TimisRobert** [TanStack/table#4125]
### Describe the bug

Grouping sends any component that has the table in a infinite loop.
Just go to the official sandbox example to see that the page will get stuck.

### Your minimal, reproducible example

https://tanstack.com/table/v8/docs/examples/react/grouping

### Steps to reproduce

Open link

### Expected behavior

To work normally

### How often does this bug happen?

Every time

### Platform

Chromium 103.0.5060.114 Arch Linux

### react-table version

8.2.2

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Yuck you’re right! We’ll get this fixed ASAP.

**Comment by TimisRobert** [comment]
Thanks! If it helps I noticed a weird thing, if I have the component already mounted without getGroupedRowModel: getGroupedRowModel() and later add it it works.

**Comment by tannerlinsley** [comment]
Seems to be fixed. 🤷

**Comment by rovolution** [comment]
@tannerlinsley what version was this fixed in?

**Comment by rovolution** [comment]
@TimisRobert i am running into the same issue...were you able to fix this by upgrading to some particular version #?

**Comment by rovolution** [comment]
I just upgraded to the latest version (8.5.11) and am still experiencing this issue when i try to instantiate the table via `useReactTable` hook the with ` getGroupedRowModel: getGroupedRowModel()`

My app is on React v16.14.0

**Comment by rovolution** [comment]
@TimisRobert should i create a new issue and reference this or would you be able to just reopen this one? thanks!

**Comment by rovolution** [comment]
@tannerlinsley @TimisRobert should i create a new issue and reference this or would you be able to just reopen this one? thanks!

**Comment by TimisRobert** [comment]
@rovolution Make sure that the data is in a useState or useMemo, that should work.

**Comment by rovolution** [comment]
@TimisRobert so i tried using `useMemo`, and its still getting into that infinite loop and crashing my browser (Anytime I try to pass in `getGroupedRowModel: getGroupedRowModel()`
