### ISSUE TITLE
Grouping weird behaviour

### ISSUE THREAD

**Issue by TimisRobert** [TanStack/table#4131]
### Describe the bug

So I'm using react-query to get data to put in the table.
If I directly use the data useQuery returns, my page crashes.
If I instead do like this:

```javascript
 const [data, setData] = useState([]);
  const { isLoading } = useQuery(
    "pmax",
    () =>
      axios.get(
        "https://---------",
        {
          headers: { Accept: "application/json" },
        }
      ),
    {
      onSuccess: ({ data }) =>
        setData(
          data
        ),
    }
  );
```

It works. 
Thanks for everything Tanner!

### Your minimal, reproducible example

--

### Steps to reproduce

--

### Expected behavior

--

### How often does this bug happen?

Every time

### Platform

Chromium 103.0.5060.114 Linux

### react-table version

8.2.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Make sure you are always passing an array to the table, even if it's empty:

```tsx
const query = useQuery(...)

// Memoize so the data isn't "new" on every render
const data = React.useMemo(() => query.data ?? [], [query.data])

const table = useTable({
  data
})
```
