### ISSUE TITLE
initialState sorting not working ? [v8 React Adapter]

### ISSUE THREAD

**Issue by ColonelCordier** [TanStack/table#4135]
### Describe the bug

Passing `initialState: { sorting: [{ id: string, desc: boolean }] }` doesn't sort the column on render.

### Your minimal, reproducible example

https://codesandbox.io/s/awesome-leaf-y8gx46?file=/src/main.tsx:2192-2204

### Steps to reproduce

1. Set `initialState: { sorting: [{ id: "lastName", desc: true }] }` in `useReactTable`
2. Reload the page
3. See the column `lastName` not being sorted

### Expected behavior

Column `lastName` should be sorted

### How often does this bug happen?

Every time

### Platform

OS: Win10 (WSL)
Browser: Chrome

### react-table version

v8.1.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by mtrenker** [comment]
You have two states with conflicting values, I'd suggest not using `initialState` and instead put your sorting in your `useState` statement at line #19.

https://codesandbox.io/s/eloquent-swirles-i633mo?file=/src/main.tsx

**Comment by ColonelCordier** [comment]
> Your problem is that you have a `state` object that overwrites the `initialState` because in line 19, you tell `useState` that the initial sorting should be `[]` or "no sorting at all".
> 
> I see two options:
> 
> * Remove the custom `state` and `onSortChange` handler and only use the `initialState` (probably easier if you don't want to do anything with the state) ([fork](https://codesandbox.io/s/stupefied-haibt-2z23dz?file=/src/main.tsx))
> * Remove the `initialState` and set the sorting in line 19 where you currently set your sorting to `[]` (better if you need more flexibility but more complex) ([fork](https://codesandbox.io/s/eloquent-swirles-i633mo?file=/src/main.tsx))

Thank you so much, I got it now !
