### ISSUE TITLE
Default row `id` is not stable or unique when data is modified

### ISSUE THREAD

**Issue by krispya** [TanStack/table#4162]
### Describe the bug

The cell `id` is meant to be a unique id, but it is based on the indice of the cell in the data representation. What this means is if you move a cell around or modify data by deleting or adding cells then its `id` changes. Even worst, other cells will inherit the `id` the cell previously had leading to all sorts of shenanigans in React if it is used as a key. I think the cell `id` should be made stable and unique such that it can be safely used as a key.

### Your minimal, reproducible example

x

### Steps to reproduce

x

### Expected behavior

x

### Platform

x

### react-table version

8.2.6

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
As far as I know, no IDs in the system are index based other than the default row ID accessor. Can you elaborate a bit more? Maybe link to the source or an example?

**Comment by krispya** [comment]
I'm sorry I just realized this was an example of me not understanding the docs the first time I read them. `getRowId` solved my issue.

To be more specific, the issue was that the row `id` was by default based on its index which causes everything that uses an id as key to be brittle. Maybe the solution here is give a big warning in the docs, but also I wonder if there is interest in having the default row id be more stable to data updates.

**Comment by tannerlinsley** [comment]
Yeah I get your sentiment. But we can only know so much about the nature of your data. The alternative of requiring a row id accessor is also not that wonderful. This is the happy medium :)
