### ISSUE TITLE
V8 Docs are broken

### ISSUE THREAD

**Issue by ureciocais** [TanStack/table#4164]
### Describe the bug

All links under feature give an error.
Also headerGroup

### Your minimal, reproducible example

https://tanstack.com/table/v8/docs/column-visibility

### Steps to reproduce

1. Go to https://tanstack.com/table/v8/docs/column-visibility
2. See error
3. Go to https://tanstack.com/table/v8/docs/header-group.md

### Expected behavior

Expecting no error

### Platform

OSX Chrome

### react-table version

latest

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
This is a bad link. Add a /features/ after /docs and it will work.
