### ISSUE TITLE
Docs: Links are broken when it is linked to the same directory

### ISSUE THREAD

**Issue by JeonJaewon** [TanStack/table#4171]
### Describe the bug

Hi, 
I found that links in the documents are broken when it is linked to same directory.
So there are many broken links in the document right now, and I wrote an example only for `guide/overview`. 
Please let me know if I missed something.

### Your minimal, reproducible example

https://tanstack.com/table/v8/docs/guide/overview

### Steps to reproduce

1. Click the [link](https://tanstack.com/table/v8/docs/guide/overview#headless)
2. Click the link `Intro`, you'll get an error page

### Expected behavior

It should be linked to `https://tanstack.com/table/v8/docs/guide/introduction`, but is actually linked to `https://tanstack.com/table/v8/docs/introduction`, so user will get an error page.

### How often does this bug happen?

Every time

### Screenshots or Videos

![스크린샷 2022-07-19 오전 2 22 53](https://user-images.githubusercontent.com/23352663/179567765-1f1e2876-8355-4123-b505-3b9fc73ea72c.png)

### Platform

Chrome version 103.0.5060.114

### react-table version

v8.2.6

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Upstream issue we are solving elsewhere due to remix.
