### ISSUE TITLE
8.3.1 breaks getIsSomeRowsSelected behaviour

### ISSUE THREAD

**Issue by EvHaus** [TanStack/table#4212]
### Describe the bug

After upgrading from 8.3.0 to 8.3.1 I've noticed that `table.getIsSomeRowsSelected()` will return `true` even if no rows are selected. Rolling back to 8.3.0 makes the issue go away. 8.3.2 also has this bug.

I suspect the problem is caused by this commit (https://github.com/TanStack/table/commit/620ba46fa74a440e19a654a08b411ab1ccf42356) but not sure why exactly.

### Your minimal, reproducible example

https://tanstack.com/table/v8/docs/examples/react/row-selection

### Steps to reproduce

Check out the row selection example page: https://tanstack.com/table/v8/docs/examples/react/row-selection Note how the checkbox in the header has the indeterminate state set to true even when nothing is selected yet.

### Expected behavior

If no rows are selected, `getIsSomeRowsSelected()` should return `false`.

### How often does this bug happen?

Every time

### Platform

macOS, Chrome

### react-table version

8.3.1

### TypeScript version

4.7.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by EvHaus** [comment]
Thanks for the quick fix @roborich. Can confirm 8.3.3 fixes the problem.

**Comment by ValentinH** [comment]
@roborich I noticed that `getIsSomeRowsSelected` returns `false` if all rows are selected. According to the documentation, this should return `true`:
![image](https://user-images.githubusercontent.com/2678610/182397300-7d9c46c4-79f9-4acb-a5bc-3f08dbc832f3.png)

IMO, it should only return false when no row is selected.

**Comment by KevinVandy** [comment]
I've noticed this too, but it makes sense if using for indeterminate logic.

**Comment by ValentinH** [comment]
I just checked and if both `checked` and `indeterminate` are `true`, the checkbox displays as checked and not as indeterminate. Therefore, I don't think this should be the reason 🙂
