### ISSUE TITLE
Svelte examples can't install dependencies

### ISSUE THREAD

**Issue by eric-naguras** [TanStack/table#4213]
### Describe the bug

I tried 2 of the Svelte examples, basic and sorting.
Neither of them could install their dependencies.

### Your minimal, reproducible example

https://github.com/TanStack/table/tree/main/examples/svelte/sorting

### Steps to reproduce

run npm install

### Expected behavior

To install depencencies

### Screenshots or Videos

```
~/projects/table/examples/svelte/sorting$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: tanstack-table-example-svelte-basic@0.0.0
npm ERR! Found: vite@2.9.14
npm ERR! node_modules/vite
npm ERR!   dev vite@"^2.9.7" from tanstack-table-example-svelte-basic@0.0.0
npm ERR!   examples/svelte/basic
npm ERR!     tanstack-table-example-svelte-basic@0.0.0
npm ERR!     node_modules/tanstack-table-example-svelte-basic
npm ERR!       workspace examples/svelte/basic from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^3.0.0" from @sveltejs/vite-plugin-svelte@1.0.1
npm ERR! node_modules/@sveltejs/vite-plugin-svelte
npm ERR!   dev @sveltejs/vite-plugin-svelte@"^1.0.0-next.42" from tanstack-table-example-svelte-basic@0.0.0
npm ERR!   examples/svelte/basic
npm ERR!     tanstack-table-example-svelte-basic@0.0.0
npm ERR!     node_modules/tanstack-table-example-svelte-basic
npm ERR!       workspace examples/svelte/basic from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/eric/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/eric/.npm/_logs/2022-07-23T05_55_57_986Z-debug-0.log
```

### Platform

elementary OS 6.1 Jólnir
Built on Ubuntu 20.04.3 LTS
Linux 5.15.0-41-generic

node:  v18.6.0
npm: 8.13.2

"devDependencies": {
    "@faker-js/faker": "^6.3.1",
    "@rollup/plugin-replace": "^4.0.0",
    "@sveltejs/vite-plugin-svelte": "^1.0.0-next.42",
    "@tanstack/svelte-table": "^8.0.0-alpha.87",
    "@tsconfig/svelte": "^2.0.1",
    "svelte": "^3.44.0",
    "svelte-check": "^2.2.7",
    "svelte-preprocess": "^4.9.8",
    "tslib": "^2.3.1",
    "typescript": "^4.5.4",
    "vite": "^2.9.7"
  }

### react-table version

3.44.0 (svelte per package.json)

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by marr** [comment]
You can use yarn to install. I'm not sure what the status of the examples is locally, however. A quick check shows that there is an issue on the vue/basic example.

**Comment by KevinVandy** [comment]
The sandboxes seem to be working fine in the sandboxes on the docs site. Probably going to close this.

**Comment by KevinVandy** [comment]
was probably fixed in this commit https://github.com/TanStack/table/commit/7ac63f94070a4d31b2aac610626ebf073ac8d64e
