### ISSUE TITLE
getIsAllRowsExpanded

### ISSUE THREAD

**Issue by sjbuysse** [TanStack/table#4216]
### Describe the bug

This does not work, and it looks incorrect in the source code
```
        // If any row is not expanded, return false
        if (table.getRowModel().flatRows.some(row => row.getIsExpanded())) {
          return false
        }
```

I'm guessing there should be a `!` in front of that `row.getIsExpanded()` ?
I've never contributed to an OS project, and unfortunately a bit short on time to figure it out at the moment

### Your minimal, reproducible example

x

### Steps to reproduce

x

### Expected behavior

x

### Screenshots or Videos

x

### Platform

x

### react-table version

latest

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by simplecommerce** [comment]
I am adding a comment here because I think this issue is still not fixed.

If look at the code here: https://github.com/TanStack/table/blob/main/packages/table-core/src/features/Expanding.ts#L131

I am having the issue on my project, and it seems to be related to this.

Was it supposed to be already fixed? I am using latest version 8.5.11

**Comment by simplecommerce** [comment]
> getIsExpanded

I forgot about this one, I think I did something similar on my end to bypass it and I used `getRowCanExpand` to check if my row has sub rows like you mentioned.

**Comment by pixelbucket-dev** [comment]
Thanks for confirming this.

I've improved the readability of the above:

```ts
return table.getRowModel().flatRows.some((row) => {
    const isRowExpandable = !!row.subRows?.length

    if (!isRowExpandable) {
      return false
    }

    const isRowCollapsed = !row.getIsExpanded()

    return isRowCollapsed
})
```

I also have a problem with `toggleAllRowsExpanded()` once all expandable rows are expanded. On the initial click, the rows stay expanded. I have to click a second time to make them collapsed. I hacked around this with this code: 

```ts
function onToggleAllRowsExpanded() {
  if (isAllRowsExpanded.value) {
    table.resetExpanded()
    return
  }

  table.toggleAllRowsExpanded()
}
```

This is probably an unrelated bug, but worth mentioning. If it's confirmed I can create an issue for it.

**Comment by simplecommerce** [comment]
> Thanks for confirming this.
> 
> I've improved the readability of the above:
> 
> ```ts
> return table.getRowModel().flatRows.some((row) => {
>     const isRowExpandable = !!row.subRows?.length
> 
>     if (!isRowExpandable) {
>       return false
>     }
> 
>     const isRowCollapsed = !row.getIsExpanded()
> 
>     return isRowCollapsed
> })
> ```
> 
> I also have a problem with `toggleAllRowsExpanded()` once all expandable rows are expanded. On the initial click, the rows stay expanded. I have to click a second time to make them collapsed. I hacked around this with this code:
> 
> ```ts
> function onToggleAllRowsExpanded() {
>   const isAllExpandableRowsExpanded = !areSomeExpandableRowsCollapsed
> 
>   if (isAllExpandableRowsExpanded) {
>     table.resetExpanded()
>     return
>   }
> 
>   table.toggleAllRowsExpanded()
> }
> ```
> 
> This is probably an unrelated bug, but worth mentioning. If it's confirmed I can create an issue for it.

haven't had the issue, I use `getToggleAllRowsExpandedHandler` and it seems ok on my end
