### ISSUE TITLE
Getting type instantiation error

### ISSUE THREAD

**Issue by Slate245** [TanStack/table#4224]
### Describe the bug

Hi, I'm still getting used to the library and most likely am doing something wrong. 

Still, I want to use internationalized strings as headers in some of my columns. The compiler throws TS2589 error: Type instantiation is excessively deep and possibly infinite, pointing to a place where i call my translation function, which return simple string, not a deep literal type.

Curiously, when I replace the call with a simple string, the error moves to accessor function for this column.

ColumnDef for this column looks something like this:
```tsx
columnHelper.accessor((transaction) => DateTime.fromJSDate(transaction?.created_at).toUTC(), {
	cell: (props) => (
		<Text title={props.getValue().toRelativeCalendar() ?? ""}>
			{props.getValue().toLocaleString(DateTime.DATETIME_SHORT_WITH_SECONDS)}
		</Text>
	),
	id: "created_at",
	header: t("sections.main.transactions.items.created_at"),
}),
```

I'm sorry I can't provide reproducible example, because I feel the problem is really project-dependant. I'm creating this issue asking mostly for answers on how to tame inferrance in tanstack-table, so I can avoid similar problems

### Your minimal, reproducible example

no link

### Steps to reproduce

1. Define columns in a memo, providing a call to t function from react-18next as a header of a column.
2. Try to compile the app

### Expected behavior

I expect the app to compile correctly

### How often does this bug happen?

Sometimes

### Platform

Linux

### react-table version

v8.3.3

### TypeScript version

v4.4.2

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Please post the errors you are seeing

**Comment by spfoos** [comment]
I'm facing this as well (I think):

TS2589: Type instantiation is excessively deep and possibly infinite.

It's on `columnHelper.accessor`

**Comment by tannerlinsley** [comment]
I’ll need something reproducible to debug :/

**Comment by Slate245** [comment]
It may happen due to some project-specific stuff. Because I tried adding `{incremental: false}` to tsconfig and the error went away. Even after I reverted tsconfig back to it's original state 😕.

**Comment by dcworldwide** [comment]
This has occurred for us, since 8.2.6.

**Comment by tannerlinsley** [comment]
We just shipped new column helper types and better underlying column def types. Please give them a try and report?

**Comment by Himself65** [comment]
My project might face the same error. When I upgrade from `8.2.6` to `8.5.5`. The typescript compiler got into the infinite compilation.

**Comment by Himself65** [comment]
I think the error comes from in [v8.3.0](https://github.com/TanStack/table/releases/tag/v8.3.0)

**Comment by vemoo** [comment]
Minimal repro: https://codesandbox.io/s/react-table-repro-s2b796?file=/src/index.ts

It indeed started happening on 8.3.0

**Comment by Himself65** [comment]
I think the `DeepKey` is the reason

https://github.com/TanStack/table/pull/4185/files#diff-ecfb42689379fb8b0ebe6328e01b25aba4a31d2d076b723ff9fcaf502ac9d0f7R49

**Comment by Himself65** [comment]
This error occurs again in `v8.5.8`

**Comment by Himself65** [comment]
Example
```ts
import { ColumnDef, createColumnHelper } from '@tanstack/react-table'

type Room = {
  id: string
  activated_at: Date
  expires_at: Date
  userId: string
  join_code: string
  room: Room
}

const columnHelper = createColumnHelper<Room>()

const defaultColumns: ColumnDef<Room, any>[] = [
  columnHelper.accessor('id', {
    header: 'ID',
    cell: info => info.getValue()
  })
]
```

```bash
TS2589: Type instantiation is excessively deep and possibly infinite.
```

**Comment by Apfii** [comment]
@tannerlinsley I get this error, Im on `v8.5.11`

**Comment by Himself65** [comment]
> I also get this error on `v8.5.11`.
> 
> 
> 
> I've tried using my own interface and the same interface in @Himself65 example above.

I think if you apply this patch, the issue will be fixed 

https://github.com/TanStack/table/pull/4262

**Comment by Nirajn2311** [comment]
I'm still facing this issue in `react-table:8.7.4`

**Comment by rotciw** [comment]
Also facing the same issue in `react-table:8.7.4`

**Comment by its-monotype** [comment]
Me too, facing the same issue in `react-table:8.7.4`

**Comment by mjlikre** [comment]
Facing this issue in react-table:8.7.6, wonder if they're going to fix it ...

**Comment by jrozbicki** [comment]
I was surprised to see it happen in one of the projects only, but now I think it might be connected to typescript version: I had 4.1.6 fixed in project, bump to latest and error went away.

const columns = [ch.accessor("currency", {})];
                                        ^ When I checked (hovered over) this, with 4.1.6 I saw
                                        
```
accessor: <"currency", never>(accessor: "currency", column: IdentifiedColumnDef<TransportLineItem, never>) => ColumnDef<TransportLineItem, never>
```

and now with 4.9.5

```
(property) accessor: <"currency", string>(accessor: "currency", column: IdentifiedColumnDef<TransportLineItem, string>) => ColumnDef<TransportLineItem, string>
```

**Comment by its-monotype** [comment]
```tsx
import { createColumnHelper } from '@tanstack/react-table';

interface Dog {
  name: string;
  owner: Owner;
}

interface Owner {
  name: string;
  dog: Dog;
}

const columnHelper = createColumnHelper<Dog>();

const columns = [
  columnHelper.accessor('name', { // ts(2589): Type instantiation is excessively deep and possibly infinite.
    header: 'Name',
  }
]
```

https://codesandbox.io/s/tanstack-table-issues-4224-u92zmn?file=/src/App.tsx

Is it possible to fix it?

**Comment by aoneahsan** [comment]
do we have a solution for this error???
![image](https://user-images.githubusercontent.com/37369204/222134861-e2d21ba4-73ea-413c-aa02-d9e516a647cd.png)
![image](https://user-images.githubusercontent.com/37369204/222134906-86071925-9437-4b3f-ac0d-1a660bfc8bb8.png)
using     "@tanstack/react-table": "^8.7.9",

**Comment by AllenKunn16** [comment]
I have an issue where if I put a type like FileList, it will cause the the ts(2589) issue

With FileList
![image](https://user-images.githubusercontent.com/46128658/223364261-915a7135-a9ad-4970-bb5b-15decbc0020e.png)
![image](https://user-images.githubusercontent.com/46128658/223364423-dac6636d-f5bf-44dd-9287-2afcc61d5cb7.png)

string only

![image](https://user-images.githubusercontent.com/46128658/223364530-ecb2493b-b99d-4b94-b574-4c77b1ad5979.png)
![image](https://user-images.githubusercontent.com/46128658/223364592-33b81318-9940-4930-b238-4c3b97df49b9.png)

**Comment by its-monotype** [comment]
Any updates?

**Comment by OkancanCosar** [comment]
any updates?

**Comment by uncvrd** [comment]
Just wanted to report I sorta naively thought I could add a complex object in to the column helper and it straight up breaks TS across my entire project when I do so.

For example, I had a table I wanted to display Stripe Charges on. So I tried to do `const helper = createColumnHelper<Stripe.Charge>()`. And this causes VS Code to infinitely display the `loading...` prompt when hovering over an element on any file afterwards!

For now I am just creating temporary DTOs with the props that I actually need

**Comment by connorlindsey** [comment]
Also seeing this on `8.8.5` with the following (abbreviated) example. If I change ObjectId to be string, the ts error goes away so something to do with larger nested types maybe. 

```
interface Patient {
    _id: ObjectId // from Mongoose
    ... other properties
}

const columnHelper = createColumnHelper<Patient>()
const columns = [
  columnHelper.accessor("name", {
    header: "Patient Info",
    cell: (info) => <span className="font-semibold text-gray-900">{info.getValue()}</span>,
  }),
]
```

**Comment by benzara-tahar** [comment]
Having the same issue with `8.9.1`
![image](https://github.com/TanStack/table/assets/71077112/3427e7f3-c4d2-495d-bce7-f4f2ea85d462)

**Comment by VinixGonzalez** [comment]
any updates ?

I'm using the official example and getting this error just by adding a new prop 'actions' to the type which is a React.ReactNode,

![image](https://github.com/TanStack/table/assets/47197477/c2fc32b9-733b-4836-82ca-579edb1e3572)

![image](https://github.com/TanStack/table/assets/47197477/aa6e313d-4578-4ecf-90d2-b525693f9d33)

![image](https://github.com/TanStack/table/assets/47197477/e40ddadf-382e-406f-bc82-ed946b28b412)

**Comment by its-monotype** [comment]
@tannerlinsley @KevinVandy Please help

**Comment by yarinsa** [comment]
Please help :)

**Comment by its-monotype** [comment]
GG
