### ISSUE TITLE
How to properly use memo to optimize rerender in v8

### ISSUE THREAD

**Issue by collides** [TanStack/table#4227]
### Describe the bug

Hi, I'm using the library to build a table component,  When a column is updated, all the components are rerendered, 
I found this [problem](https://github.com/TanStack/table/issues/4092) and [used Memo to optimize it](https://github.com/TanStack/table/issues/4092#issuecomment-1179088175), Now the component does not render 😲, 
How to properly use Memo to optimize rendering problems, This optimization is important to me because there can be a performance bottleneck when the components in a cell are complex

### Your minimal, reproducible example

https://codesandbox.io/s/inspiring-sun-i39nwf?file=/src/App.tsx

### Steps to reproduce

Click toggle select button

### Expected behavior

Click toggle select button, unselected should become selected

### Platform

Chrome

### react-table version

8.3.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
- When columns change, their data models could have also potentially changed. Changing column stability/reference will trigger the table to rerender and this is good thing, otherwise your table would never update when columns change.
- useReactTable is a hook that tracks state for the entire table. When that state updates, the entire table must update. This doesn't mean that everything will be repainted, but it will be rerendered. Optimize your table to be rerendered often.
- Columns must remain stable they are changing. Use `useMemo` to stabilize them between rerenders or move them out of the render function:

```tsx
const columns = React.useMemo(
    () => [
      {
        accessorKey: "id",
        cell: (info) => {
          const id = info.getValue();
          const selected = selectedIds[id];

          return (
            <div>
              {selected ? "selected" : "unselected"}
              <button
                onClick={() => {
                  setSelectedIds((prevSelectedIds) => {
                    return {
                      ...prevSelectedIds,
                      [id]: !prevSelectedIds[id]
                    };
                  });
                }}
              >
                toggle select
              </button>
            </div>
          );
        }
      },
...
```

**Comment by schickling** [comment]
Thanks a lot for elaborating @tannerlinsley.

So to be clear: v8 no longer allows for row components to be memoized?

> Optimize your table to be rerendered often.

I have a very dense and large table with cells which are basically simple text spans leaving little room for further optimization to my knowledge.

**Comment by jremen** [comment]
Same problem here, I'm getting image URLs from API which I render as an image thumbnails in table, but on any data change (ie row selection, updating value, sending updated value back to API), whole table rerenders which causes images to „blink“ multiple times.
I tried to memoize images itself as a separate component but because whole table rerenders, cell.getValue() rerenders itself too.

**Comment by shnigi** [comment]
> Same problem here, I'm getting image URLs from API which I render as an image thumbnails in table, but on any data change (ie row selection, updating value, sending updated value back to API), whole table rerenders which causes images to „blink“ multiple times. I tried to memoize images itself as a separate component but because whole table rerenders, cell.getValue() rerenders itself too.

I have this exact same problem. I get images from API and filtering table or selecting items causes images to blink. Looking for a solution to memoize images and prevent refetching them.

**Comment by milesingrams** [comment]
I'm dealing with an issue where I have action button column/cell that has a dropdown menu. The dropdown is autoclosed every time the table rerenders even if the data remains the same. Not sure how to resolve without memoization of some sort?

**Comment by aganglada** [comment]
@tannerlinsley is there any example of tables with images where I can asses if this re-rendering image blink is real?

**Comment by nikosrossolatos** [comment]
> Same problem here, I'm getting image URLs from API which I render as an image thumbnails in table, but on any data change (ie row selection, updating value, sending updated value back to API), whole table rerenders which causes images to „blink“ multiple times. I tried to memoize images itself as a separate component but because whole table rerenders, cell.getValue() rerenders itself too.

I am having the same issue. My images are blinking when I select a row. One thought I had was to handle selection state outside the table which feels like it defeats the purpose. Did you manage to solve this?

**Comment by jremen** [comment]
Yep, managed. I resigned whole built in select functionality. Now to properly handle this, you have to create SEPARATE table cell just for checkbox only (as any state change to common cell definition rerenders every single cell – even if you change state on only one of them).
And used zustand with separate state store just for selection. I'll pass the cell object passed from columns definition and with that I can do whatever I want. If I use select all checkbox, just column with select table cells is rerendered.

![image](https://github.com/TanStack/table/assets/7055428/991fcdfe-61f0-486e-8335-a5ebf164b01c)

![image](https://github.com/TanStack/table/assets/7055428/c06d188d-025e-4c20-a574-1335b9c82d0b)

And in table definition:
![image](https://github.com/TanStack/table/assets/7055428/30fc21e7-eb6f-4eec-af2b-ed74f2c63d32)

**Comment by sudarshan-mane** [comment]
> I'm dealing with an issue where I have action button column/cell that has a dropdown menu. The dropdown is auto closed every time the table rerenders even if the data remains the same. Not sure how to resolve without memorization of some sort?

@milesingrams  we are having same issue, using Combobox, whenever we type any letter in Combobox search, on every letter type dropdown gets closed, as table retendering, have you found any solution?

**Comment by adrienharnay** [comment]
Hello @tannerlinsley, I believe this issue should be re-opened considering the few use cases mentioned since it was closed. To my knowledge, the issue persists as of this day.
