### ISSUE TITLE
TS error with ColumnDef<T> = ColumnDef<T extends T>

### ISSUE THREAD

**Issue by rusakovStas** [TanStack/table#4242]
### Describe the bug

Hi there! I have an issue with only TS check (everything works fine). 
I want to create my component based on yours react-table. I created that component and described types to use from outside - user have to extend my type and work with them. But TS cursing on ColumnDef parameter. 
I reproduced example of that issue, but unfortunately it can't be seen from web example, but i believe you'll see it if you copy that code on your local machine.  
it's very likely that it's not a bug, but just my misunderstanding( I'll be happy if you explain me how to do such thing, one way or another. 
Just in case my error message: 
`ERROR in src/App.tsx:230:9
TS2322: Type 'ColumnDef<MyPerson, any>[]' is not assignable to type 'ColumnDef<MyTableRow<PersonData>, unknown>[]'.
  Type 'ColumnDef<MyPerson, any>' is not assignable to type 'ColumnDef<MyTableRow<PersonData>, unknown>'.
    Type 'CoreColumnDefBase<MyPerson, any> & { id: string; } & VisibilityColumnDef & ColumnPinningColumnDef & FiltersColumnDef<...> & SortingColumnDef<...> & GroupingColumnDef<...> & ColumnSizingColumnDef' is not assignable to type 'ColumnDef<MyTableRow<PersonData>, unknown>'.
      Type 'CoreColumnDefBase<MyPerson, any> & { id: string; } & VisibilityColumnDef & ColumnPinningColumnDef & FiltersColumnDef<...> & SortingColumnDef<...> & GroupingColumnDef<...> & ColumnSizingColumnDef' is not assignable to type 'CoreColumnDefBase<MyTableRow<PersonData>, unknown> & { accessorKey: "accessFn" | "id" | "index" | "original" | "depth" | "_valuesCache" | ... 38 more ... | `_groupingValuesCache.${string}`; id?: string | undefined; } & ... 5 more ... & ColumnSizingColumnDef'.
        Type 'CoreColumnDefBase<MyPerson, any> & { id: string; } & VisibilityColumnDef & ColumnPinningColumnDef & FiltersColumnDef<...> & SortingColumnDef<...> & GroupingColumnDef<...> & ColumnSizingColumnDef' is not assignable to type 'CoreColumnDefBase<MyTableRow<PersonData>, unknown>'.
          Types of property 'columns' are incompatible.
            Type 'ColumnDef<MyPerson, unknown>[] | undefined' is not assignable to type 'ColumnDef<MyTableRow<PersonData>, unknown>[] | undefined'.
              Type 'ColumnDef<MyPerson, unknown>[]' is not assignable to type 'ColumnDef<MyTableRow<PersonData>, unknown>[]'.
                Type 'ColumnDef<MyPerson, unknown>' is not assignable to type 'ColumnDef<MyTableRow<PersonData>, unknown>'.
                  Type 'CoreColumnDefBase<MyPerson, unknown> & { accessorKey: Month | "type" | "accessFn" | "id" | "index" | "original" | "depth" | "_valuesCache" | "getValue" | ... 38 more ... | `_groupingValuesCache.${string}`; id?: string | undefined; } & ... 5 more ... & ColumnSizingColumnDef' is not assignable to type 'ColumnDef<MyTableRow<PersonData>, unknown>'.
                    Type 'CoreColumnDefBase<MyPerson, unknown> & { accessorKey: Month | "type" | "accessFn" | "id" | "index" | "original" | "depth" | "_valuesCache" | "getValue" | ... 38 more ... | `_groupingValuesCache.${string}`; id?: string | undefined; } & ... 5 more ... & ColumnSizingColumnDef' is not assignable to type 'CoreColumnDefBase<MyTableRow<PersonData>, unknown> & { accessorKey: "accessFn" | "id" | "index" | "original" | "depth" | "_valuesCache" | ... 38 more ... | `_groupingValuesCache.${string}`; id?: string | undefined; } & ... 5 more ... & ColumnSizingColumnDef'.
                      Type 'CoreColumnDefBase<MyPerson, unknown> & { accessorKey: Month | "type" | "accessFn" | "id" | "index" | "original" | "depth" | "_valuesCache" | "getValue" | ... 38 more ... | `_groupingValuesCache.${string}`; id?: string | undefined; } & ... 5 more ... & ColumnSizingColumnDef' is not assignable to type '{ accessorKey: "accessFn" | "id" | "index" | "original" | "depth" | "_valuesCache" | "getValue" | "renderValue" | "subRows" | "getLeafRows" | "originalSubRows" | "getAllCells" | ... 32 more ... | `_groupingValuesCache.${string}`; id?: string | undefined; }'.
                        Types of property 'accessorKey' are incompatible.
                          Type 'Month | "type" | "accessFn" | "id" | "index" | "original" | "depth" | "_valuesCache" | "getValue" | "renderValue" | "subRows" | "getLeafRows" | "originalSubRows" | "getAllCells" | ... 33 more ... | `_groupingValuesCache.${string}`' is not assignable to type '"accessFn" | "id" | "index" | "original" | "depth" | "_valuesCache" | "getValue" | "renderValue" | "subRows" | "getLeafRows" | "originalSubRows" | "getAllCells" | "_getAllCellsByColumnId" | ... 31 more ... | `_groupingValuesCache.${string}`'.
                            Type 'Month.Jan' is not assignable to type '"accessFn" | "id" | "index" | "original" | "depth" | "_valuesCache" | "getValue" | "renderValue" | "subRows" | "getLeafRows" | "originalSubRows" | "getAllCells" | "_getAllCellsByColumnId" | ... 31 more ... | `_groupingValuesCache.${string}`'.`

### Your minimal, reproducible example

https://stackblitz.com/edit/react-ts-qw7gt4?file=App.tsx

### Steps to reproduce

just open the same project as above. 

### Expected behavior

As a user i expected to see no errors but i'm seeing error message that described above 

### How often does this bug happen?

Every time

### Screenshots or Videos

![2022-07-31_00-16-36](https://user-images.githubusercontent.com/21197242/181996444-e6e30c57-b6e9-4518-a4da-5c7c8ba13de6.png)

### Platform

my package.json (created via last create-react-app with ts template): 
"@tanstack/react-table": "^8.5.2",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^13.0.0",
    "@testing-library/user-event": "^13.2.1",
    "@types/jest": "^27.0.1",
    "@types/node": "^16.7.13",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.4.2",
    "web-vitals": "^2.1.0"

### react-table version

v8.5.2

### TypeScript version

4.4.2

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
First, try upgrading to the latest version. If that doesn't help, then it looks like it's exactly what the error is saying. You can't assign `ColumnDef<_, any>` to `ColumnDef<_, unknown>`. Somewhere you have created a type of `ColumnDef<_, unknown>` either intentionally or not and are trying to pass columns with the type `ColumnDef<_, any>` to it. I would double check all of your own uses of `ColumnDef` and make sure you are creating the right types. You likely need to change a `ColumnDef<_, unknown>` or `ColumnDef<_>` to `ColumnDef<_, any>`
