### ISSUE TITLE
Styles don't exist in many of the index.css files for the examples

### ISSUE THREAD

**Issue by MA-MacDonald** [TanStack/table#4252]
### Describe the bug

Many of the React examples don't contain the used styles in the index.css file.

For example the full width resizable table example 

none of these styles exist in the index.css file so the example aren't displaying correctly.
  
![image](https://user-images.githubusercontent.com/7886459/182265894-94273553-fb0d-44c1-b479-29d284507434.png)
 

### Your minimal, reproducible example

https://github.com/TanStack/table/blob/main/examples/react/full-width-table/src/index.css

### Steps to reproduce

Open the  React full width resizable table or the full width example. Check the index.css file.

### Expected behavior

The table should be full width in the full width examples

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/7886459/182266332-c0aabe89-555a-4f01-81ab-17f3f414a3ab.png)

### Platform

Windows 10, Chrome Version 103.0.5060.134 (Official Build) (64-bit)

### react-table version

8.5.2

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by ytnytn1** [comment]
Hi, @MA-MacDonald! 

Did you manage to make this example correct ? I faced the similar problem and I'm looking for a solution. 

Thanks in advance!

**Comment by MA-MacDonald** [comment]
@ytnytn1 Yeah if you look in the index.html it looks like they are pulling in tailwindcss which is where those "missing" classes are coming from.
