### ISSUE TITLE
 [v8] expansion sub rows hides because of pagination page limit

### ISSUE THREAD

**Issue by dhanushkumarsivaji** [TanStack/table#4260]
### Describe the bug

Hello,

I have created the table which supports row expansion. This table also has pagination with a page limit of 10 (default).

While you expand the last row ( I mean the 10th row ). The sub rows under the expansion hides because the page limit of the table is set to 10. The expansion makes the row count 10 + 2 ( it is the sub rows under expansion ).

During this scenario, the table should make the sub rows to visible despite the pagination limit.

And I don't know, How to solve this error. @tannerlinsley Please help me to resolve this one. 

A working demo of the table is available at this link - [Paginated Expansion Table](https://codesandbox.io/s/tanstack-table-filter-pagination-issue-k7sm34?file=/src/main.tsx)

**I have attached the video of the bug !!**

https://user-images.githubusercontent.com/36889650/182730878-f9fb90c3-b33b-411c-89c8-dbd127f011d4.mov

### Your minimal, reproducible example

https://codesandbox.io/s/tanstack-table-filter-pagination-issue-k7sm34?file=/src/main.tsx

### Steps to reproduce

1. Go to the sandbox provided link - You can see the working demo of the table
2. Try to expand the last row of the table.
3. You can't see the sub rows under it.

### Expected behavior

During this scenario, the table should make the sub rows to visible despite the pagination limit.

### How often does this bug happen?

Every time

### Platform

macOS

### react-table version

v8.5.5

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by dhanushkumarsivaji** [comment]
https://user-images.githubusercontent.com/36889650/182614729-ecb017da-bd96-4ea1-9b65-690b99ff34aa.mov

**Comment by R-Mahe** [comment]
+1 

I am also facing this similar problem :(  Please let us know the fix for this

**Comment by tannerlinsley** [comment]
Set this option to false https://tanstack.com/table/v8/docs/api/features/expanding#paginateexpandedrows

Tanner Linsley

**Comment by dhanushkumarsivaji** [comment]
When I set this  ``` paginateExpandedRows: false,``` none of the rows are expanding. Please check in this link - https://codesandbox.io/s/tanstack-table-expansion-pagination-9nuzit?file=/src/App.js

**Comment by Its-Just-Nans** [comment]
Related to #4223 ?

@tannerlinsley

**Comment by dhanushkumarsivaji** [comment]
As @tannerlinsley mentioned in this [ticket](https://github.com/TanStack/table/issues/4223). This issue is resolved now. Hence closing this
