### ISSUE TITLE
[v8.5.10] "type too deep" appears in ColumnDef  (without using the column helper)

### ISSUE THREAD

**Issue by Obiwarn** [TanStack/table#4272]
### Describe the bug

After I updated to v8.5.10:
`TS2589: Type instantiation is excessively deep and possibly infinite.`
appears (without using the column helper).

Noted that `ProjectStoreTableData` is really deep.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/9539797/183050556-663d4147-7d85-4c02-9bec-8c2b48fd1153.png">

### Your minimal, reproducible example

x

### Steps to reproduce

x

### Expected behavior

x

### Platform

x

### react-table version

v8.5.10

### TypeScript version

x

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Just removed the deep key functionality in the generic ColumnDef type. See if it helps.

**Comment by tannerlinsley** [comment]
Seems to have fixed #4241
