### ISSUE TITLE
When accessor key contains a dot, `getValue()` fails.

### ISSUE THREAD

**Issue by baptisteArno** [TanStack/table#4296]
### Describe the bug

When accessor key contains a dot (i.e. `Value.test`), the `getValue()` call throws: `TypeError: Cannot read properties of undefined (reading 'test')`

```
cell: (info) => {
            const value = info.getValue() as CellValueType | undefined
            if (!value) return
            return value.element || value.plainText || ''
          }
```

### Your minimal, reproducible example

https://codesandbox.io/s/vigilant-tereshkova-cposhb?file=/src/main.tsx

### Steps to reproduce

1. See error

### Expected behavior

Should not throw error

### Platform

- MacOS
- Chrome

### react-table version

8.5.11

### TypeScript version

4.7.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This is expected behavior, as TanStack Table supports dot notation to access nested data.

For example something like this:

```ts
type Person = {
  username: string;
  name: {
    firstName: string;
    lastName: string;
  }
}

//
  {
    accessorKey: 'username', //normal recommended usage of an accessorKey
    header: 'Username',
  },
  {
    accessorKey: 'name.firstName', //example of dot notation used to access nested data
    header: 'First Name',
  },
  {
    accessorKey: 'name.lastName', //example of dot notation used to access nested data
    header: 'Last Name',
  },
```

So please only use dots if you are accessing nested data in your data objects.

**Comment by platypii** [comment]
Any suggestions on how to handle loading a CSV which might have arbitrary column names?

**Comment by KevinVandy** [comment]
> Any suggestions on how to handle loading a CSV which might have arbitrary column names?

An accessorKey can have the dots, but pass in an id that doesn't

**Comment by galangel** [comment]
To contribute my perspective here:
I am working with opensearch response to render documents. I flatten the `Source` for ease of use.
To have `cell.getValue()` work for me I had to replace:
```typescript
accessorKey: `_source.${fieldName}`,
```
with
```typescript
accessorFn: row => row._source[fieldName],
```
