### ISSUE TITLE
Resizing of the columns is not working as expected

### ISSUE THREAD

**Issue by melaniemeindldynatrace** [TanStack/table#4297]
### Describe the bug

When combining flexbox with resizing, like in the [Full Width Resizable Table](https://tanstack.com/table/v8/docs/examples/react/full-width-resizable-table) example the resizing does not work as expected. When trying to resize, the column resizer is not where the mouse actually moves. This is even more visible on bigger screens and only occurs when using the flex/fullwidth table, with normal column sizes resizing works fine. 

### Your minimal, reproducible example

https://codesandbox.io/s/gracious-shaw-k2nnje?file=/src/main.tsx:127-131

### Steps to reproduce

1. Resize one of the resizable columns. (e.g. the one underneath "Name")
2. As your mouse is moving, notice how the border where you grabbed to resize is not where the mouse is. The offset increases the more you try to resize.

### Expected behavior

I expected the border to move exactly corresponding to the position of the mouse. The expected behaviour can be seen in [this example](https://tanstack.com/table/v8/docs/examples/react/column-sizing).

### How often does this bug happen?

Every time

### Platform

- OS: [Windows]
- Browser: [Chrome, Firefox, Edge]

### react-table version

v7.7.0, v8.5.11

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
The resizing logic is not flex based, so indeed this will “flex” the pixel based measurements. I don’t believe there is anything that can be done here.

**Comment by elilondon** [comment]
Trying to find the difference between the two - full width resize and the "right" example. I'd like mine to work the same as the example as well but not sure what to change to make that happen.

**Comment by talatkuyuk** [comment]
@melaniemeindldynatrace I advice you to have a look my comment in discussions below. You may inspire what to do in order to keep the column sizes in the state.

https://github.com/TanStack/table/discussions/3947#discussioncomment-2845135

**Comment by YaTomilkina** [comment]
face the same issue
