### ISSUE TITLE
[v8] Type Error in ColumnDef

### ISSUE THREAD

**Issue by celsodias12** [TanStack/table#4302]
### Describe the bug

`ColumnDef` typing is not working correctly, when a type is passed as a parameter it doesn't show me the correct typing

### Your minimal, reproducible example

https://codesandbox.io/s/react-typescript-forked-gr4xw1?file=/src/App.tsx

### Steps to reproduce

when you fill in the `accessorKey` you will see that its typing is string, and it should be `keyof Person`

### Expected behavior

should return the typing as: `accessorKey: firstName | lastName | age | visits | status | progress` and any other value that is entered should be returned typing error

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/47264001/184558845-8e7ccdb5-7c73-4b19-9e8d-106b13e9bce8.png)

### Platform

- OS: windows
- Browser: any browser

### react-table version

v8.5.11

### TypeScript version

v4.6.3

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Please use the createColumnHelper<Person>().accessor(options) API

Tanner Linsley

**Comment by iblecher** [comment]
That did work for me - columnHelper returns a type for a specific field of the column and not the entire column type.
Example:
```
type Person = {
  name: string;
  age: number;
};

const columnHelper = createColumnHelper<Person>();


// Type of nameColumn = ColumnDef<Person, string>;
const nameColumn = columnHelper('name', {
  header: `Name`,
  cell: info => info.getValue(),
});

// Type of ageColumn = ColumnDef<Person, number>;
const ageColumn = columnHelper('age', {
  header: `Age`,
  cell: info => info.getValue(),
});

// This will not work:
const columns: ColumnDef<Person> = [nameColumn, ageColumn];

**Comment by utkuturunc** [comment]
i'm working around this by using

```typescript
const columns: ColumnDef<Person, any>[] = [nameColumn, ageColumn];
```

**Comment by iblecher** [comment]
thanks @utkuturunc but we use `@typescript-eslint/no-explicit-any` rule which doesn't allow me to use `any`

**Comment by utkuturunc** [comment]
@iblecher in that case

```typescript
const nameColumn = columnHelper('name', {
  header: `Name`,
  cell: info => info.getValue(),
}) as ColumnDef<Person, unknown>;
```

should work

**Comment by huv1k** [comment]
I think `accessorKey` should show only possible keys from `ColumnDef` generic. What is point of defining it anyways, when basic type propagation doesn't work as expected? Is there any blocker to fix this behavior instead of using these helper functions? 🤔

**Comment by tannerlinsley** [comment]
Yes. Typescript limitations. We’ll be able to get around these with time.

**Comment by Jontii** [comment]
We have a similar problem in our code.


`  
const columns = useMemo<ColumnDef<Shipment>[]>(
    () => [
      columnHelper.accessor("name", {
        cell: (info) => info.getValue(),
        header: "Name",
      }),
      columnHelper.accessor("totalUnits", {
        cell: (info) => info.getValue(),
        header: "Total Units",
      }),
    ],
    [],
  )
  `
Give me this typescript error
<img width="925" alt="bild" src="https://user-images.githubusercontent.com/19165426/190342318-6d5dc637-b042-468d-aabb-278ec4ee5f25.png">

**Comment by RobinLbt** [comment]
> i'm working around this by using
> 
> ```ts
> const columns: ColumnDef<Person, any>[] = [nameColumn, ageColumn];
> ```

@utkuturunc this seems like the only viable option for now, but I still didn't manage to make it work unfortunately

For instance this

```ts
const columnHelper = createColumnHelper<Person>();

const firstNameColumn = columnHelper.accessor("firstName",{
   header: "firstName",
   cell: info => info.getValue(),
});

```

Will give the following error on "firstName":

`Argument of type 'string' is not assignable to parameter of type 'AccessorFn<Person>`

**Comment by ekozhura** [comment]
For me the main goal is to not lose the type information about cell values. To achieve this goal I found two workarounds:
1. is to provide as much type information as possible.
2. is to allow the type checker to infer types.
In both cases types of cell values are preserved.

First workaround:
```
type Person = {
  name: string;
  age: number;
};

const columnHelper = createColumnHelper<Person>();

const columns: ColumnDef<Person>[] = [
  columnHelper.accessor<"name", string>("name", { 
    cell: props => props.getValue() // getValue() will return value of type string
  }),
  columnHelper.accessor<"age", number>("age", { 
    cell: props => props.getValue() // getValue() will return value of type number
  }),
] as ColumnDef<Person>[]; // this typecast solely to avoid `any` as a value for `TValue` parameter
```

Second workaround:
```
type Person = {
  name: string;
  age: number;
};

const columnHelper = createColumnHelper<Person>();

const columns = [
  columnHelper.accessor("name", { 
    cell: props => props.getValue() // getValue() will return value of type string
  }),
  columnHelper.accessor("age", { 
    cell: props => props.getValue() // getValue() will return value of type number
  }),
];
```
Probably at some point you will have to type cast `columns` to `ColumnDef<Person>[]`, but for me this isn't an issue.

**Comment by KevinVandy** [comment]
This should be fixed in the latest v8.5.30 release https://github.com/TanStack/table/pull/4513

**Comment by mnlfischer** [comment]
It is not working for me when I use string literal types in my interface that I pass to the helper function:
`createColumnHelper<Example>()`

type AnotherValueType: "Test" | "Test2"

```
export interface Example {
    id: string;
    anotherValue: AnotherValueType
}
```

Type 'ColumnDefBase<Example, AnotherValueType> & StringHeaderIdentifier' is not assignable to type 'ColumnDef<Example, string>'.
      Type 'ColumnDefBase<Example, AnotherValueType> & StringHeaderIdentifier' is not assignable to type 'AccessorFnColumnDefBase<Example, string> & IdIdentifier<Example, string>'.

**Comment by TheOftedal** [comment]
@mnlfischer Did you find a solution for the column typing issues you experience? I am having the exact same issues...

**Comment by mnlfischer** [comment]
> @mnlfischer Did you find a solution for the column typing issues you experience? I am having the exact same issues...

sadly I disabled the ts error for now.

**Comment by TheOftedal** [comment]
> 

Thanks for your response!
I managed to avoid the ts errors by casting the column definition arrays as follows:

```
interface MyAwesomeType {
    name: string;
    value: number;
}

const columnHelper = createColumnHelper<MyAwesomeType>();

const columns = [
      columnHelper.accessor('name', {
        header: 'Name',
        cell: props => props.getValue() 
      }),
      columnHelper.accessor('value', {
        header: 'Value',
        cell: props => props.getValue() 
      }),
] as Array<ColumnDef<AwesomeType, unknown>>;
```

This works well with my generic `Table` component for which I have typed the `columns` and `data` properties as follows:
```
export interface TableProps<T> {
  data: Array<T>;
  columns: Array<ColumnDef<T, unknown>>;
}
```

The `Table` component has the following signature:
```
export const Table = <T extends object>({
  data,
  columns
}: TableProps<T>) => {
    /** 
    * Table render logic
    */
}
```

This is a very basic snapshot of how I have chosen to solve this but this works pretty well and still provides me with the required strongly typed implementation I wanted.

**Comment by S-Furman** [comment]
> @mnlfischer Thanks for your response! I managed to avoid the ts errors by casting the column definition arrays as follows:
> 
> ```
> interface MyAwesomeType {
>     name: string;
>     value: number;
> }
> 
> const columnHelper = createColumnHelper<MyAwesomeType>();
> 
> const columns = [
>       columnHelper.accessor('name', {
>         header: 'Name',
>         cell: props => props.getValue() 
>       }),
>       columnHelper.accessor('value', {
>         header: 'Value',
>         cell: props => props.getValue() 
>       }),
> ] as Array<ColumnDef<MyAwesomeType, unknown>>;
> ```
> 
> This works well with my generic `Table` component for which I have typed the `columns` and `data` properties as follows:
> 
> ```
> export interface TableProps<T> {
>   data: Array<T>;
>   columns: Array<ColumnDef<T, unknown>>;
> }
> ```
> 
> The `Table` component has the following signature:
> 
> ```
> export const Table = <T extends object>({
>   data,
>   columns
> }: TableProps<T>) => {
>     /** 
>     * Table render logic
>     */
> }
> ```
> 
> This is a very basic snapshot of how I have chosen to solve this but this works pretty well and still provides me with the required strongly typed implementation I wanted.

Works well for this case but when I have custom functionFn that returns boolean I get error: TS2322: Type  "isWithinRange"  is not assignable to type  FilterFnOption<Verification> | undefined

**Comment by Moloko20** [comment]
Hi! I'm still getting this error :(

`"@tanstack/react-table": "8.12.0"`, `"typescript": "5.2.2"`

**Comment by Kevi14** [comment]
What fixed the issue for me was to not export the columns from another file but use them directly there , the export keyword seems to be the culprit for me.

**Comment by 9mm** [comment]
is there a benefit to doing:

```
as ColumnDef<Payment, unknown>[
```

over 

```
as ColumnDef<Payment>[
```

**Comment by ilbertt** [comment]
I'm still facing the error:
```
Type 'AccessorKeyColumnDef<MyType, string>' is not assignable to type 'ColumnDef<MyType>'.
  Type 'AccessorKeyColumnDefBase<MyType, string> & Partial<StringHeaderIdentifier>' is not assignable to type 'ColumnDef<MyType>'.
```

The solution proposed by @TheOftedal to cast the `TValue` to `unknown`:
> ```typescript
> as Array<ColumnDef<MyAwesomeType, unknown>>;
> ```

**doesn't fix** the problem, it just _hides_ it by disabling types validation on the array. In fact, if I add a random element (e.g. a completely different object or even a primitive like a string) to the `columns` array, the TypeScript compiler still considers this valid, which is not the behavior we want.

The only solution that I've found so far is to cast the column type to `any` as @utkuturunc proposed:

> ```typescript
> const columns: ColumnDef<Person, any>[] = [nameColumn, ageColumn];
> ```

In particular, I've created a shared type helper that I can use in all the tables of my application:

```typescript
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type GenericColumnDef<T> = ColumnDef<T, any>;
```
so that I have to disable the `no-explicit-any` eslint rule only once.

I hope this helps, but I really hope that this gets fixed or we get better guidance on how to implement types inference properly from the maintainers.

**Comment by pcobbpennyhoarder** [comment]
After spending a while on this I was able to figure it out. Here is my code:

Defined in parent component
```
        columns: [
            { header: 'Title', key: 'title' },
            { header: 'Author', key: 'user.name' },
            { header: 'Publish Date', key: 'publish_date' },
            { header: 'Status', key: 'status' },
        ]
```

Child component. The config is passed down in a prop that contains columns.
```
      const data: Post[] = [];
      
      const columnHelper = createColumnHelper<Post>();
      const columns = config.columns.map(({ header, key }) => {
        return columnHelper.accessor(key as keyof Post, {
          header,
        })
      });
```

Types

```

export type PostListUser = {
    name: string;
}
export type Post = {
    id: number;
    title: string;
    user: PostListUser;
    publish_date: string;
    status: string;
};
```


Hopefully that helps someone out there.

**Comment by akka-httpgoing** [comment]
https://stackdev.space/questions/what-is-the-best-way-to-transfer-a-specified-number-of-cells-from-array-1-to-array-2-while-also-capturing-error-information Check out this answer
