### ISSUE TITLE
[V8] 502 Bad Gateway in React Example: Full Width Resizable Table

### ISSUE THREAD

**Issue by cha2hyun** [TanStack/table#4305]
### Describe the bug

There is an error in Tanstack Table V8 homepages > React Examples > Full Width Resizable Table
![image](https://user-images.githubusercontent.com/56015532/184811610-57a82cae-b6f9-4381-b11d-1dfe05cae65c.png)

### Your minimal, reproducible example

https://tanstack.com/table/v8/docs/examples/react/full-width-resizable-table

### Steps to reproduce

1. React Examples
2. Full Width Resizable Table
3. 502 bad gateway

### Expected behavior

Also same as in Sandbox

### Platform

MacOs Chrome, Chrome Secret Mode

### react-table version

v8

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by elilondon** [comment]
Not sure if this is related to my issue but I cant seem to make resizable columns work for the react version either.

**Comment by StarHosea** [comment]
+ 1

**Comment by KevinVandy** [comment]
was fixed with a valid package.json recently
