### ISSUE TITLE
Fully Controlled: possible sync issues between internal state and users state

### ISSUE THREAD

**Issue by sjbuysse** [TanStack/table#4307]
### Describe the bug

Hi, 

I noticed in the source code that the table is trying to manage 2 states when fully controlled. 
The library will try to update both internal state & the users state, this can (and _will_ create discrepancies between those 2 states). 

I came across a discrepancy when I wanted to keep my state in a Context. 

### Your minimal, reproducible example

https://codesandbox.io/s/throbbing-fog-w9f2qg?file=/src/main.tsx

### Steps to reproduce

1. Expand the first row
2. Click 'refresh data' button
3. Expanded state should be set to `{}` , as defined in the `useEffect`
4. You'll see that the first row is still expanded though

When I debug the react-table library locally, I can see that the internal state kept in `index.tsx` is actually correctly updated, the user state isn't.

PS. If you uncomment the `useState` line, and comment out the `useTableContext` line, everything works correctly. Nonetheless, I don't think there should be possible discrepancies with a fully controlled pattern.

### Expected behavior

The internal & user state are the same.
Even better would be if there was just a single source of truth (the users state)

### How often does this bug happen?

Every time

### Platform

macOs

### react-table version

8.5.11

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Instead of using a useEffect, just move the logic to the event handler to set state from a handler instead of an useEffect. 
<img width="536" alt="image" src="https://github.com/TanStack/table/assets/28243511/2b253afa-9f8c-4e15-9fec-53c9455e255c">

**Comment by sjbuysse** [comment]
In this simple sandbox example that would work, but we have a wrapper hook in our project that wraps around the `useReactTable` hook. This wrapper hook deals with a lot of things involving controlled state & lazy loading of subrows, etc. 

In general, when the data changes (because of some api filters or whatever), we want to close the expanded rows. This won't happen automatically, since it's a fully controlled table. Unless we want every consumer of this hook to add that logic to every event handler that can update the data, this suggestion can not help us
