### ISSUE TITLE
[v8] dot in accessorKey crashes the table

### ISSUE THREAD

**Issue by oeddyo** [TanStack/table#4320]
### Describe the bug

looks like when I try to upgrade from 8.2.3 -> 8.5.11
it crashes my app and I found out through a test case. When accessor key has dot, it crashes in 8.5.11 

Might due to recent change though I'm not 100% sure

```
commit f7be4cfb25eff51a8438346ffbb0be039bc1be2e
Author: Tanner Linsley <tannerlinsley@gmail.com>
Date:   Wed Jul 20 09:29:05 2022 -0600

    feat: column helper utility, deep accessorKey support (#4185)

    * feat: column helper utility, deep accessorKey support

    * Update main.tsx

    * fix: export column def union types

diff --git a/packages/table-core/src/core/column.ts b/packages/table-core/src/core/column.ts
--- a/packages/table-core/src/core/column.ts
+++ b/packages/table-core/src/core/column.ts
@@ -98,1 +94,1 @@
-    resolvedColumnDef.accessorKey ??
+    (accessorKey ? accessorKey.replace('.', '_') : undefined) ??
```

### Your minimal, reproducible example

https://codesandbox.io/s/quizzical-sun-4zm023?file=/src/main.tsx

### Steps to reproduce

1. create a simple table
2. give one of the column name "a.b"
3. use accessorkey a.b

### Expected behavior

it should show a.b in header
instead it crashes the table

### Platform

sandbox
mac os
v8.5.11

### react-table version

v8.5.11

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by oeddyo** [comment]
> I'm not sure it's a bug, although I agree that it can be confusing.
> 
> `.` in `accessorKey` is used to access deeply nested keys in objects.
> 
> When providing a `a.b` as the `accessorKey` `react-table` will expect `{ a: { b: "value" }` instead of `{ "a.b.": "value" }`.
> 
> Unless the maintainers want to support this use case it might be helpful to provide a more helpful error message explaining this.

From the code I think it was intentionally supporting using a dot as value since it's replacing dots with underscore. We relied on the assumption that dots in names are supported but thankfully tests caught the issues when upgrading. I believe maintaining consistency is important for users and the library. What do you think?

**Comment by dennemark** [comment]
Just stumbled over this issue on an older version and it is nice to see the new error message. But I was wondering, if it wouldn`t make more sense to return a `null` value, if the nested value does not exist?


```
for (const key of accessorKey.split('.')) {
   if(!(key in result)){
     return null
    }
    result = result[key]
    if (process.env.NODE_ENV !== 'production' && result === undefined) {
       throw new Error(
       `"${key}" in deeply nested key "${accessorKey}" returned undefined.`
        )
     }
}
```

**Comment by alico-cra** [comment]
For people still looking for an answer to the above (until it's fixed), seen this answer to resolve: https://github.com/TanStack/table/issues/579#issuecomment-841844029
