### ISSUE TITLE
Trying to pass in 'getGroupedRowModel' function to table instantiation causes browser to crash

### ISSUE THREAD

**Issue by rovolution** [TanStack/table#4330]
### Describe the bug

Hello!

I am trying to get the grouping functionality to work. However, whenever I try to pass the `getGroupedRowModel()` function reference into my table creation (via the `useReactTable()` hook), it keeps causing my browser to get caught in an infinite loop and crash.

here are the dependency versions my app is using:
```
├─ @tanstack/react-table@8.5.11
├─ react-dom@16.14.0
└─ react@16.14.0
```

I tried [following the suggestion from here](https://github.com/TanStack/table/issues/4125#issuecomment-1221178402), but wrapping my data in `useMemo()` does not do anything.

Here is my table configuration

```ts
 const table = useReactTable({
    columns: createColumnDefinitions(columns),
    data: data,
    enableMultiRowSelection: true,
    enableRowSelection: true,
    getCoreRowModel: getCoreRowModel(),
    getExpandedRowModel: getExpandedRowModel(),
    getGroupedRowModel: getGroupedRowModel(), // NOTE: When this line is commented out, it does not crash
    getRowId: getRowKey,
    getSortedRowModel: getSortedRowModel(),
    onSortingChange: updaterFn => {
      const sorting = (updaterFn as Function)() as Array<ColumnSort>
      const sortInfo = sorting[0] as ColumnSort

      if (
        sort &&
        sort.direction === 'ascending' &&
        sort.column === sortInfo.id
      ) {
        onSortChange(null)
      } else {
        const column = sortInfo.id
        const direction = sortInfo.desc ? 'descending' : 'ascending'
        onSortChange({ column, direction })
      }
    },
    sortDescFirst: true,
    state: {
      columnVisibility: createColumnVisibilityState(
        selectedRows,
        rows,
        onSelectRows
      ),
      grouping: createGroupingState(),
      rowSelection: createRowSelectionState(selectedRows, getRowKey),
      sorting: createSortingState(sort, columns),
    },
  })
```

### Your minimal, reproducible example

n/a

### Steps to reproduce

n/a

### Expected behavior

n/a

### How often does this bug happen?

Every time

### Platform

Chrome - Version 104.0.5112.101 (Official Build) (x86_64)

### react-table version

8.5.11

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by rovolution** [comment]
Ok never mind i figured it out...


I had to basically memoize my `createGroupingState()` function (so it wouldnt re-create the grouping array on each render) but damn that was really difficult to figure out. 

There needs to be better documentation around this. Otherwise its just confusing and a real struggle

**Comment by 1Ghasthunter1** [comment]
> I had to basically memoize my createGroupingState() function (so it wouldnt re-create the grouping array on each render)

**Yes, even with statically-coded arrays you have to do this!** For example:

```
const table = useReactTable({
    data: orders,
    columns,
    state: {
      grouping: ["vendor"],   //This line here crashes react.
    },
    getCoreRowModel: getCoreRowModel(),
    getGroupedRowModel: getGroupedRowModel(),
  });
```

Right way do do this to avoid crashing: 
```
    state: {
      grouping: useMemo(() => ["vendor"], []),  
    },
```

This should really be fixed or at least noted about in the docs; it's not obvious at all.
