### ISSUE TITLE
RTL column resizing doesn't work

### ISSUE THREAD

**Issue by giladv** [TanStack/table#4331]
### Describe the bug

while on RTL mode, column resizing is working backwards.

### Your minimal, reproducible example

https://codesandbox.io/s/mystifying-glade-ng5e9f

### Steps to reproduce

try to resize a column

### Expected behavior

should resize columns as expected but from right to left

### How often does this bug happen?

Every time

### Platform

all

### react-table version

latest

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by ierfaaan** [comment]
I'm getting the same issue :((

**Comment by mohsenomidi** [comment]
Dear @tannerlinsley 
Thanks for your great data table library 
Same issue here also in version 8, the RTL support is very important for many languages, is there any plan to fix resizing direction

**Comment by samuelarbibe** [comment]
Hey guys!   

You can check out my fork:  
https://github.com/samuelarbibe/table  
That fixes column resizing according to an added `rtl` option.  
  
To make column resizing work in an `rtl` context, you need to change 2 things:  
1. add `rtl: true` option to you `useTable` declaration  
```diff
  const table = useReactTable({
    data,
    columns,
+   rtl: true,
    columnResizeMode,
    getCoreRowModel: getCoreRowModel(),
    debugTable: true,
    debugHeaders: true,
    debugColumns: true
  });
```
2. change the `css` for you resizer
```diff
.resizer {
  position: absolute;
  top: 0;
+ left: 0;
- right: 0;
  height: 100%;
  width: 5px;
  background: rgba(0, 0, 0, 0.5);
  cursor: col-resize;
  user-select: none;
  touch-action: none;
}
```

This is a very basic WIP, just to get things to work.  
I can't promise I will form it into a complete `PR`, as this was done for personal purposes.

**Comment by AlonMiz** [comment]
hey, is there any progress on that? 🙏

**Comment by samuelarbibe** [comment]
Hey!
I have resolved to making my own forked library and using it, because I didn’t find a nice enough solution worthy of a PR.

**Comment by samuelarbibe** [comment]
Hey! just submitted a PR to add support for RTL column resizing. check it out: #5192

**Comment by KevinVandy** [comment]
^twas shipped
