### ISSUE TITLE
columnOrder is not respected by pinned columns

### ISSUE THREAD

**Issue by alexandergottlieb** [TanStack/table#4362]
### Describe the bug

Pinned columns are sorted according to `columnPinning.left`, rather than `columnOrder`.

### Your minimal, reproducible example

https://codesandbox.io/s/columnpinning-columnorder-q4hq2s.

### Steps to reproduce

 I've changed lines 75-83 of the column pinning example sandbox.

Notice that the age column appears before the first name column, even though `columnOrder === ['firstName', 'age']`.

### Expected behavior

I would expect the order of `columnOrder` to take precedence over `columnPinning.left` (maybe `columnPinning.left` should even be a `Set` rather than an `Array`).

This matches the behaviour described in [the docs](https://tanstack.com/table/v8/docs/guide/column-pinning):

>There are 3 table features that can reorder columns, which happen in the following order:
> 1. Column Pinning - If pinning, columns are split into left, center (unpinned), and right pinned columns.
> 2. Manual [Column Ordering](https://tanstack.com/table/v8/docs/column-ordering) - A manually specified column order is applied.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="1049" alt="Screenshot 2022-09-05 at 11 05 52" src="https://user-images.githubusercontent.com/17096321/188424455-0b799dd4-4a64-4578-b424-0cdd24834ce3.png">

### Platform

macOS 12.5, Chrome 104.0.5112.101

### react-table version

8.5.13

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Pinning order should trump column order, so this was intended functionality

**Comment by alexandergottlieb** [comment]
Thanks @KevinVandy. Does this mean the only way to change the order of pinned columns is by un-pinning and re-pinning?
