### ISSUE TITLE
All the documentation and examples I've seen for filtering use state.columns inside the Table component, with `onChange={value => column.setFilterValue(value)}`.

### ISSUE THREAD

**Issue by ganapathi-selva** [TanStack/table#4363]
All the documentation and examples I've seen for filtering use state.columns inside the Table component, with `onChange={value => column.setFilterValue(value)}`.

Is there a way I can expose this functionality to the parent component of my Table?

For context, my goal is to have a dashboard with filters at the top of the page that when set, filter down through all the various charts and tables on the screen.

Thanks

_Originally posted by @jasperdunn in https://github.com/TanStack/table/discussions/4361_

**Comment by jasperdunn** [comment]
This issue can be closed. Aggregating data like what I was attempting isn't a good approach in the front-end.
We moved to backend filtering and sorting.
