### ISSUE TITLE
[v8] Deleted rows do not affect table.getIsSomeRowsSelected() update

### ISSUE THREAD

**Issue by nirtamir2** [TanStack/table#4369]
### Describe the bug

I created a  table that allows deleting selected rows.
When I delete the rows - I set the data state to be without the the deleted rows.
When I do it - 
- `table.getSelectedRowModel()` get update well and now showing the deleted rows ✅ 
- `table.getIsSomeRowsSelected()` does not update well and returns true even if I deleted all the selected rows 🐛

I use `table.getSelectedRowModel()` to show the "all" checkbox seletion state like in your official example https://tanstack.com/table/v8/docs/examples/react/row-selection

### Your minimal, reproducible example

https://codesandbox.io/s/sweet-germain-qhzev6?file=/src/main.tsx

### Steps to reproduce

Click some table checkboxes
Notice that the select all rows checkbox is in `indeterminate` state
Click delete selected rows button (which set the data to the rows that does not include the selected rows)
The the select all rows state need to be unchecked (meaning no row selection) 

### Expected behavior

The select all rows state need to be unchecked when deleting rows that have been previously selected

### How often does this bug happen?

Every time

### Screenshots or Videos

https://user-images.githubusercontent.com/16452789/189105578-a4e1088b-e81d-4240-a1a5-bd75a77c0a73.mp4

_No response_

### Platform

MacOS 12.5.1
Chrome 104.0.5112.101

### react-table version

8.5.13

### TypeScript version

4.7.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This is expected to happen, because the `rowSelection` state does not get reset automatically when the `data` changes. This is especially useful when using manual pagination, filtering, etc. so that the rowSelection state can be persistent. 

To solve your problem, you should call `table.resetRowSelection()` at the same time as you delete your rows. That will clear the rowSelection state.

**Comment by Pirulax** [comment]
What if the data changes from external sources?
Imagine a users list that someone else can change as well on, for example, another computer?
If I understand correctly, `table.resetRowSelection()` will reset the selection on all rows, right?
