### ISSUE TITLE
Invalid `sorting` column causes crash

### ISSUE THREAD

**Issue by joshuabaker** [TanStack/table#4409]
### Describe the bug

When providing `sorting` state, invalid columns causes a crash.

In scenarios where the data changes between tables but the component does not (e.g. Next.js, SPAs, etc.) the `sorting` state is saved and causes a crash.

### Your minimal, reproducible example

https://codesandbox.io/s/react-table-sorting-issue-755jyu

### Steps to reproduce

1. Select a link in the preview
2. Navigate to either of the other links

### Expected behavior

I’d expect the underlying library to ignore any invalid `sorting` columns.

### How often does this bug happen?

Every time

### Platform

Using Next.js

### react-table version

8.5.13

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This was originally a safe-guard to make sure devs noticed an error during development and would not supply invalid ids. Not sure if we want to get rid of this error, but maybe we should just console.warn instead of throw error? @tannerlinsley

**Comment by tannerlinsley** [comment]
Yeah that sounds good.

**Comment by jonahallibone** [comment]
Would this warning be thrown in the aforementioned scenario? I also was struggling with this and opted to reset the sort on page change.

**Comment by joshuabaker** [comment]
A warning would be certainly preferable to an error. 

Is there a reason passing invalid sorting is wrong though (i.e. performance, internals, etc.)?

There’s lots of scenarios where metrics can change the columns on the same page/view. It’d be preferable not to have to clear the state in scenarios where saving the sort order of a variant is the desired UX.

**Comment by joshuabaker** [comment]
This appears to have been resolved. 🙏🏻
