### ISSUE TITLE
[React] subRows are not included in row.getIsSelected() 

### ISSUE THREAD

**Issue by james-Infotrack** [TanStack/table#4413]
### Describe the bug

I'm passing selectedRows to another table instance in another Route for printing. 

```js
  const selectedRows = rows.filter((row) => row.getIsSelected()); 
```
This works fine, if the rows are expanded, but if they are collapsed. the subrows are ignored.

### Your minimal, reproducible example

https://codesandbox.io/s/fervent-meadow-qymqg0?file=/src/main.tsx

### Steps to reproduce

Click the top row, 

I'm currently logging `rows.map(row => row.getIsSelected() )`

![image](https://user-images.githubusercontent.com/71992800/193198904-21249308-4095-4834-9030-42184ae46a2c.png)

now expand the row and see that the children are selected as well and now included in this 
![image](https://user-images.githubusercontent.com/71992800/193198974-ede76b95-1175-4aa2-ac2c-2a0e2c17a871.png)

### Expected behavior

Selecting a row that has subRows should include the subRows even if they are collapsed. 

### How often does this bug happen?

Every time

### Platform

latest chrome

### react-table version

"@tanstack/react-table": "8.5.13",

### TypeScript version

4.5.5

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Victor2333** [comment]
After I debug in code. I think this is not a problem. If you want to check all selected rows including sub rows. You should call 
```js
table.getRowModel().flatRows.map(r => r.getIsSelected()
```
In your case. The row which you get. It has property sub rows.

**Comment by james-Infotrack** [comment]
> After I debug in code. I think this is not a problem. If you want to check all selected rows including sub rows. You should call
> 
> ```js
> table.getRowModel().flatRows.map(r => r.getIsSelected()
> ```
> 
> In your case. The row which you get. It has property sub rows.

This worked perfectly thankyou!
