### ISSUE TITLE
Group on a column that has custom component

### ISSUE THREAD

**Issue by gaddario98** [TanStack/table#4466]
### Describe the bug

Grouping on a column with a custom component results in a single row and the first value of the custom column as the cell value.

Is there a solution to this problem?

### Your minimal, reproducible example

https://codesandbox.io/s/react-library-7ccz1i?file=/src/tableGroupBy.tsx

### Steps to reproduce

Click on "Custom Column 👊"

### Expected behavior

20 lines because each component has different data.

### How often does this bug happen?

Every time

### Screenshots or Videos

![group_by_custom_column](https://user-images.githubusercontent.com/68993095/196926684-0c55619a-0f8f-413d-a515-7a89ac7492fe.png)

### Platform

Windows

### react-table version

8.5.15

### TypeScript version

4.8.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by bring-shrubbery** [comment]
I have exactly the same issue, but I've identified this issue to happen when I'm passing an object to as the cell into the `data` property of `useTable` hook.

I've created a **minimal, reproducible example** [HERE](https://codesandbox.io/s/github/bring-shrubbery/test-table-grouping). It is just a grouping example from the docs, but with the `firstName` replaced by an object with `label` property instead of directly providing `string`.

**Comment by bring-shrubbery** [comment]
This does look like a bug or unimplemented feature to me, unless I'm doing something wrong.

**Comment by briinki** [comment]
I'm facing the same issue here.

Quote:
> I've also noticed, that when the grouping is enabled, the items are indexed by key:[object Object]. It looks like the library is trying to group the items by the value of the cell that is being grouped, but since the cell is an object, the value is converted to "[object Object]", thus all rows look the same.

**Comment by KevinVandy** [comment]
Accessors are not meant to have JSX. That's what custom `cell`, `aggregatedCell`, etc. are for. Accessors must only resolve primitive values if you expect sorting, filtering, or grouping to work.

Also see the `getGroupingValue` column option if you need the value that you group on to be different than your accessor's value.
