### ISSUE TITLE
Initial pageIndex in state gets reset to 0 when getGroupedRowModel is added

### ISSUE THREAD

**Issue by daphnesmit** [TanStack/table#4480]
### Describe the bug

Table doesnt maintain the pageIndex set in the state on load when getGroupedRowModel is added to the table.

Reproduction is a fork of the grouping sandbox and just added a pagination useState to it:
https://codesandbox.io/s/wandering-river-8jl0ns?file=/src/main.tsx

### Your minimal, reproducible example

https://codesandbox.io/s/wandering-river-8jl0ns?file=/src/main.tsx

### Steps to reproduce

1. I added a table with a useState with an initial pagination state of ```{pageIndex:2, pageSize: 20}```
2. I added to useReactTable: ```{ state: { pagination }}```
3. This works ok. 
4. The I added getGroupedRowModel to the useReactTable
5. Then the initial pagination is quickly logged as 2, but then directly reset to pageIndex 0.

### Expected behavior

 As user I expect the table to maintain my initial state set on load of the table with pageIndex 2 and not reset to 0

### How often does this bug happen?

Every time

### Platform

MacOs, chrome

### react-table version

8.5.15

### TypeScript version

4.6.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Cifixie** [comment]
Have been debugging similar issue: found out that there is an option called `autoResetPageIndex` you can set on false. Not sure if that helps. There is this still wage concept to me that triggers resets, ie. when ever calling `table.getFilteredRowModel()`, that causes unexpected behaviour

**Comment by daphnesmit** [comment]
> Have been debugging similar issue: found out that there is an option called `autoResetPageIndex` you can set on false. Not sure if that helps.

it does not help.

**Comment by daphnesmit** [comment]
In latest react table issue seems solved!
