### ISSUE TITLE
[V8] You may need an additional loader to handle the result of these loaders

### ISSUE THREAD

**Issue by samyan** [TanStack/table#4500]
### Describe the bug

I'm trying to run react app with your library but I get runtime error:

```
./node_modules/@tanstack/react-table/build/umd/index.production.js 106:18
Module parse failed: Unexpected token (106:18)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|           i = l.accessorKey;
|     let r,
>         a = l.id ?? (i ? i.replace(".", "_") : void 0) ?? ("string" == typeof l.header ? l.header : void 0);
|     if (l.accessorFn ? r = l.accessorFn : i && (r = i.includes(".") ? e => {
|       let t = e;
```

### Your minimal, reproducible example

localhost

### Steps to reproduce

This is my npm package:

```
├── @tanstack/react-table@8.5.22
├── @types/match-sorter@6.0.0
├── @types/node@14.14.37
├── @types/react-dom@17.0.3
├── @types/react-router-dom@5.1.7
├── @types/react@17.0.3
├── react-dom@17.0.2
├── react-i18next@11.18.0
├── react-router-dom@5.2.0
├── react-scripts@4.0.3
├── react@17.0.2
├── typescript@4.2.3
└── web-vitals@1.1.1
```

My code:

```typescript
const table = useReactTable({
	data,
	columns,
	getCoreRowModel: getCoreRowModel()
});

return (
	<div className='p-2'>
		<table>
			<thead>
				{table.getHeaderGroups().map((headerGroup) => (
					<tr key={headerGroup.id}>
						{headerGroup.headers.map((header) => (
							<th key={header.id}>
								{header.isPlaceholder ? null : flexRender(header.column.columnDef.header, header.getContext())}
							</th>
						))}
					</tr>
				))}
			</thead>
			<tbody>
				{table.getRowModel().rows.map((row) => (
					<tr key={row.id}>
						{row.getVisibleCells().map((cell) => (
							<td key={cell.id}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>
						))}
					</tr>
				))}
			</tbody>
			<tfoot>
				{table.getFooterGroups().map((footerGroup) => (
					<tr key={footerGroup.id}>
						{footerGroup.headers.map((header) => (
							<th key={header.id}>
								{header.isPlaceholder ? null : flexRender(header.column.columnDef.footer, header.getContext())}
							</th>
						))}
					</tr>
				))}
			</tfoot>
		</table>
	</div>
);
```

### Expected behavior

Get result.

### How often does this bug happen?

Every time

### Platform

Windows 11 // Node v16.151

### react-table version

v8.5.22

### TypeScript version

v4.2.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by gear4s** [comment]
this issue was first introduced in 8.5.15 - we are currently using 8.5.13 to build our front-end

**Comment by samyan** [comment]
> this issue was first introduced in 8.5.15 - we are currently using 8.5.13 to build our front-end

I will try with 8.5.13. Thanks for response.

**Comment by samyan** [comment]
Working with 8.5.13 for now as @gear4s suggested. Any idea when will be fixed?

**Comment by gear4s** [comment]
try to change your browser targets from this:
```json
"browserslist": {
   "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
},
```

to this:
```json
"browserslist": [
   ">0.2%",
  "not dead",
  "not op_mini all"
],
```

**Comment by samyan** [comment]
> try to change your browser targets from this:
> 
> ```json
> "browserslist": {
>    "production": [
>       ">0.2%",
>       "not dead",
>       "not op_mini all"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
> },
> ```
> 
> to this:
> 
> ```json
> "browserslist": [
>    ">0.2%",
>   "not dead",
>   "not op_mini all"
> ],
> ```
> 
> it could also be an issue with your version of React-Scripts not supporting Babel version that implements the `??` operator - try to update to `react-scripts@3.4.4` too

I've tried **_browserslist_** already but no luck. About **_react-scripts_** version, maybe. I will try later and write you. Thanks!

**Comment by nrayburn-tech** [comment]
Your issue is likely due to how Create React App processes dependency code, here is an issue from that repo with a more detailed explanation.

https://github.com/facebook/create-react-app/issues/11339#issuecomment-915716259

**Comment by patrickgalbraith** [comment]
I had this same issue when using v8 with Storybook. Fix was to extend the webpack config to process react-table.

**.storybook/main.js**

```
const nodeModulesThatNeedToBeParsedBecauseTheyExposeES6 = [
  '@tanstack[\\\\/]react-table',
];

module.exports = {
  // ...
  webpackFinal: async (config) => {
    return {
      ...config,
      module: {
        ...config.module,
        rules: config.module.rules.map((rule) => {
          if (rule.test.toString() !== String(/\.js$/)) return rule;

          const include = new RegExp(
            `[\\\\/]node_modules[\\\\/](${nodeModulesThatNeedToBeParsedBecauseTheyExposeES6.join(
              '|'
            )})`
          );

          if (Array.isArray(rule.include)) {
            rule.include.push(include);
          } else {
            rule.include = [rule.include, include].filter(Boolean);
          }

          return rule;
        }),
      },
    };
  },
```

**Comment by KevinVandy** [comment]
@samyan @gear4s @patrickgalbraith  Try out the newest TanStack Table `v8.7.0` and let us know if you are still running into problems here

We think PR https://github.com/TanStack/table/pull/4552 should have fixed this issue.

**Comment by samyan** [comment]
> @samyan @gear4s @patrickgalbraith Try out the newest TanStack Table `v8.7.0` and let us know if you are still running into problems here
> 
> We think PR #4552 should have fixed this issue.

Working perfect! Thank you.

**Comment by patrickgalbraith** [comment]
@KevinVandy 8.7.0 works great! 

However I tried v8.7.3 and the issue has returned, was there a regression recently?

**Comment by patrickgalbraith** [comment]
Error I'm getting in 8.7.3

```
ERROR in ./node_modules/@tanstack/react-table/build/lib/index.esm.js 64:28
Module parse failed: Unexpected token (64:28)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     onStateChange: updater => {
|       setState(updater);
>       options.onStateChange?.(updater);
|     }
|   }));
```

**Comment by KevinVandy** [comment]
> Error I'm getting in 8.7.3
> 
> ```
> ERROR in ./node_modules/@tanstack/react-table/build/lib/index.esm.js 64:28
> Module parse failed: Unexpected token (64:28)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> |     onStateChange: updater => {
> |       setState(updater);
> >       options.onStateChange?.(updater);
> |     }
> |   }));
> ```

There have been no code changes pretty much between 8.7.0 and 8.7.3, which is making this hard to figure out why it is happening

**Comment by marwen-cherif** [comment]
Rollback to version 8.5.11 allowed me to get arround the problem.

it seems that the problem was introduced between 8.512 and 8.5.30

8.5.30 => KO
8.5.11 => OK

**Comment by vishal-rathod-07** [comment]
> Error I'm getting in 8.7.3
> 
> ```
> ERROR in ./node_modules/@tanstack/react-table/build/lib/index.esm.js 64:28
> Module parse failed: Unexpected token (64:28)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> |     onStateChange: updater => {
> |       setState(updater);
> >       options.onStateChange?.(updater);
> |     }
> |   }));
> ```

I am also getting same error.

I am using "react-scripts": "3.0.1" and "@tanstack/react-table": "8.7.2".

any solution without changing browserlist.

**Comment by valentinkorzun** [comment]
> > Error I'm getting in 8.7.3
> > ```
> > ERROR in ./node_modules/@tanstack/react-table/build/lib/index.esm.js 64:28
> > Module parse failed: Unexpected token (64:28)
> > You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > |     onStateChange: updater => {
> > |       setState(updater);
> > >       options.onStateChange?.(updater);
> > |     }
> > |   }));
> > ```
> 
> I am also getting same error.
> 
> I am using "react-scripts": "3.0.1" and "@tanstack/react-table": "8.7.2".
> 
> any solution without changing browserlist.

I also have this error. Any updates?

**Comment by ivanov-v** [comment]
Error with 8.7.2. Maybe reopen issue?

**Comment by ellisPae** [comment]
> > Error I'm getting in 8.7.3
> > ```
> > ERROR in ./node_modules/@tanstack/react-table/build/lib/index.esm.js 64:28
> > Module parse failed: Unexpected token (64:28)
> > You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > |     onStateChange: updater => {
> > |       setState(updater);
> > >       options.onStateChange?.(updater);
> > |     }
> > |   }));
> > ```
> 
> I am also getting same error.
> 
> I am using "react-scripts": "3.0.1" and "@tanstack/react-table": "8.7.2".
> 
> any solution without changing browserlist.

I'm getting the same exact issue on `8.7.4`

**Comment by gear4s** [comment]
@KevinVandy I'm sure that the issues are related to the `react-scripts` these guys are using. what finally, really fixed the issue for us, was upgrading from `react-scripts@3.2.0` to `react-scripts@3.4.1`. what would likely have triggered this to arise is a change to the build process.

@ellisPae @valentinkorzun @vishal-rathod-07 could you try to update `react-scripts` first?

**Comment by WilsonCWong** [comment]
Having the same issue with `react-scripts@4.0.3` and `@tanstack/react-table@8.7.4`.

**Comment by vishal-rathod-07** [comment]
@gear4s Updating `react-scripts@3.4.1` works for me thanks 👍🏻.

**Comment by netdesignr** [comment]
Downgrading to 8.7.0 it solved the issue

**Comment by patrickgalbraith** [comment]
Something has obviously changed when the package is built:

```ts
// v8.7.0
onStateChange: updater => {
  setState(updater);
  options.onStateChange == null ? void 0 : options.onStateChange(updater);
}

// v8.7.4
onStateChange: updater => {
  setState(updater);
  options.onStateChange?.(updater);
}
```

@KevinVandy if I do a build locally and install using `npm` then I get the result from `v8.7.4` **BUT** if I install using `yarn` then I get the correct result. You have a `yarn.lock` but you don't have a `package-lock.json` so when you do the build locally it is correct but the CI builds are using `npm install` which will pull the latest dependencies. So you may want to use `yarn` when doing the install in your Gitlab CI config.

**Comment by oneblockchain** [comment]
> try to change your browser targets from this:
> 
> ```json
> "browserslist": {
>    "production": [
>       ">0.2%",
>       "not dead",
>       "not op_mini all"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
> },
> ```
> 
> to this:
> 
> ```json
> "browserslist": [
>    ">0.2%",
>   "not dead",
>   "not op_mini all"
> ],
> ```
> 
> it could also be an issue with your version of React-Scripts not supporting Babel version that implements the `??` operator - try to update to `react-scripts@3.4.4` too

This works for me, thanks!

**Comment by KevinVandy** [comment]
@oneblockchain this should no longer be necessary in the latest version of table though
