### ISSUE TITLE
Documentation Propriety Naming is Wrong

### ISSUE THREAD

**Issue by VincentBoutch** [TanStack/table#4534]
### Describe the bug

AutoResetPagination mentionned in the documentation in the source code doesn't exists it's autoResetPageIndex. 

### Your minimal, reproducible example

https://codesandbox.io/s/inspiring-stallman-xk6jlm?file=/src/main.tsx

### Steps to reproduce

In the documentation it's:
![image](https://user-images.githubusercontent.com/113119083/201966957-91211042-b4b4-4bc5-a55a-9b1863651ca7.png)
but in the source code it's : 
 autoResetPageIndex

### Expected behavior

see the video (used property  autoResetPageIndex: false)

### How often does this bug happen?

Every time

### Screenshots or Videos

https://user-images.githubusercontent.com/113119083/201966496-5cdf85a0-baf3-400e-a5ee-ee49cc74964c.mp4

### Platform

Windows

### react-table version

latest

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Feel free to make PRs when you notice really small typos like this in the docs. It helps us out a lot faster.
