### ISSUE TITLE
@tanstack/react-table not building?

### ISSUE THREAD

**Issue by shyce** [TanStack/table#4575]
### Describe the bug

I went to upgrade @tanstack/react-table to 8.7.1 and it said it didn't exist. Seems it stopped building to npm registry since eversion 8.7.0?

### Your minimal, reproducible example

NA

### Steps to reproduce

Upgrade package.json to 8.7.1 for @tanstack/react-table and run `npm i`

### Expected behavior

@tanstack/react-table would be built when @tanstack/table is built

### How often does this bug happen?

Every time

### Platform

NA

### react-table version

8.7.1

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
It's because it doesn't exist. Install v8.7.0 if you are using React. v8.7.1 was only for the Vue adapter
