### ISSUE TITLE
Aggregation Median incorrect calculation

### ISSUE THREAD

**Issue by timsun28** [TanStack/table#4582]
### Describe the bug

The current implementation of calculation of the median is incorrect. 
This bug has been report before [here](https://github.com/TanStack/table/issues/2588), and it was fixed in the following [commit](https://github.com/TanStack/table/commit/6a9223bb11821b48a92531f493e171f0df0d62c8).

However, if you now go to the [current file](https://github.com/TanStack/table/blob/main/packages/table-core/src/aggregationFns.ts) the old version is back again. 

### Your minimal, reproducible example

https://codesandbox.io/s/exciting-sun-ddlcoz?file=/src/main.tsx

### Steps to reproduce

Go to the given sandbox and click on the hand icon with More info. This will turn the table into a grouped view and will calculate the median for the age column and for the progress column. 

### Expected behavior

With the fixed data set it should be: age 15 and profile progress should be 20%. Those are the middle values of the three options. An alternative test case would be to add one more row and see if it calculates the average correctly of the two middle rows. 

### How often does this bug happen?

Every time

### Platform

Any platform - version 8.7.1

### react-table version

v8.7.1

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alex314159** [comment]
adding my voice - it's an important and simple fix, and the solution was provided

**Comment by KevinVandy** [comment]
> adding my voice - it's an important and simple fix, and the solution was provided

Feel free to PR again

**Comment by alex314159** [comment]
Afraid I know nothing about TS, I use material-react-table through Clojurescript. Happy to PR the following if you think it works:

```
const median: AggregationFn<any> = (columnId, leafRows) => {
  if (!leafRows.length) {
    return
  }

//   let min = 0
//   let max = 0
//
//   leafRows.forEach(row => {
//     let value = row.getValue(columnId)
//     if (typeof value === 'number') {
//       min = Math.min(min, value)
//       max = Math.max(max, value)
//     }
//   })
//
//   return (min + max) / 2

  let mid = Math.floor(leafRows.length / 2)
  let values = leafRows.map(d => d.getValue(columnId)).sort((a, b) => a - b)
  return values.length % 2 !== 0 ? values[mid] : (values[mid - 1] + values[mid]) / 2

}
```

**Comment by KevinVandy** [comment]
> Afraid I know nothing about TS, I use material-react-table through Clojurescript. Happy to PR the following if you think it works:

I had never heard of Clojurescript, but glad MRT is working for you. Looking into the median calc a bit more

**Comment by alex314159** [comment]
thanks!
