### ISSUE TITLE
ColumnDef Meta cannot be declared with pnpm

### ISSUE THREAD

**Issue by sharky98** [TanStack/table#4597]
### Describe the bug

When using `pnpm` as a package manager, `@tanstack/table-core` is not installed in `node_modules`, as this is only a dependency of `@tanstack/react-table`.

As such, this table-core package is not available for the project when declaring the meta as shown in [the docs](https://tanstack.com/table/v8/docs/api/core/column-def#meta).

For info, `pnpm` puts only packages listed in `package.json` in the `node_modules` directory. For the deps of these packages, they are "hidden" from the project into some symlinked folders.

### Your minimal, reproducible example

can't provide due to corporate proxy

### Steps to reproduce

1. Add `@tanstack/react-table` as a dependency of a project using `pnpm`.
2. Try declaring `meta` as per docs (I had to change the import a bit though).

```ts
import type {RowData} from "@tanstack/react-table";

declare module '@tanstack/table-core' {
  interface ColumnMeta<TData extends RowData, TValue> {
    foo: string
  }
}
```

### Expected behavior

As a user, I expected to be able to use `Meta` directly. However, I must install another package that was not declared (either in the docs or as peer deps).

=> Recommended solution would be to place `@tanstack/table-core` as a peer deps, flagging it optional. See [pnpm docs](https://pnpm.io/package_json#peerdependenciesmeta) and [npm docs](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#peerdependencies). Also, adding a note in the [Meta section of the docs](https://tanstack.com/table/v8/docs/api/core/column-def#meta) that this optional peer is required to make use of this feature using `pnpm` and Typescript.

### How often does this bug happen?

Every time

### Platform

- OS: Windows

### react-table version

v8.7.0

### TypeScript version

v4.9.4

### Additional context

=> As a workaround, I can installed the package manually.

Also, I can `// @ts-ignore` the lines causing issues (including when using the meta when rendering, since it can't find `foo`), but I lose Typescript IDE hinting.

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by sharky98** [comment]
My bad... I see that my mistake was that I did not name the file with `*.d.ts`.

**Comment by acailly** [comment]
@sharky98 where did you put your .d.ts file? do you have IDE autocompletion on your custom meta properties?

**Comment by sharky98** [comment]
I just put it somewhere (named `types`, but the file was in another folder first) in my project folder and the IDE just picked up.
