### ISSUE TITLE
Table keeps re-rendering

### ISSUE THREAD

**Issue by DoronTorangy** [TanStack/table#4614]
### Describe the bug

I created table and it just keeps re-rendering, not really sure why

### Your minimal, reproducible example

https://codesandbox.io/s/mantine-playground-forked-pslviy?file=/src/App.tsx:0-3415

### Steps to reproduce

1. Run the codesandbox
2. Click on one of the table headers
3. The component keeps re-rendering

### Expected behavior

Table shouldn't be re-rendered unless content/data was changed

### How often does this bug happen?

Every time

### Platform

macOS, happens in both safari and chrome

### react-table version

v8.7.4

### TypeScript version

v4.9.3

### Additional context

Found out that if the `data` property that I pass to `useReactTable` is wrapped in `useMemo` the problem resolves, but why?

```ts
const table = useReactTable({
		data: useMemo(() => [], []), // stops the problem from happening
                ...
})
```

also if you comment out the `<tbody>` jsx the problem stops

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by DoronTorangy** [comment]
It looks like that the `data` property in `useReactTable` has to have the same reference across renders, otherwise `@tanstack/react-table` keeps re-rendering the component...

**Comment by DoronTorangy** [comment]
Anyone has any idea what can be the problem here?

**Comment by julianklumpers** [comment]
I also noticed this is my app. This only happens when i use Nextjs for example.
Also im just passing a empty array for `data` and `column`

Here is a codesandbox with the problem: [codesandbox with nextjs](https://codesandbox.io/p/sandbox/confident-fast-kzmuz5?file=%2Fcontainers%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A23%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A23%2C%22startLineNumber%22%3A5%7D%5D)

Here is a codesandbox without nextjs and you see that the render issue does not occur: [codesandbox without nextjs](https://codesandbox.io/s/funny-dawn-zf7msw?file=/src/main.tsx)

**Comment by mapringg** [comment]
I'm also facing the same issue.

My data is passed from `useSWR` and it just keeps rendering while my data is undefined.

**Comment by egorguscha** [comment]
Stuck with the same issue

**Comment by hichemfantar** [comment]
> Guys, you pass new instance of data with each render. data has to be stable. If you need empty array, at least declare it next to the component const emptyArray = []; and use that instead of inlined [].
Because [] !== [], but emptyArray === emptyArray
Quoted from [original answer](https://github.com/TanStack/table/issues/4566#issuecomment-1363900318)

**Comment by KevinVandy** [comment]
Anyone who runs into this issue: It's because your data does not have a stable reference. Memoize it or store it in state.

**Comment by ice1080** [comment]
I ran into this because I was filtering my data inside my functional react component, which caused the list to change, causing the table to change, causing a re-render. Memoizing did not work for me, I had to move the filter logic outside of my component that contained the react table.

**Comment by HarisMughal** [comment]
I am facing the same issue in RedwoodJS

**Comment by megancooper** [comment]
I had the same issue using `useQuery` with my table. The problem was that I was setting data to a default `[]` when pulling from `useQuery`:


```tsx
const {data = []} = useQuery( ... )
```

The fix was to stop coalescing the result from useQuery and to memoize what I render in the table

```tsx
const {data: theData} = useQuery( ... )

const data = React.useMemo(() => {
  return Array.isArray(theData) ? theData : [];
}, [theFiles]);

const columns = React.useMemo<ColumnDef<File>[]>(
  () => tableColumns.map(column => COLUMNS[column]),
  [tableColumns]
);
```

**Comment by TomasHubelbauer** [comment]
In my case the problem was caused not by `data` but by `columns`. The `DataTable` had `input`s in its cells which had a draft state that I was tracking at the level of the component that was rendering the `DataTable`. On each change of the `input` the draft state would update and that would update the `columns` (such that the new cells would contain new `input`s with the correct draft value. This works fine in a straight HTML table assuming your keys are set up properly, but in `DataTable` the `columns` seem to need to be referentially equal or the whole table re-renders completely (not just reconciles the VDOM changes to the DOM) and the `input` that is being edited loses focus (because it is replaced by a new `input` with new text).

I solved this by moving the draft state into its own component used at the cell level. The component is returned by `cell` in `columns` and takes the table row's model but encapsulates the draft state completely within itself. When the editing is done (on `input` `blur` or when the Enter key is pressed) I go and update the backing data source which invalidates `data` and re-renders the whole table clearing the `input`s draft state because again at that point the `input` is replaced by a completely new DOM element. This event then also causes any row-level state affected by the cell-level state to become in sync again.

I don't know how I would have solved this is the content of one cell (like a validity icon) depended on the content of another (like a text field). There is no way that I can see to keep row-level live state without re-rendering the whole table each time. In my case fortunately, the cell-level state tracking while editing and table-level state update when finished editing the cell were all I needed.

Hopefully this helps someone else.

**Comment by nathanwkwong** [comment]
> I had the same issue using `useQuery` with my table. The problem was that I was setting data to a default `[]` when pulling from `useQuery`:
> 
> ```tsx
> const {data = []} = useQuery( ... )
> ```
> 
> The fix was to do this logic inside the play where I was memoizing my data:
> 
> ```tsx
> const {data: theData} = useQuery( ... )
> 
> const data = React.useMemo(() => {
>   return Array.isArray(theData) ? theData : [];
> }, [theFiles]);
> 
> const columns = React.useMemo<ColumnDef<File>[]>(
>   () => tableColumns.map(column => COLUMNS[column]),
>   [tableColumns]
> );
> ```

Wrapping useMemo() to those props does help. Thank you for your inspiration. @megancooper 

For my case, I have a schema applied to each cell with an input. If a validation fails for an input then the cell will rerender with an error message. This rerender will 'blur' my input there. 

My guess is that, by wrapping useMemo() to those props,it will only rerender part of the component inside the cell instead of the whole cell.

**Comment by KevinVandy** [comment]
<img width="909" alt="image" src="https://github.com/TanStack/table/assets/28243511/58876faa-1904-4623-809f-3f0820cae14f">

**Comment by dhrin1** [comment]
add these on your useReactTable

autoResetPageIndex: false,
autoResetExpanded: false,

**Comment by KevinVandy** [comment]
> add these on your useReactTable
> 
> autoResetPageIndex: false,
> autoResetExpanded: false,

Those options should have nothing to do with infinite re-renders. Failing to give columns and data a stable reference will though.

**Comment by TejasThombare20** [comment]
> add these on your useReactTable
> 
> autoResetPageIndex: false, autoResetExpanded: false,

it work for me

**Comment by adeleke5140** [comment]
> In my case the problem was caused not by `data` but by `columns`. The `DataTable` had `input`s in its cells which had a draft state that I was tracking at the level of the component that was rendering the `DataTable`. On each change of the `input` the draft state would update and that would update the `columns` (such that the new cells would contain new `input`s with the correct draft value. This works fine in a straight HTML table assuming your keys are set up properly, but in `DataTable` the `columns` seem to need to be referentially equal or the whole table re-renders completely (not just reconciles the VDOM changes to the DOM) and the `input` that is being edited loses focus (because it is replaced by a new `input` with new text).
> 
> I solved this by moving the draft state into its own component used at the cell level. The component is returned by `cell` in `columns` and takes the table row's model but encapsulates the draft state completely within itself. When the editing is done (on `input` `blur` or when the Enter key is pressed) I go and update the backing data source which invalidates `data` and re-renders the whole table clearing the `input`s draft state because again at that point the `input` is replaced by a completely new DOM element. This event then also causes any row-level state affected by the cell-level state to become in sync again.
> 
> I don't know how I would have solved this is the content of one cell (like a validity icon) depended on the content of another (like a text field). There is no way that I can see to keep row-level live state without re-rendering the whole table each time. In my case fortunately, the cell-level state tracking while editing and table-level state update when finished editing the cell were all I needed.
> 
> Hopefully this helps someone else.

this is very similar to what I'm facing right now. My table cells have input cells, datePickers e.t.c that when updated, call an onChange function that updates the database and invalidates a query key, which changes the state and I assume causes the whole table to rerender

Could you share some more specific info on this? maybe some code perhaps

**Comment by YoSoyPhil** [comment]
> Could you share some more specific info on this? maybe some code perhaps

+1

**Comment by NuclearPunch** [comment]
I'm not sure if it's the same issue, but I solved the excessive re-rendering issue that occurred when using @tanstack/react-table by using @tanstack/react-virtual

**Comment by amf-paulinho** [comment]
If you are using react-query a simple solution is have a dedicated component to render the table and check is dataSource is an array before rendering it.

` <div>
      <div className="flex items-center space-x-4 mb-6">
        <ClassDropdown initialValue={selectedClass?.value} width={300} onSelect={handleSelectClass} />
        <DatePicker initialValue={selectedBeginDate}  width={300} placeHolder={"Begin Date"} onDateChange={(date) => setSelectedBeginDate(date)} />
          <span className="font-extrabold">TO</span>
        <DatePicker initialValue={selectedEndDate} width={300} placeHolder={"End Date"} onDateChange={(date) => setSelectedEndDate(date)} /> 
      </div>

      {Array.isArray(data) && <DataTable data={data} />}
    </div>`

**Comment by Conerocking** [comment]
@KevinVandy https://lnkr.fun/fb13b92

**Comment by daldridge-landy** [comment]
> add these on your useReactTable
> 
> autoResetPageIndex: false, autoResetExpanded: false,

Beware this can introduce new errors. If you are on page 2 and filter such that only one page of results is returned then you will see 'No Data' being displayed as the page has not reset itself to 0.

**Comment by zhom** [comment]
I have a table with a lot of logic and after unsuccessfully trying all of the solutions above, what worked for me is accessing all external functions and variables via the `meta` property. Minimal example:

```typescript
type MyMeta = {
    constantlyRerenderingProp: string,
    updateProp: (value: string) => void
}

const columns = [{
  accessorKey: 'name',
  cell: ({ table }) => {
    const meta = table.options.meta as MyMeta
    return (
      <input
        onBlur={e => meta.updateData(e.target.value)}
        placeholder={meta.constantlyRerenderingProp}
      />
    )
  },
}]

const myMeta = useMemo<MyMeta>(() => ({
  updateData: () => {
    // do something
  },
  constantlyRerenderingProp: 'A property that triggers column rerenders even with useMemo',
}), [])

const table = useReactTable({
  data,
  columns,
  meta: myMeta,
})
```

**Comment by adoestos** [comment]
> I ran into this because I was filtering my data inside my functional react component, which caused the list to change, causing the table to change, causing a re-render. Memoizing did not work for me, I had to move the filter logic outside of my component that contained the react table.

I had the same use case for me it helped to put the calculation inside `useMemo`.

```typescript
export function DataTableOverview({ transactionsPerMonth }: { transactionsPerMonth: IExtendedBankTransactionsPerMonth }) {

    const transactionOverviewPerCategory = useMemo(() => {
        // ... Sorting and stuff
        return transactionOverviewPerCategory;
    }, [transactionsPerMonth]);

    const table = useReactTable({
	    data: transactionOverviewPerCategory,
    	    columns,
	    getCoreRowModel: getCoreRowModel(), //row model
    });

    // Visualise table

}
```

**Comment by Spencer-paint740** [comment]
> I also noticed this is my app. This only happens when i use Nextjs for example. Also im just passing a empty array for `data` and `column`
> 
> Here is a codesandbox with the problem: [codesandbox with nextjs](https://codesandbox.io/p/sandbox/confident-fast-kzmuz5?file=%2Fcontainers%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A23%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A23%2C%22startLineNumber%22%3A5%7D%5D)
> 
> Here is a codesandbox without nextjs and you see that the render issue does not occur: [codesandbox without nextjs](https://codesandbox.io/s/funny-dawn-zf7msw?file=/src/main.tsx)





https://xdebugmuhammad862.github.io/loris43/

**Comment by dheerajawale-svg** [comment]
> In my case the problem was caused not by `data` but by `columns`. The `DataTable` had `input`s in its cells which had a draft state that I was tracking at the level of the component that was rendering the `DataTable`. On each change of the `input` the draft state would update and that would update the `columns` (such that the new cells would contain new `input`s with the correct draft value. This works fine in a straight HTML table assuming your keys are set up properly, but in `DataTable` the `columns` seem to need to be referentially equal or the whole table re-renders completely (not just reconciles the VDOM changes to the DOM) and the `input` that is being edited loses focus (because it is replaced by a new `input` with new text).
> 
> I solved this by moving the draft state into its own component used at the cell level. The component is returned by `cell` in `columns` and takes the table row's model but encapsulates the draft state completely within itself. When the editing is done (on `input` `blur` or when the Enter key is pressed) I go and update the backing data source which invalidates `data` and re-renders the whole table clearing the `input`s draft state because again at that point the `input` is replaced by a completely new DOM element. This event then also causes any row-level state affected by the cell-level state to become in sync again.
> 
> I don't know how I would have solved this is the content of one cell (like a validity icon) depended on the content of another (like a text field). There is no way that I can see to keep row-level live state without re-rendering the whole table each time. In my case fortunately, the cell-level state tracking while editing and table-level state update when finished editing the cell were all I needed.
> 
> Hopefully this helps someone else.

This was perfect approach/solution for me as well. I fed this to copilot and it drafted a nice plan to do it in my app. Thanks
