### ISSUE TITLE
Global Filtering not working in 8.7.4

### ISSUE THREAD

**Issue by ZeroPie** [TanStack/table#4623]
### Describe the bug

Global filter functionality is not working.

### Your minimal, reproducible example

https://codesandbox.io/s/immutable-morning-pwg0l8?file=/src/App.tsx

### Steps to reproduce

1. Go to: https://codesandbox.io/s/immutable-morning-pwg0l8?file=/src/App.tsx
2. Write in the input

### Expected behavior

1. The Results are affected by the filter value

### How often does this bug happen?

Every time

### Screenshots or Videos

https://codesandbox.io/s/immutable-morning-pwg0l8?file=/src/App.tsx

### Platform

All

### react-table version

8.7.4

### Additional context

8.7.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Moggers** [comment]
I found I had to import `getFilteredRowModel` and pass it into the table options- I think that is meant to be the default one, and its failing to initialize.

**Comment by KevinVandy** [comment]
Yeah, this just had a missing filter row model
