### ISSUE TITLE
Fix typescript compilation errors

### ISSUE THREAD

**Issue by Drezir** [TanStack/table#4660]
### Describe the bug

node_modules/@tanstack/table-core/src/features/Grouping.ts:173:29 - error TS7030: Not all code paths return a value.

173       getAutoAggregationFn: () => {
                                ~~~~~~~

node_modules/@tanstack/table-core/src/features/RowSelection.ts:462:12 - error TS7030: Not all code paths return a value.

462       .map(row => {
               ~~~~~~~~

### Your minimal, reproducible example

No example

### Steps to reproduce

Just install it and run tsc

### Expected behavior

No errors

### How often does this bug happen?

None

### Platform

Linux

### react-table version

8.7.6

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by ITsvetkoFF** [comment]
Looks like I have 2 more errors. Also v8.7.6 
(making internal ts ui library project)

```
> tsc --noEmit               
node_modules/@tanstack/table-core/src/columnHelper.ts:9:31 - error TS6133: 'RequiredKeys' is declared but its value is never read.

9 import { DeepKeys, DeepValue, RequiredKeys } from './utils'
                                ~~~~~~~~~~~~

node_modules/@tanstack/table-core/src/features/Grouping.ts:245:11 - error TS6133: 'getRenderValue' is declared but its value is never read.

245     const getRenderValue = () =>
              ~~~~~~~~~~~~~~
```

**Comment by jackmcpickle** [comment]
Hit the same issue. As our `tsconfig.json` is very strict and couldnt add to tsconfig include/exclude list a we import directly into our own `.env.d.ts` file. Based on the docs. https://tanstack.com/table/v8/docs/api/core/column-def#meta

**Fixed** by using the one package import across the project. In my case `@tanstack/react-table` everywhere.

In my project  I was importing state types like `import {SortingState} from '@tanstack/table-core/src/features/Sorting';`

By changing to be consistent across the project `import {SortingState} from '@tanstack/react-table';`

and then updated the env.d.ts file to extend the ColumnMeta with the same package. 

```ts
// root env.d.ts

import { RowData } from '@tanstack/react-table';

declare module '@tanstack/react-table' {
    interface ColumnMeta<TData extends RowData, TValue> {
        className?: string,
    }
}
```
