### ISSUE TITLE
Documentation Site Overlap Issue

### ISSUE THREAD

**Issue by khill-fbmc** [TanStack/table#4664]
### Describe the bug

It looks like the subscribe section slides over the menu on scroll 

### Your minimal, reproducible example

https://react-table-v7.tanstack.com/docs/quick-start

### Steps to reproduce

Visit https://react-table-v7.tanstack.com/docs/quick-start and scroll down

### Expected behavior

The text to not overlap

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/107003416/212955584-d67c4fc4-786c-4c86-b9fd-1245b98be723.png)

### Platform

W11, Firefox

### react-table version

7

### TypeScript version

4.9

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piyushjha0409** [comment]
I would like to work on this issue! seems like z-index problem in styling.
