### ISSUE TITLE
Import trace for requested module:(useState)

### ISSUE THREAD

**Issue by Codefreak69** [TanStack/table#4674]
### Describe the bug

```
Import trace for requested module:
./node_modules/@tanstack/react-table/build/lib/index.mjs
./src/app/(site)/page.tsx

```
_ModuleDependencyError: export 'useState' (imported as 'React') was not found in 'react' (possible exports: Children, Fragment, Profiler, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cache, cloneElement, createElement, createRef, createServerContext, forwardRef, isValidElement, lazy, memo, startTransition, use, useCallback, useContext, useDebugValue, useId, useMemo, version)_

Recently i was working with Nextjs 13.1 project and installed React Table but i can't fix this error , It keeps saying Import Trace not found for useState, i have checked the tanstack folder in node modules and i couldn't find the export there also

### Your minimal, reproducible example

No link

### Steps to reproduce

1) just install the package in Nextjs 13.1 and try to create a Simple Data table ,this error will popUP

### Expected behavior

Table should be rendered but instead getting this error

### How often does this bug happen?

None

### Platform

Linux

### react-table version

8.7.6

### TypeScript version

4.9.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Codefreak69** [comment]
![image](https://user-images.githubusercontent.com/75885286/214296236-5e071a8c-56b6-476d-9c8d-205fb42f5e8d.png)

**Comment by AlexandreKueny** [comment]
I have a slightly different error message, but it looks like the same issue.
Im using next 13.4.2 and react-table 8.9.1
<img width="1026" alt="image" src="https://github.com/TanStack/table/assets/4974911/0594e181-a48a-4a0f-b027-bbbafe07b197">

**Comment by phillipkregg** [comment]
Having same problem with:

"next": "^13.2.3",
"@tanstack/react-table": "^8.7.9",


Here is the error:

![image](https://github.com/TanStack/table/assets/1066044/9282185a-2d1f-4d0f-813e-984236761fc4)


It's worth noting that I'm using this exact same version of the table with Next "12.0.7" and not having this problem.

Which makes me wonder if it has something to do with either the new "app" directory (which I'm using).

**Comment by KevinVandy** [comment]
This just has to do with trying to use `useReactTable` as a server component, which is obviously not supported.
