### ISSUE TITLE
It's not possible to compile the project with a table because of ts errors

### ISSUE THREAD

**Issue by Travellerme** [TanStack/table#4688]
### Describe the bug

![image](https://user-images.githubusercontent.com/3765355/215465308-6b1e5ddd-23bd-43b7-9bb6-abf4c554fb35.png)
The error is happening here: 
node_modules/@tanstack/table-core/src/utils/filterRowsUtils.ts:112:19

### Your minimal, reproducible example

N/A

### Steps to reproduce

Running a build with typescript triggers such errors to be shown

### Expected behavior

Is this possible to define rows as follows:
```    const rows: Row<TData>[] = []```  
?
It's urgent for us, as we're going to use the table in production 
Thank you 

### How often does this bug happen?

None

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/3765355/215465308-6b1e5ddd-23bd-43b7-9bb6-abf4c554fb35.png)

### Platform

ANY

### react-table version

8.7.8

### TypeScript version

4.8.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Travellerme** [comment]
I've created a PR for it https://github.com/TanStack/table/pull/4689

**Comment by Travellerme** [comment]
It's not I guess.
At least ```tsc --noEmit --showConfig```
returns nothing related to node_modules:
```

{
    "compilerOptions": {
        "baseUrl": "./src",
        "paths": {
            "components/*": [
                "./components/*"
            ],
            "constants/*": [
                "./constants/*"
            ],
            "config/*": [
                "./config/*"
            ],
            "contexts/*": [
                "./contexts/*"
            ],
            "lib": [
                "./lib"
            ],
            "services": [
                "./services"
            ],
            "ui": [
                "./ui"
            ]
        },
        "target": "es5",
        "lib": [
            "dom",
            "dom.iterable",
            "esnext"
        ],
        "allowJs": true,
        "skipLibCheck": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "noFallthroughCasesInSwitch": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "noEmit": true,
        "jsx": "react-jsx",
        "noImplicitAny": false
    },
    "files": [
        ...  // I've checked and there are no files from node_modules here

    ],
    "include": [
        "src",
        "types"
    ]
}

```

My assumption is that it checks imports and somehow sees ts errors in dependent packages. But I might be wrong.
Anyway if I may suggest, having a strict type is better than having "never" type

**Comment by Travellerme** [comment]
Most probably I found an explanation for why it fails even if node_modules are not included in TS checking
There is a tool https://www.npmjs.com/package/loose-ts-check that I have to use in order to skip this error in Tanstack/table, and it's said: 
```
Why not exclude in tsconfig.json
The exclude option in tsconfig.json only tells tsc to not start type-checking from those files. If some already type-checked file imports a file listed in the exclude, it will still be type-checked.

Thus, it does not suit this use case.
```
So most probably my assumption was correct. The file which is using the tanstack table library should be checked by TS. And as it has a dependency on tanstack - it causes a failure

**Comment by KevinVandy** [comment]
Most if not all projects (at least that I have ever worked on) include this in their tsconfig

```json
"exclude": [
    "node_modules"
  ]
```

Different projects and libraries can have very different ts configurations. 

Also, this is probably caused by you are importing from `src` instead of importing directly from `@tanstack/react-table`. Your own project should only import the transpiled js that way, instead of the source typescript files.

**Comment by Travellerme** [comment]
I tried to use exclude option as well but had no luck, unfortunately.
