### ISSUE TITLE
Minor typo in docs for column accessors

### ISSUE THREAD

**Issue by GabriFila** [TanStack/table#4717]
### Describe the bug

Hi, I possibly found a minor typo in the docs.

[Here](https://tanstack.com/table/v8/docs/guide/column-defs#creating-accessor-columns) shouldn't it be "There are `3` ways to do this" instead of "There are `2` ways to do this"

### Your minimal, reproducible example

https://tanstack.com/table/v8/docs/guide/column-defs#creating-accessor-columns

### Steps to reproduce

Go [here](https://tanstack.com/table/v8/docs/guide/column-defs#creating-accessor-columns)

### Expected behavior

There should be a 3 instead of a 2

### How often does this bug happen?

Every time

### Platform

It should be independent since it is in md [here](https://github.com/TanStack/table/blob/main/docs/guide/column-defs.md#creating-accessor-columns) 

### react-table version

latest

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by MohitBansal321** [comment]
would you assign this issue to me @GabriFila
