### ISSUE TITLE
Table v8 expanding - incorrect state of parent checkbox when selecting subrows

### ISSUE THREAD

**Issue by aleksygoroszko** [TanStack/table#4720]
### Describe the bug

When selecting subrows the parent checkbox does not get correct state

### Your minimal, reproducible example

https://codesandbox.io/s/github/tanstack/table/tree/main/examples/react/expanding

### Steps to reproduce

The bug can be reproduced in official demo: 
https://codesandbox.io/s/github/tanstack/table/tree/main/examples/react/expanding

How to reproduce:

1. Expand the row 
![1](https://user-images.githubusercontent.com/1842300/220273738-a39c9679-7b9c-4b8a-98e5-cce41953be47.PNG)

2. Begin selecting subrows, the parent checkbox shows partial selection, which is correct
![2](https://user-images.githubusercontent.com/1842300/220273741-1f34c550-5a8e-4aa7-a8ca-cbd595eafb8e.PNG)

3. When selecting last subrow, the parent row is set as **unchecked**, but should be **checked** to mark that all subrows are selected. 
![3](https://user-images.githubusercontent.com/1842300/220273744-54783d83-2a2c-47ff-8b2f-a39ce0ae3862.PNG)

Selecting/unselecting parent checkox selects/unselects all subrows correctly

### Expected behavior

Selecting all subrows must mark parent checkbox as checked

### How often does this bug happen?

Every time

### Platform

Windows, Chrome 110.0.5481.104

### react-table version

8.7.9

### TypeScript version

-

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by aleksygoroszko** [comment]
I haven't considered that maybe the demo itself could be not correct. It looks that it is it's definition of IndeterminateCheckbox doesn't handle more depths so it should be added **|| row.getIsAllSubRowsSelected()** to mark correct checked state:

`<IndeterminateCheckbox
{...{
checked: row.getIsSelected() || row.getIsAllSubRowsSelected(),
indeterminate: row.getIsSomeSelected(),
onChange: row.getToggleSelectedHandler(),
}}
/>`

**Comment by VincEnterprise** [comment]
I still have trouble with this exact same problem, currently trying to implement this on a Vue project but it's not working. 

Here's my attempt:

https://codesandbox.io/p/sandbox/amazing-panna-ksdmvb?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A13%2C%22endLineNumber%22%3A89%2C%22startColumn%22%3A13%2C%22startLineNumber%22%3A89%7D%5D

Everything seems to work except the sub title checkbox. 

Repro: 

1. Select both 'nested title' and 'nested title 2' checkboxes
2. uncheck the parent sub title checkbox
3. Child checkboxes aren't unchecked properly

**Comment by VincEnterprise** [comment]
@aleksygoroszko  When I apply your changes to the codesandbox demo, the checkboxes still don't work properly. 

Maybe this issue needs to be re-opened?

**Comment by wkeese** [comment]
Yes, please reopen this.   At the very least, https://tanstack.com/table/latest/docs/framework/react/examples/expanding should be updated to work correctly, but as explained in #4878 this seems like a problem with the library itself rather than a problem with the demo.
