### ISSUE TITLE
Docs: Row Dnd Example code not working

### ISSUE THREAD

**Issue by therealgabryx** [TanStack/table#4730]
### Describe the bug

The docs page "[React Example: Row Dnd](https://tanstack.com/table/v8/docs/examples/react/row-dnd)" isn't working properly.

### Your minimal, reproducible example

https://tanstack.com/table/v8/docs/examples/react/row-dnd

### Steps to reproduce

1. Go to the docs and visit the React Table Row Dnd Example page.
2. 502 Bad Gateway error shows up in the provided example code.
3. .-.

### Expected behavior

As a user, I expected to be trying the example to implement Row Dnd into my app, because there isn't much info about how it works anywhere else... so it's crucial that at least the given example code works. 

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="1680" alt="Screenshot 2023-02-25 at 12 16 01" src="https://user-images.githubusercontent.com/35427308/221354096-7b12de0c-f389-4037-96ee-4a38df7b414e.png">

### Platform

Google Chrome, MacBook Pro M1 2020, macOS Ventura

### react-table version

v8.7.9

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by IanVS** [comment]
There's no 502 anymore, but the example doesn't work (dragging has no effect).
