### ISSUE TITLE
Attempted import error: 'useState' is not exported from 'react'

### ISSUE THREAD

**Issue by sek-consulting** [TanStack/table#4731]
### Describe the bug

I tried to build a nextjs application that uses the tanstack v8 react-table component but I came across the following error:

Failed to compile

./node_modules/@tanstack/react-table/build/lib/index.mjs
Attempted import error: 'useState' is not exported from 'react' (imported as 'React').

This error occurred during the build process and can only be dismissed by fixing the error.

Now I'm not sure if this is caused by next, node or the component itself.

### Your minimal, reproducible example

https://stackblitz.com/github/sek-consulting/tanstack-usestate-error-mre

### Steps to reproduce

open the stackblitz link or use the github repo directly:
https://github.com/sek-consulting/tanstack-usestate-error-mre

### Expected behavior

Since this is just a copy/paste of the Basic Example (with stripped down data/columns) I expect it to like similar to this:
https://tanstack.com/table/v8/docs/examples/react/basic

### How often does this bug happen?

Every time

### Screenshots or Videos

![screen](https://user-images.githubusercontent.com/8871906/221535077-ed19949b-3826-424d-a65e-61bb3347b691.JPG)

### Platform

Windows
Firefox
Node 18.14

### react-table version

^8.7.9

### TypeScript version

4.9.5

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by sek-consulting** [comment]
I played around with another project of mine that has the tanstack-table working just fine and step by step tried it to move it the above configuration.

And the error starts to appear when I move from the old pages setup to the new app directory feature.

**Comment by puntogris** [comment]
Hi! did you found out a way to fix it? I'm having the same issue

**Comment by sek-consulting** [comment]
Unfortunately not.
I set my project on hold until I get some more info on how to fix it here.

In the meantime I switched to t3-stack for a bigger project which doesn't use the app folder and therefore doesn't break the table.

**Comment by dschlabach** [comment]
Also experiencing this and unsure how to resolve. Next 13.2.4 and Tanstack Table 8.7.6

**Comment by dschlabach** [comment]
@sek-consulting btw, I was able to fix your error:

You're trying to use Tanstack Table in a server component, which doesn't have access to hooks like useState. In order to fix this, you need to let Next know that you want a Client component. You can do this by adding `'use client'` to the top of page.tsx.

The trouble for me comes when I create a separate Client component `<Table />` that renders the table, then import that into a server component. This should work according to [Next's docs](https://beta.nextjs.org/docs/rendering/server-and-client-components) but I can't seem to get it working.

The error I get is:

```./node_modules/@tanstack/react-table/build/lib/index.mjs
Attempted import error: 'useState' is not exported from 'react' (imported as 'React').```

**Comment by asomethings** [comment]
It seems like `createColumnHelper` needs to be on the client side component. Make sure you have `"use client"` on top of any files that uses tanstack tabl

**Comment by sek-consulting** [comment]
thanks to everyone for helping me out with this! ❤️ 

I now have my table.tsx in a client component and a seperat client component for all my needed tables to wrap the columnHandler stuff and the typing.
Then I can fetch the data in a server component and display it in the client component.

Still need to get used to the new layout and usage of the app directory 😆

**Comment by Fred-O-Nyarko** [comment]
I solved this issue by creating a new function which returns the `createColumnHelper` function. This new function resided in a component that had a `"use client"` declaration.

```JSX
export function _createColumnHelper<
  TData extends unknown,
>(): ColumnHelper<TData> {
  return createColumnHelper();
}
```
