### ISSUE TITLE
Row DnD example = 502 Bad Gateway

### ISSUE THREAD

**Issue by kristianHaahr** [TanStack/table#4736]
### Describe the bug

<img width="420" alt="image" src="https://user-images.githubusercontent.com/58253949/221773022-6d359943-ffb4-4640-88d6-4e208a2fc900.png">

### Your minimal, reproducible example

Code sandbox

### Steps to reproduce

go to page: https://tanstack.com/table/v8/docs/examples/react/row-dnd

### Expected behavior

502 bad gateway response

### How often does this bug happen?

None

### Platform

Windows 11, edge browser. all up to date.

22H2 Build 22621.1265

### react-table version

latest

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by theMattCode** [comment]
Duplicates #4730
