### ISSUE TITLE
Problem with eslint sort-imports rule

### ISSUE THREAD

**Issue by dzienisz** [TanStack/table#4799]
### Describe the bug

Hey I found this bug with `sort-imports` rule in `eslint`

I made an `eslint` bug report but I think that it could be also handled by this repo

https://github.com/eslint/eslint/issues/17062

What do you think?

<img width="756" alt="Screenshot 2023-04-05 at 14 35 14" src="https://user-images.githubusercontent.com/3521624/230082632-f88a3e88-7554-4a24-92af-054b85528c29.png">

### Your minimal, reproducible example

https://github.com/eslint/eslint/issues/17062

### Steps to reproduce

Described here: https://github.com/eslint/eslint/issues/17062

### Expected behavior

there is no error and imports are properly sorted

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="756" alt="Screenshot 2023-04-05 at 14 35 14" src="https://user-images.githubusercontent.com/3521624/230082883-5ff6ebde-d663-4710-a3a3-367a1b853685.png">

### Platform

https://github.com/eslint/eslint/issues/17062

### react-table version

v8.7.9

### TypeScript version

v4.9.5

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by talatkuyuk** [comment]
This is not related with the `@tanstack/table`, which is purely related with `eslint`. And you got the answer [here](https://github.com/eslint/eslint/issues/17062#issuecomment-1497637309).
