### ISSUE TITLE
table.setPageCount is not updating pageCount

### ISSUE THREAD

**Issue by lakshmanang** [TanStack/table#4918]
### Describe the bug

table.setPageCount not updating pageCount.

 ```
const table = useReactTable({
    data: dataQuery.data?.rows ?? defaultData,
    columns,
    pageCount:  10,
    state: {
      pagination,
    },
    onPaginationChange: setPagination,
    getCoreRowModel: getCoreRowModel(),
    manualPagination: true,
    // getPaginationRowModel: getPaginationRowModel(), // If only doing manual pagination, you don't need this
    debugTable: true,
  })
React.useEffect(() => {
    console.log("asdfasdf");
    table.setPageCount(20)
  },[])

```

Actual result: 
`
   console.log(table.getPageCount()); // 10
`

Please suggest a way to change pageCount.

### Your minimal, reproducible example

Not available

### Steps to reproduce

1.Set pageCount=10 in `useReactTableOptions`
2. change pageCount somewhere outside by table.setPageCount(20)

### Expected behavior

Expected result:

` 
   console.log(table.getPageCount()); // 20
`

### How often does this bug happen?

None

### Screenshots or Videos

<img width="233" alt="image" src="https://github.com/TanStack/table/assets/104250040/17b52c40-27f6-4906-ad56-2dfcb5ee2b20">
<img width="394" alt="image" src="https://github.com/TanStack/table/assets/104250040/7df631b3-a430-4a92-b22f-6d7721845670">

### Platform

windows 11, Chrome

### react-table version

^8.8.4

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Leo-Xee** [comment]
How about put `pageCount` into `tableOption`?

**Comment by lakshmanang** [comment]
Hi Jangmin,

1. Here we are developing Compound table component. Creating table instance is in TableContext and passing down. PageCount will be calculate(using totalDataCount) inside of PaginationFooter component. So I am in the need of changing PageCount after the tableInstance creation.


***@***.***

2.Another think is, PageCount can be dynamic here. Whenever user request to see the total count we will fetch and so. At the time also I want to use table.setPageCount.


***@***.***


Thanks
Lakshmanan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by chiragparekh** [comment]
I am using vue-table, also facing the same issue, I am not sure is this bug or I have configured incorrectly?

**Comment by eyal-rp** [comment]
Also same issue! just wasted half a day trying to figure out what I'm doing wrong, but I think it's a bug.

In: Pagination.ts
It seems that setPageCount is using setPagination() and updates the count on the PaginationState, 
from the docs it doesn't look like the pageCount is part of the PaginationState, should be updated directly into table.options.pageCount.

Can someone from tanstack team please take a look? 
this is a show stopper bug, and no reply on this thread for over a month.

<img width="487" alt="image" src="https://github.com/TanStack/table/assets/134921616/b543aeb6-865d-4583-808f-810c17bb64b7">


Thank you!! 🙏🙏🙏

**Comment by eyal-rp** [comment]
This is actually a really easy fix..
Replacing in the above function 'setPagination' to 'setOptions' fixes the issue,
I'll open a PR for this.

**Comment by sameckmeier** [comment]
Appreciate everyones work on this! Any timeline on when this PR will get merged? This is a blocking bug for my team and I. Thanks!

**Comment by AndreasMarkopoulos** [comment]
This is an issue I'm still having, do you happen to have any updates on it?

**Comment by dogukanoksuz** [comment]
+1 Having this issue

**Comment by KevinVandy** [comment]
table.setPageCount is actually a deprecated API that does nothing in v8. Just pass in the page count or row count as a table option. This API was supposed to have been removed by the time v8 stable came out, but it was forgotten about.

**Comment by nguyenhuutuong999** [comment]
fixed by using   
get pageCount() {
    return props.totalPages
},
instead of pageCount: props.totalPages
