### ISSUE TITLE
getIsSomeSelected() returns false for selected node's grandparent

### ISSUE THREAD

**Issue by drewbrend** [TanStack/table#4938]
### Describe the bug

When a table has double (or more) nesting, and a child is selected, its direct parent can use `getIsSomeSelected()` to toggle its indeterminate selection state, however its grandparent cannot, it seems to only check the first level of its children.

This becomes more confusing because the table header uses `getIsSomeRowsSelected()`, which works as expected, returning `true` if any row is selected - see screenshot of this state.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/znmfz7

### Steps to reproduce

1. Open the codesandbox link
2. Expand the first double nested node until you get its deepest child
3. Select the deepest child
4. notice its parent's checkbox is marked indeterminate and the table header is marked indeterminate, however the grandparent is not selected

### Expected behavior

I expect all ancestors of a selected row to show indeterminate state

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="314" alt="Screenshot 2023-06-27 at 12 36 37 PM" src="https://github.com/TanStack/table/assets/5375799/90d7c631-a1c7-43fb-8f28-bf410b862fbd">

### Platform

macOS, Chrome (latest)

### react-table version

8.9.3

### TypeScript version

4.9.5

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by msankaran0712** [comment]
Facing the same issue for the table having more than two levels of nested rows

**Comment by drewbrend** [comment]
This is fixed in the latest version (8.11.3), likely earlier but I just noticed and tested it now.

If you open the original code sandbox link, upgrade @tanstack/react-table to latest, and restart the app the problem is fixed.

Thanks to whoever incidentally fixed it!
