### ISSUE TITLE
Column Filtering does not work when using the column accessorFn to manipulate a boolean field.

### ISSUE THREAD

**Issue by changyeamoon** [TanStack/table#4951]
### Describe the bug

When you have a boolean field in your dataset that you feed to the table and you want to filter on that boolean field by changing its value to a String (e.g `!!status ? 'Active' : 'Inactive'`) then when you try to filter on them, it doesn't filter correctly.

I think the reproducible steps give a clearer explanation 

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/accessorkey-filter-q7534z?embed=1&file=%2Fsrc%2Fmain.tsx%3A7%2C10

### Steps to reproduce

**GIVEN**  I  set up data that has a boolean field in it (e.g `status`)
**AND**      I set up the table (using an example from the docs (filter example))
**AND**      I use the accessorFn field on the columnDef to manipulate the boolean (e.g `!!status ? 'Active' : 'Inactive'`)
**AND**      filtering is enabled
**WHEN**   I select the status filter and select 'Active' 
**THEN**    the columns do not filter correctly. You still see some 'Inactive' rows

### Expected behavior

Same as steps to reproduce but with ->

**THEN**    the columns **do** filter correctly. 

### How often does this bug happen?

Every time

### Screenshots or Videos

https://github.com/TanStack/table/assets/30943398/1ab51ec2-cbcc-4586-a474-b85cb48eb83e

### Platform

macOS, Google Chrome latest

### react-table version

8.9.3

### TypeScript version

4.9.5

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by pi-kei** [comment]
The word `active` included in the work `inactive`. By default, filter uses `includesString` (case-insensitive) function. So, when you choose `Active` `Inactive` will not be filtered out. Specify proper `filterFn` value in your columnDef (see https://tanstack.com/table/v8/docs/api/features/filters#filterfn). For example, `equalsStringSensitive`

**Comment by changyeamoon** [comment]
Hey @pi-kei, thanks for the info. I just assumed it would work the same as in v7, but your explanation makes sense, especially since the filter components in the example also handle search.

The filters in my components just provide options, so it seems more logical to change the tables filterFn to `equalsStringSensitive`.
