### ISSUE TITLE
[docs]: react/column-dnd  doesn't work

### ISSUE THREAD

**Issue by vaynevayne** [TanStack/table#4969]
### Describe the bug

<img width="886" alt="image" src="https://github.com/TanStack/table/assets/124666577/0aa5b0d2-69b4-4060-8e87-ab726755081f">

invalid

### Your minimal, reproducible example

https://tanstack.com/table/v8/docs/examples/react/column-dnd

### Steps to reproduce

..

### Expected behavior

..

### How often does this bug happen?

None

### Platform

chrome

### react-table version

v8

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by JaviGF8** [comment]
It doesn't work for me either. I've tried in my code and it doesn't work. The reordering function is working as expected, the state of the variable with the order is ok, but the columns doesn't reorder

**Comment by KevinVandy** [comment]
@lortschi The docs link has not been removed, the entire site just had a URL restructure recently. Just browse the sidebar.

A new column ordering guide has been made: https://tanstack.com/table/v8/docs/guide/column-ordering
And the column DnD example was rewritten with DnD Kit: https://tanstack.com/table/v8/docs/framework/react/examples/column-dnd

I don't know what page you are seeing where the react-dnd bugs still persist? This was all updated last night though, so maybe you're seeing a cached version of the example.
