### ISSUE TITLE
yarnpkg restricted to version 8.9.3

### ISSUE THREAD

**Issue by PargRi01** [TanStack/table#5044]
### Describe the bug

Current release is 8.9.6, but yarn is covering version up to 8.9.3
yarn cache clean done, but problem still exists.

### Your minimal, reproducible example

yarn add @tanstack/react-table@8.9.6

### Steps to reproduce

yarn add @tanstack/react-table@8.9.6

### Expected behavior

As a user I expected version 8.9.6 to be installed, but I am limited to version 8.9.3

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/table/assets/22663867/c4d1fa48-dcdf-4392-a45e-91f77fff3e55)

### Platform

macOs - 12.6.5

### react-table version

latest

### Additional context

https://yarnpkg.com/package?name=%40tanstack%2Freact-table reports 8.9.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
8.9.3 is the latest release for all of the packages except for svelte. 8.9.6 is svelte only. Don't worry about it. Check the npm page for all published versions

**Comment by PargRi01** [comment]
@KevinVandy highlighted its the latest for React atm.
