### ISSUE TITLE
Ts type infer issue on onPaginationChange

### ISSUE THREAD

**Issue by FasalMohammadh** [TanStack/table#5062]
### Describe the bug

![image](https://github.com/TanStack/table/assets/105656186/c02cbd89-aa5e-4a5e-ab12-6ffefe73197c)
![image](https://github.com/TanStack/table/assets/105656186/0e6a7f8f-4646-4a0b-8573-acf765df59b4)

in the onPaginationChange the parameter updaterOrValue Updater<T> does't infer the type correctly

### Steps to reproduce

just define a function to onPaginationChange and try access the variable updaterOrValue

### Platform

Windows

### react-table version

v8.9.3

### TypeScript version

V5.1.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [x] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by headironc** [comment]
How to solve this problem? I want to use this with next useRouter hook
