### ISSUE TITLE
Table Resizing Lags behind Cursor on Drag Start When No Explicit WidthSet

### ISSUE THREAD

**Issue by sslgeorge** [TanStack/table#5073]
### Describe the bug

When an explicit width is not set via `defaultColumn.size` or when the content of a cell becomes larger than `defaultColumn.size` the resizer lags behind the cursor on the initial column resize. This only happens when using table element, when using div (relative or absolute) it seems to work fine.

### Your minimal, reproducible example

[Demo](https://codesandbox.io/p/sandbox/elated-cray-jmckxc?embed=1&file=/src/main.tsx:26,82)

### Steps to reproduce
1. Using the link above, go to the firstName column of the `<table />` containing a cell with the text `tannertannertannertanner`
2. Try to resize the column using the resizer

### Expected behavior

Resizing should happen at the same pace as mouse cursor move

### How often does this bug happen?

Every time

### Platform

ALL

### react-table version

v8.9.10

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Ryanjso** [comment]
Hey @sslgeorge were you able to fix this? I'm running into this issue currently
