### ISSUE TITLE
Expanding Rows rapidly decreasing performance using vue-table

### ISSUE THREAD

**Issue by falkfrentzen** [TanStack/table#5095]
### Describe the bug

I'm currently converting the react-table v8 examples to Vue3 examples. When trying to replicate the "Expanding" example (https://tanstack.com/table/v8/docs/examples/react/expanding), I ran into this issue, showcased here: https://codesandbox.io/p/sandbox/mystifying-herschel-hhzwnn?file=%2Fsrc%2FApp.vue%3A1%2C1 Clicking the "👉" button, changes the expansion model and causes the selected row toggle its expansion. The more often you trigger the expansion model change, the slower "getExpansionRowModel" gets, resulting in increasing lag.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/mystifying-herschel-hhzwnn?file=%2Fsrc%2FApp.vue%3A1%2C1

### Steps to reproduce

Run the CodeSandBox and click any of the "👉" buttons for about 5-10 times. Debug times are shown in the console.

### Expected behavior

The time to process "getExpandedRowModel" should stay consistent, as it does in the React example.

### How often does this bug happen?

Every time

### Screenshots or Videos

![tanstack-vue-table-performance](https://github.com/TanStack/table/assets/19949500/6a272368-4b37-431d-b400-89e23e567671)

### Platform

macOS 13.5.2 M1 Chip

### react-table version

*vue-table v8.10.1

### TypeScript version

5.0.2

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Than-DE** [comment]
For me this happens also for column visibility. I feel like it may have something to do with setting state.

**Comment by falkfrentzen** [comment]
I already suspected that there might be too complex information passed to the "expanded" ref. However, logging the value shows the expected list, as also shown above the table in my codesandbox (<pre>{{ expanded }}</pre>). I would guess there is some sort of unwanted caching going on internally?

**Comment by Than-DE** [comment]
I think I was able to fix the issue. Indeed it was related to the state because we were setting the table state wrongly:

```js
const table = useVueTable({
  get data() {
    return data.value;
  },
  // before
  get state() {
    return {
      expanded: expanded.value
    }
  }
  // after
  state: {
    get expanded() {
      return expanded.value;
    }
  },
// ...
});
```

Found this out through the [sorting example](https://tanstack.com/table/v8/docs/examples/vue/sorting).

**Comment by falkfrentzen** [comment]
Awesome! Thank you very much!

**Comment by p19ky** [comment]
> I think I was able to find the issue. Indeed it was related to the state because we were setting the table state wrongly:
> 
> const table = useVueTable({
>   get data() {
>     return data.value;
>   },
>   // before
>   get state() {
>     return {
>       expanded: expanded.value
>     }
>   }
>   // after
>   state: {
>     get expanded() {
>       return expanded.value;
>     }
>   },
> // ...
> });
> Found this out through the [sorting example](https://tanstack.com/table/v8/docs/examples/vue/sorting).

You are my hero.
