### ISSUE TITLE
Subrows sorting order is broken

### ISSUE THREAD

**Issue by denysgoloborodko** [TanStack/table#5113]
### Describe the bug

If you enable SortedRowModel, but turn off sorting for the specific column in colDef (enableSorting: false) - subrows for this row will have different order. For the first render - the order will be the same as order in subRows array. Afterwards, the order changes for some reason. Even though ids and indexes indicates the expecting order

### Your minimal, reproducible example

 https://codesandbox.io/p/sandbox/react-table-subrows-sorting-issue-n26khp

### Steps to reproduce

1. Expand any row
2. Memoize an order of items
3. Toggle sorting for some column and turn sorting off
4. Check the order of items again, it has been changed

### Expected behavior

The order of subRows should not be touched when sorting is off for this column

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="503" alt="image" src="https://github.com/TanStack/table/assets/107812611/e46376e2-f0ce-4216-99d0-2cf12e5b87f9">

### Platform

macOS

### react-table version

8.9.3

### TypeScript version

4.5.0

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by itsmejoeeey** [comment]
Seems like a duplicate of #5081 and #5103.

My fix for this is now available in [v8.10.4](https://github.com/TanStack/table/releases/tag/v8.10.4)

**Comment by denysgoloborodko** [comment]
Yes, it's fixed, thank you!
