### ISSUE TITLE
Size property not working

### ISSUE THREAD

**Issue by anduscheung** [TanStack/table#5115]
### Describe the bug

I am using v8 and unable to change the width of the column of the most simple example according to the document.

https://tanstack.com/table/v8/docs/examples/react/basic

For this example, I opened the sandbox and changed the size of the first column to 500, as below:

```
columnHelper.accessor('firstName', {
  cell: info => info.getValue(),
  footer: info => info.column.id,
  size: 500,
  minSize: 500
}),
```
However the width of the first column remain unchanged

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/strange-pine-wtqhtg?embed=1&file=%2Fsrc%2Fmain.tsx%3A62%2C15

### Steps to reproduce

Add size property to the first column of basic example one

### Expected behavior

Size property should be respected

### How often does this bug happen?

Every time

### Platform

Chrome

### react-table version

8.10.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by aoloo** [comment]
Seeing this as well

**Comment by sergor5** [comment]
@anduscheung , @aoloo 

You're probably missing the part where you set the width by yourself in the styles prop:
```jsx
<td
  style={{
    width: cell.column.getSize(),
  }}
>
    ...
</td>
```
It's shown here: [Tanstack Column Sizing](https://tanstack.com/table/v8/docs/examples/react/column-sizing)

**Comment by anduscheung** [comment]
Thanks, I thought it is an automatic property 👍

**Comment by dawalberto** [comment]
Someone know a workaround? still doesn't works

**Comment by KevinVandy** [comment]
> Someone know a workaround? still doesn't works

Why do you need "a workaround"? You probably have just not hooked up the column size APIs to your CSS properly. Follow the official examples and you should be fine.

**Comment by dawalberto** [comment]
@KevinVandy this is my column helper:

```js
...
columnHelper.accessor('ref', {
	id: 'ref',
	cell: (info) => <span className='whitespace-nowrap'>{info.renderValue()}</span>,
	size: 300,
	header: 'ID',
	footer: (info) => info.column.id,
}),
...
```
And this my table:
```jsx
...
<td
	key={cell.id}
	style={{ width: cell.column.getSize() }}
...
```

Am I missing something?

**Comment by KevinVandy** [comment]
Just also apply the width in th header elements

**Comment by dawalberto** [comment]
@KevinVandy  I already did but still not working 🤷‍♂️

```jsx
...
<tr key={headerGroup.id}>
	{headerGroup.headers.map((header) => (
		<th
			key={header.id}
			colSpan={header.colSpan}
			style={{ position: 'relative', width: header.getSize() }}
		>
...
```

**Comment by KevinVandy** [comment]
Ok. Share a full sandbox showing it not working and we can go from there.

**Comment by birddigital** [comment]
@KevinVandy @dawalberto any fix to this?

**Comment by birddigital** [comment]
I'm using shadcn-ui v0.8.0 and in the TableHeader components I used header.column.columnDef.meta?.width
```typescript
<TableHeader>
            {table.getHeaderGroups().map((headerGroup) => (
              <TableRow key={headerGroup.id}>
                {headerGroup.headers.map((header) => {
                  return (
                    <TableHead key={header.id} style={{ width: header.column.columnDef.meta?.width }}>
                      {header.isPlaceholder ? null : flexRender(header.column.columnDef.header, header.getContext())}
                    </TableHead>
                  );
                })}
              </TableRow>
            ))}
          </TableHeader>
<TableHeader>
            {table.getHeaderGroups().map((headerGroup) => (
              <TableRow key={headerGroup.id}>
                {headerGroup.headers.map((header) => {
                  return (
                    <TableHead key={header.id} style={{ width: header.column.columnDef.meta?.width }}>
                      {header.isPlaceholder ? null : flexRender(header.column.columnDef.header, header.getContext())}
                    </TableHead>
                  );
                })}
              </TableRow>
            ))}
          </TableHeader>

``` 

Then in my column definition i used the metadata object with the width value. Not sure if this is proper but it worked. 
```typescript
{
    accessorKey: 'isResold',
    meta: {
      width: 72,
    },
    header: () => {
      return <div className="flex justify-center">Resold</div>;
    },
    cell: ({ row }) => {
      switch (row.original.isResold) {
        case true:
          return (
            <div className="flex justify-center items-center ">
              <CheckCircledIcon className="w-4 h-4 text-green-500" />
            </div>
          );
        case false:
          return (
            <div className="flex justify-center items-center ">
              <CrossCircledIcon className="w-4 h-4 text-slate-500" />
            </div>
          );
      }
    },
  }, 
``` 
Hopefully this helps. 

just using size, maxSize, and minSize in the column definitions didn't work. 🤷‍♂️

**Comment by mdaffan01** [comment]
Is there an auto-fit column property? Don't want to limit Table columns to a particular width, want to expand columns based on content. 
I tried size: 'auto' against all columns, doesn't work.
Tried some CSS workarounds(whitespace, etc), works but I lose the resize functionality 
Thanks in advance.

**Comment by mdaffan01** [comment]
@KevinVandy

**Comment by KevinVandy** [comment]
> Is there an auto-fit column property? Don't want to limit Table columns to a particular width, want to expand columns based on content. 
> I tried size: 'auto' against all columns, doesn't work.
> Tried some CSS workarounds(whitespace, etc), works but I lose the resize functionality 
> Thanks in advance.

Just don't apply a width at all in your styles if you want auto fit (assuming semantic table elements). The size property is for specifying an exact size.

**Comment by Oize** [comment]
Fox example, [here](https://codesandbox.io/p/devbox/tanstack-table-sizing-43svkv?file=%2Fsrc%2Fmain.tsx) size don't do anything.

**Comment by Oize** [comment]
For example, [here](https://codesandbox.io/p/devbox/tanstack-table-sizing-43svkv?file=%2Fsrc%2Fmain.tsx) size don't do anything.

**Comment by songexile** [comment]
I am using shadcn with Tanstack table and solved my issue by adding a defaultColumn prop to give columns a size.
![tanstack](https://github.com/TanStack/table/assets/26337237/afbd09cc-bdf8-44ac-b757-3dbbbebd225f)

I also needed to change the CSS in TableHead to use width : header.getSize()
![image](https://github.com/TanStack/table/assets/26337237/b4a036e0-f7e2-40c0-9798-74e5f796dfa5)

Hope it helps someone if they are using shadcn with TanStack table. :)

**Comment by Sylar-A** [comment]
I'm using tanstack table in shadcn/ui. Columns sizing didn't work until i add
1.
``` 
 <table // <Table/> component in shadcn
    {...{
      style: {
        width: table.getCenterTotalSize()
      }
    }}
  >
```
2.
```
<td // <TableCell/> component in shadcn
  style={{
    width: cell.column.getSize()
  }}
>
```
3.
```
size: 100, // in ColumnDef
```

**Comment by rgorai-cc** [comment]
> I'm using tanstack table in shadcn/ui. Columns sizing didn't work until i add 1.
> 
> ```
>  <table // <Table/> component in shadcn
>     {...{
>       style: {
>         width: table.getCenterTotalSize()
>       }
>     }}
>   >
> ```

This was the missing piece! Somehow the table was overriding the cell widths but this fixed it

**Comment by nerixim** [comment]
> I'm using tanstack table in shadcn/ui. Columns sizing didn't work until i add 1.
> 
> ```
>  <table // <Table/> component in shadcn
>     {...{
>       style: {
>         width: table.getCenterTotalSize()
>       }
>     }}
>   >
> ```
> 
> 
> ```
> <td // <TableCell/> component in shadcn
>   style={{
>     width: cell.column.getSize()
>   }}
> >
> ```
> 
> 
> ```
> size: 100, // in ColumnDef
> ```

Worked for Chakra UI too.

**Comment by MDziurakh** [comment]
```
columnHelper.accessor('firstName', {
  cell: info => info.getValue(),
  footer: info => info.column.id,
  size: 500,
  maxSize: 700, // how about this line?
}), 

```
every answer here is working with size, but not with **maxSize**. Have someone any workaround with this?

**Comment by KevinVandy** [comment]
The issues that most seem to run into here is that many people assume that TanStack Table will hook up the width CSS for you. It doesn't! You need to set the styles on your `<table>`, `<th>`, and/or `<th>` elements. The ShadCn components don't do this out of the box.

**Comment by Raphaww** [comment]
What if I just want to add width to one column? 
```
[
   {
      ...
      accessorKey: 'id',
      width: 75,
   },
   {
      ...
      accessorKey: 'color',
   },
   ...
]
```
the `getSize` function returns the default (150) in every other column
```
<th style=`75px`>...</th>
<th style=`150px`>...</th>
```
and **I want them to remain unset**

**Comment by MDziurakh** [comment]
@Raphaww, how about this implementation?

`width: header.getSize() !== 150 ? header.getSize() : undefined
`

![image](https://github.com/TanStack/table/assets/103488662/6cbf4c53-0d6b-4c7c-b753-8eaa2ead0423)

**Comment by Raphaww** [comment]
Thanks, but what if in other scenario I need to set a 150px size to a column, then it would be ignored.

I believe there should be a **different attribute** like `defaultWidth` or something, then I could decide if use it or not. For now I ended up doing something similar to your response but defining default width to a size equals to de minSize +1

```
const minSize = 50
useReactTable({ ..., defaultColumn: {
   size: minSize + 1,
   minSize,
}})

<th
{...(header.getSize() !== (minSize + 1) && { style: { width: `${header.getSize()}px` } })}
/>
```
That way, if someone sets a size of 51 it will be ignored but the default being 50 then there should be not much of a difference. I know it is a poor implementation but can't find another way

**Comment by TheeKia** [comment]
None of the above fixed it for me and I realized I have to set `table-layout: fixed;` for my table. Everything is working now 👌

**Comment by fathulfahmy** [comment]
As mentioned by @TheeKia , for those who are using TanStack Table + ShadCN + Tailwind, `table-fixed` in `<Table>` component solved the issue.

```json
"@tanstack/react-table": "^8.21.3",
"shadcn": "^4.6.0",
"tailwindcss": "^4.2.4",
```

```typescript
"use client"

import {
  type Table as TableType,
  flexRender,
} from "@tanstack/react-table"


import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"

interface DataTableProps<TData, TValue> {
  table: TableType<TData>
}

export function DataTable<TData, TValue>({
  table
}: DataTableProps<TData, TValue>) {
  return (
    <div className="overflow-hidden rounded-md border">
      <Table className="table-fixed">
        <TableHeader>
          {table.getHeaderGroups().map((headerGroup) => (
            <TableRow key={headerGroup.id}>
              {headerGroup.headers.map((header) => {
                return (
                  <TableHead key={header.id} style={{width: header.column.getSize()}}>
                    {header.isPlaceholder
                      ? null
                      : flexRender(
                          header.column.columnDef.header,
                          header.getContext()
                        )}
                  </TableHead>
                )
              })}
            </TableRow>
          ))}
        </TableHeader>
        <TableBody>
          {table.getRowModel().rows?.length ? (
            table.getRowModel().rows.map((row) => (
              <TableRow
                key={row.id}
                data-state={row.getIsSelected() && "selected"}
              >
                {row.getVisibleCells().map((cell) => (
                  <TableCell key={cell.id} style={{width: cell.column.getSize()}}>
                    <div className="whitespace-normal break-all">
                      {flexRender(cell.column.columnDef.cell, cell.getContext())}
                    </div>
                  </TableCell>
                ))}
              </TableRow>
            ))
          ) : (
            <TableRow>
              <TableCell colSpan={table.getAllColumns().length} className="h-24 text-center">
                No results.
              </TableCell>
            </TableRow>
          )}
        </TableBody>
      </Table>
    </div>
  )
}
```

```typescript
export const columns: ColumnDef<Agent>[] = [
  {
    id: "select",
    header: ({ table }) => (
      <Checkbox
        checked={table.getIsAllPageRowsSelected()}
        onCheckedChange={(value) => table.toggleAllPageRowsSelected(!!value)}
        aria-label="Select all"
      />
    ),
    cell: ({ row }) => (
      <Checkbox
        checked={row.getIsSelected()}
        onCheckedChange={(value) => row.toggleSelected(!!value)}
        aria-label="Select row"
      />
    ),
    enableSorting: false,
    enableHiding: false,
    size: 30,
  },
  {
    accessorKey: "created_at",
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Created at" />
    ),
    cell: ({ row }) => formatDatetime(row.original.created_at ?? ""),
  },
  {
    accessorKey: "updated_at",
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Updated at" />
    ),
    cell: ({ row }) => formatDatetime(row.original.updated_at ?? ""),
  },
  {
    id: "actions",
    cell: ({ row }) => {
      const _agent = row.original

      return (
        <DropdownMenu>
          <DropdownMenuTrigger>
            <Button variant="ghost" className="h-8 w-8 p-0">
              <span className="sr-only">Open menu</span>
              <MoreHorizontal className="h-4 w-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuGroup>
              <DropdownMenuLabel>Actions</DropdownMenuLabel>
              <DropdownMenuItem>View</DropdownMenuItem>
              <DropdownMenuItem>Edit</DropdownMenuItem>
            </DropdownMenuGroup>
          </DropdownMenuContent>
        </DropdownMenu>
      )
    },
    size: 30,
  },
]

```
