### ISSUE TITLE
toggleSelected produce error when apply on filtered out elements

### ISSUE THREAD

**Issue by More4ever** [TanStack/table#5119]
### Describe the bug

Bug is pretty similar to this one [#2601](https://github.com/TanStack/table/issues/2601)

**Issue:** `toggleSelected` work with `mutateRowIsSelected -> getRow -> getRowModel` method response instead of `getCoreRowModel`

**If it is expected behaviour:** Could you please add notice about this to documentation?

### Your minimal, reproducible example

[Code sandbox](https://codesandbox.io/s/react-table-editable-example-with-filter-forked-lxrw54?file=/src/App.js)

### Steps to reproduce

- render table
- filter out element 
- select element programmatically 

### Expected behavior

Element added to selected list without errors

### How often does this bug happen?

Every time

### Platform

macOs
Chrome, Version 117.0.5938.149 (Official Build) (x86_64)

### react-table version

8.10.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by More4ever** [comment]
Small update: error can't be catched with `try...catch`, which produces huge head ache

**Comment by pedroarm** [comment]
The same error here!

**Comment by More4ever** [comment]
Fixed in [8.11.2](https://github.com/TanStack/table/releases/tag/v8.11.2)
