### ISSUE TITLE
Allow both column ordering (drag and drop) and resizing

### ISSUE THREAD

**Issue by abhishekgahlot2** [TanStack/table#5128]
### Describe the bug

Hi

When i enable resizing with column ordering only column ordering works with drag and drop can we make it resizeable too. 

How to achieve it.

https://codesandbox.io/p/sandbox/clever-mcnulty-xqfj3l?embed=1&file=%2Fsrc%2Fmain.tsx%3A144%2C34

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/clever-mcnulty-xqfj3l?embed=1&file=%2Fsrc%2Fmain.tsx%3A144%2C34

### Steps to reproduce

https://codesandbox.io/p/sandbox/clever-mcnulty-xqfj3l?embed=1&file=%2Fsrc%2Fmain.tsx%3A144%2C34

### Expected behavior

Both column ordering and resizing should work

### How often does this bug happen?

None

### Platform

Mac OSX, Chrome

### react-table version

latest

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by pinkpigeonltd** [comment]
What was the solution to this in the end? I can't make DnD reordering work at the same time as resizing. I've tried a few things, but the table just slows down to the point of unusability when trying to resize columns.
