### ISSUE TITLE
redefine getRowID to be number, not string

### ISSUE THREAD

**Issue by step2341** [TanStack/table#5151]
### Describe the bug

I've just started attempting to extend our existing data-table to include nesting, for things such as WBS and CBS hierarchical structures. Our current table built on tanstack table 8.10.3 features inline editing which has been working well. 

First I've added the expand capability by reviewing this codesandbox:
https://codesandbox.io/p/sandbox/tanstack-table-example-expanding-jr4nn3?file=%2Fsrc%2Fmain.tsx%3A40%2C16-46%2C31

Subrows expand as desired, but when attempting to inline edit, the wrong row is updated. for example, if i ended the first child of a parent (ie index 0 of that group) the root level index 0 item (ie the first item the table) gets updated.

It seems like there is a local leaf node id that is now confusing the edit function. How would I access the 'flattened row' id?

### Your minimal, reproducible example

unavailable

### Steps to reproduce

attempt to combine inline editing as per tanstack demos and expanding/tree capabilities. 

### Expected behavior

particular leaf node required to be edited is edited, instead of the parent node id corresponding to that leaf node id. 

### How often does this bug happen?

None

### Platform

Windows

### react-table version

8.10.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by step2341** [comment]
Upon a bit more investigation, it looks like my issue is coming from the fact that the row index repeats within a parent group, and all my editing functions currently use an index. I can assign a uniqueId via getRowId but this still resolves to a string, even if I pass it a number which again makes it very hard to add/delete/remove rows within the nested array. For example to add a row, I currently do this:

addRow: (rowIndex: number) => {
        const dataBeforeSelectedRow = data.slice(0, rowIndex + 1);
        const dataAfterSelectedRow = data.slice(rowIndex + 1, data.length);
        const columnSchema = table.getAllColumns().map(a => a.columnDef.accessorKey).slice(1,-1)
        const newRow: any = Object.fromEntries(columnSchema.map((x)=>[x, "-"]))
        const setFunc = () => [...dataBeforeSelectedRow, newRow, ...dataAfterSelectedRow];
        setData(setFunc);
        setOriginalData(setFunc);
      },

using a number works well as then i can position the new row below the selected row. else if you have alot of data it ends up on page 100.. but to do this though, i need the rowID to be a number. 

I can do this:

<img width="339" alt="image" src="https://github.com/TanStack/table/assets/147585316/012c78af-c5b7-40d0-b8ff-9bb9f3860055">

 but then get a type error:
<img width="1124" alt="image" src="https://github.com/TanStack/table/assets/147585316/7b188f3e-0756-411a-9dce-da58c5c783f5">

Is it possible to redefine getRowId via table options to be a number?

**Comment by step2341** [comment]
found can fix by creating my own index.

**Comment by KevinVandy** [comment]
Since row ids are often used as keys in objects, they have to be strings. You can always parse your rowIds into numbers during your usage, right?
