### ISSUE TITLE
React Table v8 on Next 14

### ISSUE THREAD

**Issue by eric-sison** [TanStack/table#5165]
### Describe the bug

![Screenshot from 2023-11-16 10-04-45](https://github.com/TanStack/table/assets/65406753/b564f9a6-2197-4526-8e81-ad907ae61375)

I created a `DataTable` client component and used it inside `page.tsx` . When trying to define my columns, I'm getting an error that says, "Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". The error seems to have come from when trying to call `cell: (info) => info.getValue()` .

Steps I tried:
1.) Removed `cell: (info) => info.getValue()` and just allow react-table to render the default cell data.
**Result**: No error, and the table rendered correctly. However, this is not ideal for me, as I want to render a custom component in the table cell.

2.) Modified the code into: 
`cell: async (info) => {"use server"; return info.getValue();}`
**Result**: Just a white blank page, but error still persists when checking the console.
![Screenshot from 2023-11-16 10-03-24](https://github.com/TanStack/table/assets/65406753/c8a40321-4aa3-4ddb-997c-879a76cd6c38)

### Your minimal, reproducible example

Please clone it here: https://github.com/eric-sison/react-table-repro-sample

### Expected behavior

In Next 13, this code works as expected. But when I updated to Next 14, the error now occurs.

### How often does this bug happen?

None

### Platform

OS: Linux Ubuntu 22.04 LTS
Node Version: 20.9.0
React Version: 18
NextJS Version: 14.0.2
Browser: tried on Chrome (`Version 119.0.6045.159 (Official Build) (64-bit)`), Firefox (`119.0.1 (64-bit)`)

### react-table version

8.10.7

### TypeScript version

5

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by karimdaghari** [comment]
To fix this, just add `"use client"` at the top of the component/file in which you're using react table.

This is not exactly a React Table error, nor is it even a Next "issue" per se (technically speaking).

**Comment by eric-sison** [comment]
> To fix this, just add `"use client"` at the top of the component/file in which you're using react table.
> 
> This is not exactly a React Table error, nor is it even a Next "issue" per se (technically speaking).

I have it on my DataTable component. As mentioned above, when running it on Next 13, everything is just fine. But updating it to 14, the error now occurs. You may check my sample repo

**Comment by karimdaghari** [comment]
Wherever you're using non-serializable props (i.e., functions) you should be using client-rendering (`"use client";`) which you're not using here: https://github.com/eric-sison/react-table-repro-sample/blob/main/src/app/page.tsx#L1

**Comment by eric-sison** [comment]
> Wherever you're using non-serializable props (i.e., functions) you should be using client-rendering (`"use client";`) which you're not using here: https://github.com/eric-sison/react-table-repro-sample/blob/main/src/app/page.tsx#L1

My `page.tsx` is meant to be rendered on the server. But my `DataTable` component is on the client.

**Comment by karimdaghari** [comment]
Given that the columns you're passing contain functions in their fields, you have to set `"use client";` where these columns/fns are passed.

**Comment by Jared-Dahlke** [comment]
i'm having this problem too. Next 14 latest.

I have a server component:

```
import React from "react";
import { TanstackPermissionsTable } from "./components/tanstack-table";
import { getColumns } from "./components/getColumns";

export const metadata: Metadata = {
  title: "Roles",
  description: "Verses Genius Core Admin Console",
  metadataBase: new URL("https://genius-db-admin.ama.genius.verses.ai/"),
};

export default async function Home() {
  
 const {roles, rolesPermissions} = await getData()
  

  const columns = getColumns({
    roles,
    rolePermissions: rolesPermissions,
  });

  return (
      <TanstackPermissionsTable
        columns={columns}
      />
  );
}
```


And my getColumns is in a file called `getColumns.tsx`:
```
"use client";
import { DataTableColumnHeader } from "@/app/components/table/data-table-column-header";
import { Permission, Role, RolePermission } from "../types";
import { ColumnDef } from "@tanstack/react-table";
import { Checkbox } from "@versesdev/ui-components/checkbox";
import { updateRolePermissionInDB } from "../actions/actions";

interface GetColumnProps {
  roles: Role[];
  rolePermissions: RolePermission[];
}

export const getColumns = ({
  roles,
  rolePermissions,
}: GetColumnProps) => {
  const hasPermission = (roleId: string, permissionId: string): boolean => {
    const rolePerm = rolePermissions.find((rp) => rp.roleId === roleId);
    return rolePerm?.permissions.includes(permissionId) || false;
  };

  const isDisabled = (roleId: string): boolean => {
    const disabled_roles = [
      "swid:entity:AdminUserRole00000000",
      "swid:entity:PowerUserRole00000000",
      "swid:entity:RegularUserRole000000",
    ];
    return disabled_roles.includes(roleId) || false;
  };

  const defaultColumns: ColumnDef<Permission>[] = [
    {
      accessorKey: "id",
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title="Permission SWID" />
      ),
      cell: (row) => row.getValue(),
      enablePinning: true,
    },
    {
      accessorKey: "name",
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title="Permission Name" />
      ),
      cell: (row) => row.getValue(),
    },
    ...roles.map((role) => ({
      accessorKey: role.id,
      header: role.name,
      cell: ({ row }: { row: { original: { id: string } } }) => {
        return (
          <Checkbox
            disabled={isDisabled(role.id)}
            defaultChecked={hasPermission(role.id, row.original.id)}
            onCheckedChange={async (e) => {
              updateRolePermissionInDB(
                role.id,
                row.original.id,
                hasPermission(role.id, row.original.id)
              );
            }}
          />
        );
      },
    })),
  ];
  return defaultColumns;
};

```

But I get this error:
```
Error: (0 , _components_getColumns__WEBPACK_IMPORTED_MODULE_6__.getColumns) is not a function
```

![image](https://github.com/TanStack/table/assets/32936978/847d189e-2fe4-4524-8736-cde1ca4bc7c7)


Any idea what the problem could be?

**Comment by KevinVandy** [comment]
Tables need to be in a client component because they use hooks

**Comment by Jared-Dahlke** [comment]
@KevinVandy here is my Table component:

```
"use client";
import React, { useEffect, useState } from "react";
import {
  Permission,
  Role,
  RolePermission,
  UpdateRolePermission,
} from "../types";
import { PlusIcon } from "@radix-ui/react-icons";

import {
  flexRender,
  getCoreRowModel,
  useReactTable,
  ColumnDef,
  VisibilityState,
  ColumnFiltersState,
  SortingState,
  getFacetedRowModel,
  getFacetedUniqueValues,
  getFilteredRowModel,
  getPaginationRowModel,
  getSortedRowModel,
} from "@tanstack/react-table";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@versesdev/ui-components/table";
import { DataTableToolbar } from "../../../../components/table/data-table-toolbar";
import { DataTablePagination } from "../../../../components/table/data-table-pagination";
import { Button } from "@versesdev/ui-components/button";
import { CreateRoleDialog } from "./CreateRoleDialog";

export interface RolesPermissionsTableProps {
  columns: ColumnDef<Permission>[];
}

export const TanstackPermissionsTable: React.FC<RolesPermissionsTableProps> = ({
  columns,
}) => {
  const [createRoleDialogIsOpen, setCreateRoleDialogIsOpen] = useState(false);

  const [rowSelection, setRowSelection] = React.useState({});
  const [columnVisibility, setColumnVisibility] =
    React.useState<VisibilityState>({});
  const [columnFilters, setColumnFilters] = React.useState<ColumnFiltersState>(
    []
  );
  const [sorting, setSorting] = React.useState<SortingState>([]);

  const table = useReactTable({
    data: [],
    columns,
    getCoreRowModel: getCoreRowModel(),

    state: {
      sorting,
      columnVisibility,
      rowSelection,
      columnFilters,
    },
    initialState: { pagination: { pageIndex: 0, pageSize: 50 } },
    enableRowSelection: true,
    onRowSelectionChange: setRowSelection,
    onSortingChange: setSorting,
    onColumnFiltersChange: setColumnFilters,
    onColumnVisibilityChange: setColumnVisibility,
    getFilteredRowModel: getFilteredRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFacetedRowModel: getFacetedRowModel(),
    getFacetedUniqueValues: getFacetedUniqueValues(),
  });

  return (
    <div className="space-y-4">
      <DataTableToolbar
        table={table}
        extraItems={
          <div className="flex ml-3 gap-3">
            <Button
              size="sm"
              className="ml-auto hidden h-8 lg:flex"
              onClick={() => setCreateRoleDialogIsOpen(true)}
            >
              <PlusIcon className="mr-2 h-4 w-4" />
              Create Role
            </Button>
            <Button size="sm" className="ml-auto hidden h-8 lg:flex">
              <PlusIcon className="mr-2 h-4 w-4" />
              Create Permission
            </Button>
          </div>
        }
      />
      <div className="rounded-md border">
        <Table>
          <TableHeader>
            {table.getHeaderGroups().map((headerGroup) => (
              <TableRow key={headerGroup.id}>
                {headerGroup.headers.map((header, index) => (
                  <TableHead
                    key={header.id}
                    className={
                      index === 0 ? "sticky left-0 z-10 bg-background" : ""
                    }
                  >
                    {header.isPlaceholder
                      ? null
                      : flexRender(
                          header.column.columnDef.header,
                          header.getContext()
                        )}
                  </TableHead>
                ))}
              </TableRow>
            ))}
          </TableHeader>
          <TableBody>
            {table.getRowModel().rows.map((row) => {
              return (
                <TableRow key={row.id}>
                  {row.getVisibleCells().map((cell, index) => (
                    <TableCell
                      key={cell.id}
                      className={
                        index === 0 ? "sticky left-0 z-10 bg-background" : ""
                      }
                    >
                      {flexRender(
                        cell.column.columnDef.cell,
                        cell.getContext()
                      )}
                    </TableCell>
                  ))}
                </TableRow>
              );
            })}
          </TableBody>
        </Table>
      </div>
      <DataTablePagination table={table} />
      <CreateRoleDialog
        isOpen={createRoleDialogIsOpen}
        setIsOpen={setCreateRoleDialogIsOpen}
      />
    </div>
  );
};


```

it is in client

**Comment by Jared-Dahlke** [comment]
i'm trying to getColumns from the server component, that way after i check a checkbox i can just revalidate the path and avoid tons of rerenders. Maybe it is not possible to getColumns from server component.

**Comment by meleyal** [comment]
You could move your column defs to a separate file marked with `use-client` e.g.:

```tsx
// columns.tsx

"use client";

import { ColumnDef } from "@tanstack/react-table";

export const columns: ColumnDef<User>[] = [
  {
    accessorKey: "name",
    header: "Name",
  },
  {
    id: "id",
    header: "ID",
    cell: ({ row }) => (<i>{row.original.id}</i>),
  },
];

// page.tsx

import columns from './columns';

export default async function Page() {
    const data = await getData();

    return (
        <Table columns={columns} data={data} />
    );
}

```

**Comment by laurent512** [comment]
I am struggling on this as well. What if my columns definition depends on something fetched by the server ? 

In my practical case, I am fetching some members information that I would like to show in a table. 
One of these members is particular and its name should be written in red. this is based on information fetched on the server. 

So ideally I would like to create a parametric column definition and invoke columns({particularUserId : smlkfjzoefj})

**Comment by Er4twXz** [comment]
Wouldn't it be easier in that case to query the members , then enhance this data with the additional column needed for rendering the table and then use the cell function to render everything properly ?

**Comment by shivpratik** [comment]
I'm struggling with the same. What if we want to pass additional data to the table that is fetched from server using server actions?

```typescript
// columns.tsx

"use client";

import { ColumnDef } from "@tanstack/react-table";
import { getAdditionalData } from "@app/actions";

export const columns: ColumnDef<User>[] = [
  {
    accessorKey: "name",
    header: "Name",
  },
  {
    id: "id",
    header: "ID",
    cell: ({ row }) => (<i>{row.original.id}</i>),
  },
  {
    id: "extraField",
    header: "Extra",
    cell: ({ row }) => {
     const data = getAdditionalData(row.original.id);
     return (<i>{data.field}</i>);
    },
  },
];

// page.tsx

import { columns } from './columns';

export default async function Page() {
    const data = await getData();

    return (
        <Table columns={columns} data={data} />
    );
}

```

**Comment by Brien-Austin** [comment]
> You could move your column defs to a separate file marked with `use-client` e.g.:
> 
> ```tsx
> // columns.tsx
> 
> "use client";
> 
> import { ColumnDef } from "@tanstack/react-table";
> 
> export const columns: ColumnDef<User>[] = [
>   {
>     accessorKey: "name",
>     header: "Name",
>   },
>   {
>     id: "id",
>     header: "ID",
>     cell: ({ row }) => (<i>{row.original.id}</i>),
>   },
> ];
> 
> // page.tsx
> 
> import { columns } from './columns';
> 
> export default async function Page() {
>     const data = await getData();
> 
>     return (
>         <Table columns={columns} data={data} />
>     );
> }
> ```

thanks man it worked

**Comment by webml** [comment]
If I need to generate columns on the NextJS server and pass to the client, how can I do that?

**Comment by karimdaghari** [comment]
Split the data table in 2 : `data-table.server.tsx` (where you’re generating the columns) and `data-table.client.tsx` which takes in the columns as a prop.


`data-table.server.tsx`

```tsx
import { DataTableClient } from “./data-table.client.tsx”;
async function DataTableServer() {
  const columns = await getColumns();
return <DataTableClient columns={columns} />
}

```

`data-table.client.tsx`

```tsx
“use client”;

interface Props {
 columns: Column[];
}


export function DataTableClient({ columns }: Props) {
return <DataTable columns={columns} />
}
```

On 02/12/2024, at 14:10, Mike ***@***.***> wrote:



If I need to generate columns on the NextJS server and pass to the client, how can I do that?
