### ISSUE TITLE
(Bug) Drag and drop columns in grouped columns

### ISSUE THREAD

**Issue by GlebKodrik** [TanStack/table#5179]
### Describe the bug

I need to drag the title column "Test" but he won't let me do it 

### Your minimal, reproducible example

 https://codesandbox.io/p/devbox/elastic-sound-3yv8lz?embed=1&file=%2Fsrc%2Fmain.tsx%3A90%2C20

### Steps to reproduce

Start moving the column 'Test"

### Expected behavior

Column "Test" should be dragged

### How often does this bug happen?

Only once

### Screenshots or Videos

https://recordit.co/fsafqWvR1M

### Platform

Windows Google chrome

### react-table version

8.10.7

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by GlebKodrik** [comment]
Another example

https://recordit.co/rD049mXt3k

I noticed that columnOrder updates correctly but by itself useReactTable doesn't update columns
![Снимок экрана 2023-12-02 020703](https://github.com/TanStack/table/assets/40304887/ead4fe14-c638-42d5-90b5-2b2c90dffb6e)

Local code example

**Comment by VladPorvin** [comment]
I met the same problem
https://codesandbox.io/p/devbox/competent-star-zwlj23?embed=1&file=%2Fsrc%2Fmain.tsx%3A32%2C42
I'm trying to move lastName, but it does't work. Column order updates but the table does't change the position of the columns

**Comment by KevinVandy** [comment]
I think the main problem you guys are running into here is trying to use React 18 with react-dnd, which doesn't really work. All tanstack table dnd examples have moved on to dnd-kit instead.

**Comment by nurbek-mirai** [comment]
I have the same issue, Did you guys resolve it? @KevinVandy  @GlebKodrik
