### ISSUE TITLE
toggleAllRowsSelected and toggleAllPageRowsSelected also select disabled rows/cells

### ISSUE THREAD

**Issue by lucascnunes** [TanStack/table#5181]
### Describe the bug

Disabled row/cell are being selected by the toggleAllPageRowsSelected and toggleAllRowsSelected

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/sleepy-mestorf-6vt5tv

### Steps to reproduce

I've defined a disabled state if the cell content status was concluded, but it is still being selected by the toggleAllPageRowsSelected and toggleAllRowsSelected

```
Here i'm using a Checkbox component, but on the codesandbox above I'm using plain input checkbox.


{
    id: 'select',
    header: ({ table }) => h(Checkbox, {
        'checked': table.getIsAllPageRowsSelected(),
        'onUpdate:checked': (value: boolean) => table.toggleAllPageRowsSelected(!!value),
        'ariaLabel': 'Select all',
    }),
    cell: ({ row }) => h(Checkbox, {
        'checked': row.getIsSelected(),
        'onUpdate:checked': (value: boolean) => row.toggleSelected(!!value),
        'ariaLabel': 'Select row',
        'disabled': row.getValue('status') === 'concluded' || row.getValue('status') === 'closed' ? true : false
    }),
    enableSorting: false,
    enableHiding: false,
    
  },
```

### Expected behavior

I was expecting that disabled cells would be ignored.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="220" alt="Selecting disabled cell" src="https://github.com/TanStack/table/assets/2693803/8adecec5-7aee-47d5-a701-39e339fc71a8">

### Platform

OS: M1 - macOS Sonoma 14.1.2
Browser: Chrome - Arc

### vue-table version

"@tanstack/vue-table": "^8.10.7",

### Additional context

If it's me doing something wrong let me know. 🤦‍♂️

### Terms & Code of Conduct

- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.
- [X] I agree to follow this project's Code of Conduct

**Comment by andreiculda** [comment]
You are only setting the checkbox as disableld, not sure tanstack can rely or should know about that.
What I did was set a disabled prop on rows which I want disabled and added a custom function for the main toggle, which kinda works but seems very hacky:

```javascript
function toggleAllSelected () {
    // use getIsSomeSelected as the disabled rows will not be selected, so cannot rely on getAllRowsSelected
    table.toggleAllRowsSelected(!table.getIsSomeRowsSelected())
    // get all disabled rows
    const disabledRows = table.getCoreRowModel().rows.filter(r => r.original.disabled)
    disabledRows.forEach(r => {
        // set as not-selected
        r.toggleSelected(false)
    })
}
```
Updated codesandbox: https://codesandbox.io/p/devbox/github-tanstack-checkbox-select-forked-zd5qp2?file=%2Fsrc%2FApp.vue%3A106%2C31

Could there be a solution for this?

**Comment by ylyra** [comment]
Just in case anyone else gets in here, there is also this way: https://tanstack.com/table/v8/docs/guide/row-selection#enable-row-selection-conditionally
