### ISSUE TITLE
Vue Demo on tanstack.com not working

### ISSUE THREAD

**Issue by Soundkage** [TanStack/table#5266]
Hi there,

I thought I would just let you know (in case you don't already :smiley: ) that your demo on the homepage for your Vue implementation is not working.  I loaded it up in codesandbox itself and saw the following:
![image](https://user-images.githubusercontent.com/4698170/181191871-526904ea-ea98-455e-895f-869f24d4b14e.png)

Have you changed something to do with the exports of your methods?  Maybe the package needs updating?

In any case it looks like a really cool product and I will be keeping an eye on it for future implementations in my projects.

**Comment by crutchcorn** [comment]
Transferring to the appropriate repo as part of the website repo cleanup. However, this issue may already be solved.
