### ISSUE TITLE
problem filter when i filter by subrow of ligne

### ISSUE THREAD

**Issue by majdos1993** [TanStack/table#5271]
### Describe the bug

bonjour , j'ai trouvé un erreur lors je fait un filtre par subrow valeur j'ai pas trouvé aucun  résultat , s'il vous plaît aidez moi 

### Your minimal, reproducible example

https://www.npmjs.com/package/@aures/custom-react-table

### Steps to reproduce

 j'ai trouvé un erreur lors je fait un filtre par subrow valeur j'ai pas trouvé aucun  résultat , s'il vous plaît aidez moi 

### Expected behavior

 j'ai trouvé un erreur lors je fait un filtre par subrow valeur j'ai pas trouvé aucun  résultat , s'il vous plaît aidez moi 

### How often does this bug happen?

Every time

### Screenshots or Videos

j'ai pas de video

### Platform

windows 10

### react-table version

7

### TypeScript version

  "typescript": "^4.5.4",

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by atefBB** [comment]
Bonjour. Le dev du package [@aures/custom-react-table](https://www.npmjs.com/package/@aures/custom-react-table) n'est public sur github ! Je suis un dev de la part d'aures et j travaille sur cet projet avec mes collégues d'aures, merci de me contacter sur atef.bettaieb@aureskonnect.com si vous besoin d'aide !
