### ISSUE TITLE
Dead Links in the Tanstack Table Documentation

### ISSUE THREAD

**Issue by BearCooder** [TanStack/table#5288]
### TanStack Table version

v8.11.6

### Framework/Library version

v17.2

### Describe the bug and the steps to reproduce it

When I go to the documentation here: https://tanstack.com/table/v8/docs/guide/filters
I get multiple guides:

- [Column Filtering](https://tanstack.com/table/v8/docs/column-filtering)
- [Global Filtering](https://tanstack.com/table/v8/docs/global-filtering)
- [Fuzzy Filtering](https://tanstack.com/table/v8/docs/fuzzy-filtering)
- [Faceted Values](https://tanstack.com/table/v8/docs/faceted-values)

All lead to dead links: **Oops! Looks like you tried to visit a page that does not exist.**

I got redirected to the page from Shadcn here https://ui.shadcn.com/docs/components/data-table
So I wanted to report that the links do not work and I tried the search function butz I cannot find the content for global filtering?
I wanted to customize the example from shadcn, instead of only filtering email values to accept other columns to filter too.

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

See the links in description

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by oulianov** [comment]
+1

The docs in the source are very minimal : https://github.com/TanStack/table/tree/main/docs/guide

**Comment by andrew1515** [comment]
The https://tanstack.com/table/latest/docs/examples link is also broken, it navigates me to the introduction page.

**Comment by RicardoAALL** [comment]
Agreed, the documentation in general isn't very helpful. Some improvements on that front would be very much appreciated.
