### ISSUE TITLE
flatMap is not a function

### ISSUE THREAD

**Issue by navidadelpour** [TanStack/table#5330]
### TanStack Table version

8.5.22

### Framework/Library version

17.0.0

### Describe the bug and the steps to reproduce it

`flatMap` is not supported in older versions of browsers. I've been receiving errors in sentry indicating that. 

Browsers:
- Chrome Mobile `66.0.3359`
- Chromium `65.0.3325`
- Chrome Mobile `64.0.3282`

Stack trace:
```
/static/js/4.0436c9ae.chunk.js in K.c.getAllLeafColumns.m.key at line 2:1446206
/static/js/4.0436c9ae.chunk.js in Object.getAllLeafColumns at line 2:1393500
/static/js/4.0436c9ae.chunk.js at line 2:1420005
/static/js/4.0436c9ae.chunk.js in e.filter.t at line 2:1419527
/static/js/4.0436c9ae.chunk.js in Object.getVisibleLeafColumns at line 2:1393377
/static/js/4.0436c9ae.chunk.js at line 2:1394675
/static/js/4.0436c9ae.chunk.js in Object.getHeaderGroups at line 2:1393377
...
```

I'm willing to contribute and submitting a PR to fix this. maybe we can polyfill or use alternative ways of doing this.
Thanks for your great work! :heart:

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

-

### Do you intend to try to help solve this bug with your own PR?

Yes, I think I know how to fix it and will discuss it in the comments of this issue

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by cralex11** [comment]
Have you tried to install the polyfill for flatMap?

npm install array-flat-polyfill
`import 'array-flat-polyfill';`

Or use core-js 
`import "core-js/fn/array/flat-map";`

**Comment by navidadelpour** [comment]
@cralex11 Yes, I eventually used core js polyfill.
