### ISSUE TITLE
Drag n drop stops working when using columnHelper

### ISSUE THREAD

**Issue by sherman89** [TanStack/table#5368]
### TanStack Table version

8.12.0

### Framework/Library version

18.2.0

### Describe the bug and the steps to reproduce it

Drag n drop (using dnd-kit) breaks when table columns are created using `createColumnHelper`.

I almost ripped my hair out wondering what I did wrong, but managed to work around the issue by passing the attributes and listeners from the `useSortable` hook in the cell context, then placing them directly on the drag handle button. If I just rendered the handle component (which calls `useSortable` with the correct id), it just refused to work in my case and in the react-table dnd example it stopped working after the first drag n drop.

I tried removing the useMemo thinking maybe it's the cause of the issue, but the result was the same.

In the end I ended up trying to create the columns the "traditional" way without using the helper, and it worked fine!

To reproduce:

- Go to https://tanstack.com/table/latest/docs/framework/react/examples/row-dnd
- Delete columns variable
- Replace with:
```ts
const columnHelper = createColumnHelper<Person>();

const columns = [
  columnHelper.display({
    id: 'drag-handle',
    header: 'Move',
    cell: ({ row }) => <RowDragHandleCell rowId={row.id} />,
    size: 60
  }),
  columnHelper.accessor('firstName', {
    cell: (c) => c.getValue(),
    header: () => <span>Last Name</span>
  }),
  columnHelper.accessor('lastName', {
    id: 'lastName',
    cell: (c) => c.getValue(),
    header: () => <span>Last Name</span>
  }),
  columnHelper.accessor('age', {
    header: () => 'Age'
  }),
  columnHelper.accessor('visits', {
    header: () => <span>Visits</span>
  }),
  columnHelper.accessor('status', {
    header: 'Status'
  }),
  columnHelper.accessor('progress', {
    header: 'Profile Progress'
  })
];
```

Now after the first drag n drop, it stops working.

Am I doing something wrong? It looks like a bug to me :)

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

https://tanstack.com/table/latest/docs/framework/react/examples/row-dnd

### Screenshots or Videos (Optional)

![reactTableBugDnd](https://github.com/TanStack/table/assets/20951158/82adfcc1-0833-4abf-9c68-94a6e17ccb48)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
@sherman89  This appears to just be happening because you aren't memoizing the columns anymore. The columnHelper is not a replacement for memoization. It only exists to add more TValue type-safety. If you don't want to use `useMemo`, you can just define the columns outside of the component, and that will also work fine.

**Comment by sherman89** [comment]
@KevinVandy Oh 😅 oops... Thanks!
