### ISSUE TITLE
@silevis reactgrid excel table full width

### ISSUE THREAD

**Issue by shiva8843** [TanStack/table#5374]
iam using @silevis react grid excel table , i have tried many ways to achieve full width , but i unable to get the table to fit the screen , even if the excel consists two cells , could you please suggest me the approach . how to get the full width table

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

none

### Screenshots or Videos (Optional)

![image](https://github.com/TanStack/table/assets/161428347/29985248-dde8-46f6-b1b3-ca59dbe65fd0)
![k2a9o](https://github.com/TanStack/table/assets/161428347/1dbabcb5-9186-456e-8f37-cdc6c76b747a)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
why was this issue opened for TanStack Table?
