### ISSUE TITLE
Pinned sticky column has incorrect position with non-fixed width table

### ISSUE THREAD

**Issue by thomassimko** [TanStack/table#5382]
### TanStack Table version

v8.13.2

### Framework/Library version

React v18.2.0

### Describe the bug and the steps to reproduce it

When using sticky pinned columns and a non-fixed width table, the pinned column positions is not correct.  It leads to gap in between the pinned columns.  I notice that when resizing the window/table, the CSS width property never changes.  I suspect this value is used in the calculation for the sticky positioning.

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

https://stackblitz.com/edit/tanstack-table-9qu1hq

### Screenshots or Videos (Optional)

![Screenshot 2024-02-29 at 3 04 02 PM](https://github.com/TanStack/table/assets/11153023/86e019dc-3bf3-46d8-a13d-d910eae4b55b)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This seems like your implementation problem. What would you expect TanStack Table to do differently?

**Comment by KevinVandy** [comment]
@thomassimko Adding a minWidth along with width fixes it
<img width="390" alt="image" src="https://github.com/TanStack/table/assets/28243511/008a7dc5-3e50-4cac-91f6-44bd3f8ab611">

**Comment by thomassimko** [comment]
So based off your response, this library does not support pinned columns in a fluid table without specifying the width of the column as px percentages. Currently I am using a ResizeObserver that is calculating each column's bounding rect in order to calculate the true position of the pinned column, rather than using the library's `getStart` methods.  I was hoping that there would be a cleaner way to achieve this.

**Comment by KevinVandy** [comment]
@thomassimko I guess I don't get what you would expect. TanStack Table doesn't really have a way of knowing if you change the total width of the table or not. It you are using it's size system, it expects the elements to be styled to be that exact size. If you are allowing columns to be squished together, how would the table instance know?
