### ISSUE TITLE
Pagination counts with extended option is wrong ??

### ISSUE THREAD

**Issue by stychu** [TanStack/table#5408]
### TanStack Table version

8.13.2

### Framework/Library version

React 18.2

### Describe the bug and the steps to reproduce it

I have a dataset comprised of events, each containing a series of changes. My goal is to represent this data within a table, where each row showcases a single event alongside its related changes. This structure should result in each event and its changes occupying a single row. However, in practice, when I attempt to display my data using an example dataset, the table incorrectly expands to show 8 rows instead of the expected 2. This discrepancy arises because it appears to count both the events and the individual changes within those events as separate rows. 

This could indicate a misunderstanding on my part regarding the correct approach how to use tanstack table  or possibly an issue with the pagination calculation mechanism.

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

https://codesandbox.io/p/devbox/mystifying-austin-8v4qdv

### Do you intend to try to help solve this bug with your own PR?

None

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I can't really tell what you are trying to do, but you can always override the page count and row count values by telling the table how many pages or rows that there are https://tanstack.com/table/latest/docs/guide/pagination#page-count-and-row-count

**Comment by perverseplotly** [comment]
@KevinVandy https://unthinking-rudy2.github.io/ZnQAmVHh3wc-x09Gsk1KP73uvJjUwINLznK3MB3KtgH0HF9yqg/
