### ISSUE TITLE
Row count parameter is not reactive when using manual pagination (serverside)

### ISSUE THREAD

**Issue by dogukanoksuz** [TanStack/table#5412]
### TanStack Table version

v8.13.2

### Framework/Library version

vue@latest

### Describe the bug and the steps to reproduce it

When using server-side pagination mode, rowCount might get changed by filtering etc. but table's rowCount parameter only can be changed at when initializing with params.

Because of rowCount parameter cannot be changed, when i'm sending filters, pagination total page count stays same.

![image](https://github.com/TanStack/table/assets/32539161/1d043bfb-8b0e-4251-b00d-888765ac4890)

I think moving this parameter to dynamic changable state(like pagination/sorting etc...) will fix this issue.

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

-

### Screenshots or Videos (Optional)

https://github.com/TanStack/table/assets/32539161/f87772d9-8c7e-4e94-b176-0893ee67ec8a

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by haayhappen** [comment]
I have the same issue in vue - any Tipps how to fix it there?

**Comment by haayhappen** [comment]
Ah I just found that this is the way to pass reactive values outside of the state property.... that could be a bit more obvious in the docs.
