### ISSUE TITLE
V7 documentation seems to be missing, resorting to Wayback Machine

### ISSUE THREAD

**Issue by toddpress** [TanStack/table#5427]
### TanStack Table version

v7

### Framework/Library version

React v7.0.2

### Describe the bug and the steps to reproduce it

Hello all, I'm working on an enterprise app for the govt using react 17 and react-table v7. Our delivery schedule is very tight, and we don't have the time to migrate our large app to v8/React 18 at the moment. 

I've searched the documentation site quite extensively and am unable to locate the legacy v7 docs - v7 is absolutely critical to our project. Currently, the best we're able to do is use the web archive's wayback machine to [browse the v7 docs](https://react-table-v7.tanstack.com/docs/api/overview).

Here's what we've done:

1. Navigate to https://react-table-v7.tanstack.com/docs
2. Note redirect to https://tanstack.com/table/v8?from=reactTableV7
3. Navigate instead to https://react-table-v7.tanstack.com/docs/api/overview
4. Note that there are limited captures and that the search bar is inert

Please tell me where and how to access the v7 docs directly 🙏🙏🙏. I'm almost certain that y'all still host them someplace... I just can't seem to find them anywhere except in wayback, which is obviously not optimal for myself and my team.

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

N/A

### Do you intend to try to help solve this bug with your own PR?

None

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
https://react-table-v7-docs.netlify.app/

**Comment by toddpress** [comment]
You da man @KevinVandy! 

How did I miss these?! THANK YOU SO MUCH!

**Comment by epurban** [comment]
I agree @toddpress @KevinVandy you da man! We literally could not find this and my team relies on v7 of react-table. Thanks for the save.
