### ISSUE TITLE
Examples for svelte in documentation page not working

### ISSUE THREAD

**Issue by davbauer** [TanStack/table#5437]
### TanStack Table version

v8.14.0

### Framework/Library version

Svelte

### Describe the bug and the steps to reproduce it

In the following folder `examples/svelte` all 6 examples for svelte are not working and throw errors when trying to launch them on the TanStack documentation page:

reference: https://tanstack.com/table/latest/docs/framework/svelte/examples/basic

I tried to fix it myself since I want to use TanStack Table in my own project but I do not have the time to dig into getting the example to work.

Following screenshots in the `reproduceable section` show the errors.

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

https://stackblitz.com/github/tanstack/table/tree/main/examples/svelte/basic

### Screenshots or Videos (Optional)

![Screenshot 2024-03-25 at 20 17 04](https://github.com/TanStack/table/assets/89662560/89c90f9b-6f79-4651-85ad-bc0bd2ed32e8)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
fixed
