### ISSUE TITLE
AccessorFnColumnDefBase not being exported, causes type error with an array of columns defined by columnHelper

### ISSUE THREAD

**Issue by slhsxcmy** [TanStack/table#5444]
### TanStack Table version

8.15.0

### Framework/Library version

18

### Describe the bug and the steps to reproduce it

Similar to issue https://github.com/TanStack/table/issues/5135 (for AccessorKeyColumnDefBase), in this case the error comes from AccessorFnColumnDefBase.

It seems to happen when several columns have different return types in their accessorFn, this error happens:
``` 
Exported variable 'Columns' has or is using name 'AccessorFnColumnDefBase' from external module "/node_modules/@tanstack/table-core/build/lib/types" but cannot be named.
```

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

[See the bottom of this TS playground](https://www.typescriptlang.org/play?ssl=530&ssc=1&pln=531&pc=1#code/JYWwDg9gTgLgBAbzgYWgUwPJhsCA7AZwBoV0AVAQwCMAbNAZRgpjRNSjQElCm8BjNHAC+cAGZQIIOAHIAdAHo+6eU1pppAKFCRYiDXANwAasALAqwGsBgBPbgV4Ci+wybMWrtymsbNWLgzdzS2sbVBoAVxA8OAoCUkjooI9Q8Ki8Z0NjU2DPGywcfGIA7PcQ2zTogBE0UUzXHJTbACUIAHdnEXFJGQVRNGYIjgJ5Srxk8ptNbWh4BBKxjCgAEzQoMfqDRZW1+0d-LO3VqALcQk2E9KXj7zpfFk6xCSk5eX7B4dGIRLxrteA8ABzabgWZ6Q7fdIABQBeABgI2C0h0RheDhQLGNTqSJ+qPRgL2FH4B0MYzx8NORQuZNh8NaHRx0NpQNuDCYDw0XWevTeAxgQzQIxpaPhIJ0cxK9PJQMJxIuUuZgMp50l7WlgPp8rVitZ938XJ6r3e-M+CpFQLFYPmEI4AAkBsdqeh7RRjgBxCQRMAXF3HVB4FgADxgPodawIsqcnKehoUSg48gAFmGoARLbokAAxCgCFjLDZwbO5tDLZXxA0vPp8gVC5F4ItoHAWrSgjOM6KZywsVOIiE-Ts0bsETG1J39rvhyMkrZ1gdDstj9Jz8Oa9v1iep3Xs-Uxyu8j6Cr7jwf-ZszNtZN00CBUCg0ZfrOsXK83u8PkfYy-X2-3jdT5-fm+G4LiUL4-g+W5+I83R7saNbyGBQEnlAootuK4KGPQszwr2mHYRidZYhcWGwPC-4lCRTZKtgZzFFklHwpBHIVjycGmu0DFnq2EqXp6YA4WgNA0M+fE4U+oGiQRPxERJEBemRPBElGvFyfxQIgSp8lAqumlqYCTE7jBrHVp8YweqpqHnjxhgAKKBmARKrMs5FZHZDl4E5Gm2fZjklgZFxub5yyrixRomYe9KBR5lncRhM4-PQwAAF5iT8i7RIlKVSekMl9ukmXwr6azpXgBUyopcprmV1GFCqeUZcljHUHc27QdyYUHrWCWNVx6HWoYUIUICALMGc3DWMAd7+SUg3DXgo34C5A1DSNtVeQYs2rWc02hVWnXyFKK3zbV6bWQY9L0IJaB8LVS3nRxV03Wc61wBdj21TphhvXQT34Dtu7Gft33XSdaFWqQHD0sIAOvPGaDyBIbSnYgcCDaRd4ANJoDYxBwAAqnCf0QNwQ4g2c0NGa8EQ4DQaZgxmKCCTQ-pBiGENoMgTMU+1cbKAIQnI0g7Ac3W3OxoofN1poGhoPZYIAt2og5oIrKZuFAA8ZBVMwFBwLLLAefE9La0wcAALyxHgNgAHxxXAfAcH4nNCQA-AAXHAAAUJRZPzNAe87NCaybFAkBEeAANZ4O0eDWxcvt1gHdbBzrcc+4YiMe-SKdMGnWRZKodAe6yOcUNbJQAJTm7bABuEDAMsJQO3yIs-O7XtKD8Sc-KXYeR9HbSxyQhdoMXzVoKX1tV2btf143vuOywRVQO3nvJq6awe8vvdwOHUcx3HcAj2PaiT9Ps8N03i9oPSq+Z697ST8P48n3QZ-V3AdeXwvLesqvx9wBLlrVO59P5zxKICRsWIKAREHB+VeoC0Y4DvOrD8O894D1juXLIkCYDQNgTAMsq904GAAUAkO2DDCIIoOjIOrIyzNEFN8GuJZJ6UIMLg8ayCaB6lXgCCad5eEey4ZNGgBlqG0M1uPPU5chAaBlnLXQCs1hKwEIA8eABZRsFBS562DGgQ2D82gUJRnIhR6FlFQFUYIMYWimC6P1gY5YRt2ghxIGQIwd4IhoFtkgMxssLEBhUcrQsG47G6z8fIgJ8sglWJCQ+TMhBTFRMUfASx1i4CcUBIk+IkTzExMViEgAgoCQEHBAQLXrEkvJ0TdC2DAIIPGYBlh+CgJrW2FsyBwAAD5e09t8ZYxdQFkArvkupNgGlwAwHgZAiYiSQMSe082XsvQtO7EsTxkRR742aa09poCv6NzGfAepghjY62WRgmOPS4A3gAFYgxuUSGwABtAAuik9Cpy4BFKtowjyaxlme1QOAD2zySBgAkGAAgYKragOeZ8gpwS1HkIuY4wx5zc4lHRc49mU4n4lGXhGCqAgCVZAmHkfFwDc4lT+FAKlFCSrqgZanLUbRmUkontSsuJUHzEocEpLljLQKAV-MhFlNKKL4QJJyslhhzJaRlQK4kcr4r5R6kq-YAUfIAucrK7ledlpzUqRKnlqo2iXR+rdfVJi8npPieFMsDj9EYtcanbFLrcUUtCC9I4axfV1nVC9M0+InUGouA2PMYbhX1XXMhAg0bWUitfGK9ZNEiiqsydKxNkrdIUnTXVby7lPIFoIJmsY1UXqbWOs9UtbLLVk3wDmsuyTjlwHtSi8eDCmE0BYcsZ1BtcWYrLh6wd8RhbNsNQYNWB5J2ttqWk2JGT6GloHU4lxxj3VZBxfEJBoisY43ViQ9Rahu0EGYaw8Nx7pACpYNIG50h8B6lmfM9QD6OAAqgNmISt4+AR02d4zQWRfHCERUopdISDKjvXezaa5LGiTDg6SOsdKkNqpRDqaRrVzXqjQ5cDsG4CB4cQqmtYeGsl4aik5Yjkl9JYaglVDVeHq2VLw8DX6eADKto7TYyQYA6AsBEVNejLBoOGOFnh71XgRPTnw78HYUA8PCnxGx7U5o6M+Gw7GvlxHRUQRk8RaVlGdXUYM7JRVSm6zVWY0dE1cJuGqYte9baMn52pPbRBtRQmxGuZ3ajGh3DUF8YE1wezoiDIgf8e5njRi12us3Vi7dnrx3oGzle+DZQ8hpZjch3EipstJqyCGuk7ReWEYK7m+VtHPr3Sc1as4NW4BUZLFDGp0XPNnPaBoiAqw6Ehz0WOoxtqSiIxhbFg17ySiiBoMwekY2Ktl0m1kUbAAhOwgzXrXWgP2hwKEgQkAW9bWRYGTkTMEEUvgAgCDnq-XgOLQ63VMHcQBwQFsrmDw6V7Eo0BgDGpoPSYubiSgAlWIGD2eAohUDWBoYZL2TtHzO3JrEZA0DgBmywTWUIoXxD8-ckGHSSi9N2-CQnfTIUQGhcXLHFOCDwrhfD75jA9tKkU6j-jfht7cue14nx5tSfE6BKTj8KO0d+HVsvFm+sd4eJ50d+HMWmeFRTJwVYAZgCiGAIC-qBh17HA9gLwEwPljtwN5yeXHW4Aq5VwYnAGu1j3Y3W4wBL3fFG-1zAZnJRddrHbor9SrPRdLxTNLl3ZuNDfLGNbtXdvUwO6GzrbnWyCdZF6Vb1XtvNdtK5872XpO-eAmXlHjP0ONDyHkPImLH47IGzMBm7lA2YPDsT94y5-cD5ia9QhvIH4mWKh72uPlaD0vyr0xufv9FpVD5ywYBVekp8J5z0nkq1UPxucCYUtRH4VtxCFWi5L8enuL5b29tvH2O8pekrUavBja+EBD7Lu2uCCbAAAI7eJewQduF2rs3cWdn97eA7y7CYgEAEA3Y7cwubO6OE8Eu+ArM9+SewBfsEBhEtQIu7OGOgckuwYCB3icuWQIA2iKBPw4SuBPiYeZe5uG+ggRe6umu+YqBogceTeR+r2u8p+sc5+SOtQ2+BAu+h+MuSedsDcJuHuJOWQ3uK8Hs+eSw6B0BnOTugheBYeC6COkyVQpg7OYQjBR6WQ9efmTeJQShbBABzgn2W+O+ZBtsAAZHJrQTHmWtnsYeXFoBbrPhYXwcwY9qHKwa3vvGfkloNh4fwT4c4XbJ3OkJ-t3DlLUDvM8tbJNlFl8oju4ToUYf1gYd4RcMYX4ZgmYcsqkZfqILwSEc3rzrYZHunnQeGFYRXhbt-oKL-jMowSUV4QlqES9rke3oETBsEVYXbDmD-tAIkh7A0ddsMXdk4aHkkWCN8mMU0WgukXvoNoYXoZ0Sfv4RkBoJ9vMRMX0VMQ-hUXWPYZno4YoaHm2jFrsVAAen0UsabJke0dkesewZsfkX5vsecQ-tru2sbu7p7lkIMY0dAAeh7J7AbnALYQgEIFXL0hHNjBAKIIAiHCoe5nMZdsCTcdjIsXoRkfvqsYYDkRsXkdscstcbcS0ZYQcUIdYTNAFqIkFj8CcTUdSXgS4aoeiUMY+EUW0V8Vsl0R9nzinj8hieMVidoTyayeQcKdcYkvPgIRcZQW2hHjofofiVkb4cSQfEKYYL0hoQQFofKR0bnsKYUTEUwVKcAb0tcUaWUeyWiYjh+Iwuer2qwvcbrI8UDmsTzgKVsZ9nuigs-kTCTOGI2ndraawUdjYQMaKTdgeqIZ7jMeBtQXJryQvkSa8ZgsAR8egGMFYSVFJhKekL3uprhNOsrHmHmcPuhnGkOFWdPnACRu+OJBPqRNlNEJmrPqlOkOWlZhqmWXJnSmMGvkinEpvkzGmQqSaYYDmRwIHPmeZnPlzG1uvsioIAocsY3hqc4VwcLBuVOUvoxllAXimCOcmWuXAMvLPpOSOj0eJs6CmNeQaq2gzojgGTQAeo4SQBjA3oYvCTYIiYAp9hgCANYJrN+dGe+erDCH+uBXABjHLhyYjowm-sABwMsJ+XBT+X5v+YBWQMBaBTAFhTYZKGgKhehdBcALBWQBBeXEhZMhgCwlAG0ChBjjRfjL+bikgC8mQAeh5nALhUiWQG8u3M8sIARWBUYRcIJfjKSbSVkHjK+ZMkGZxsTLEnwRxkshbN7HoZxfEGJS7F7GDoAnTjYHAODmgExTDnpUZR7ACP0FAK9KZSUIZc0CUBZVZcqYjpwAQL8jYHBQAJokAAByn2AAjDZQAAyQmAJwCGUBXmVwDBVeWTI+UYyYKBUhWfYAE2VdKGXBWJUBXyIqngDUw3yvq6GGAFV+YQ4gBQ5QDyiCgEI2VFJQBQAUD+UAGfbvL5EWzOkEIvLSB0BAgwCJjSBvI2XJVZCuVNWDjuWkClUsDNAVXBUkAvKyAbX9WDgHazUwCDXDWAijXjVvLlzfLcCg4AAs0VFsIKYAZVy1QIE8V1CRtV9VHype8glu8Qo1pgahggus-I-GaALs4e3lRGXob8+FyyXSfmjsyw+ANAZlzy7yMVSAB1o1dleADlcAAAMgYodYmKBtNbjfjaNTZedbLFdS5YAvNXgJZdDlkB5SXmXpbkiT9d9Yjr9QDRDawHAG0HMoussFRYKLEBwLEEJO0CWCDXMRLW0CWBTYGIKJVQYGQDzTZYwq6AjTYK1e1f5fERcJ+TZa9YChbHTUxb1YAmrbDQ6FrXAEtoYIZZ+fNarUDTZXDbbS8vZYCgAPokAbWyBe2OWUCWAfLE1FKy3y0AqK2OEUCWDfnYzxC9LB00D7Wk1jUnXzVO0pWCA1BoBgCYXsVax51k1+bI0TUWxAHQ01DYCJip0jXp02UACs1NZtDNhgHsOVfmZA1NpujNsV1tmteAiNlsryE1thPlLtkNwBhl4d14cteqoOStUNepaAedn5WOtQwAgYcFs9ktC9ssS9h8RdNdwBxcNlZd1Nud+dCdmsLyxtUAbya1-tx9o1JAzyGdfdMN++JsaALd9NUAztNleON01NnsMlXSthBusJcAV969HAGu297F4D7i1do1p9cArdADoN6hq919OMG9CDytgC2RBDW92RqDhNpdVsPVpJnSpDgYNl4DMVns99NyUD1NAABgACQIBkD0NCCyA8OwM31kA8X0OP123P0UNv1WwnUxUG5CAcO03-1KU524MvZwV8NQqfZf0rFbYrDqwQm9L30yM2zU1aMU42XcMICB2AIrbtX8CJgCM8O2NF153U5gCKOX3qM8631kD2NKSJgSNuNgAePoOiMWNgDyNiFAih3t0YMqPZ1JVqUOVaV23CU8Xn1WxxVwDRVM0P2qONmNjdiawu7LKawZnOGeygLBUpP25kA7lJNjD2g0ANJZ54krHeGfY-FAlikexEN6HXEtWxkTGTw3LCOHrVn5w5Fd1DN+aymTFO6uOMImicH5wO2AIrNDB4DHrFxzPf24MF0ULHqGVX0aNOHXHAF92YMXDWw6XrOxAjNQB7NPPxyGARHRAvNcnDNcl-7HMPP5ynOaEzZFnVCxGWnHp93MkMGSl8nKFZCgIRk7lZBC0GkgtgkfN4Aez6mGmqkUKIt4sL5dUQJ8QYuJyNl8RGlTwfwRnEtJnwCiDhwcb2zXzNOCRtNENqmdNPHbHVPRHRAtMcvPk-EcCrN2yAlPNgm9M3YkCYugI-EAuivbN-WAXSvQDmxmwWzSCMv8CgwAsAuGWewKv6vrP+2YtvMmsSu-NYuPNckWv6siBxAj2jKWv5wezGuusGBmstmevrNqvilgqvOQsPNyIAtCD2uotaEeyYsfwxtOu0scFTr5xlKqTRuiwzz2yizxuEuH5dUXByJmLfJQjhj4DLI-EsKJhUVFxwAABEUOeASUNbNydbIAbQNb8iWQGuqYMAwVFAhB-x4hhgM2Dgvb-bcAvdhgQ02y99JQNcOQMAY2M7WQt6EQY2E7Bg5OZSjR4OkObdBgzcfgywRSMA2LfgJQdNDgJY7rx6ogoBHsLywbBgHr+rt4zzMgr7QGlr4bx6cT6zr77r47EQVA2+b7VAoBdARIwg9tf7FASU17rrt7EAHs2roBn7Jr-74rlrt4cH77sHaHDrx6obhgBb8iSTCzH4-CtUnLCzPzmJiyxbqY+A5cOxTzcpOhDH56GQm2qzZAZ2msCzcu8iSgPAcAyYrTJtLLLcbL4nbSHHTH1TpHqhwnDgcmRgaAlbfAdAyyYnbTsg-r9zBgiMH8iMsgFbVbsmz7khHsNbanGndANb9rDcyHZnmn6gJQciVcTr5H7HJbXHcngB0gLndA41Lhbayn8AYwJSbBOnawenTzBncARnGbJnU7FwlnKYyHUX0gjnG2NbU7Dn7n1lXnrHzRPJ-nJA999p6E4Xcm9wq72n7LsX+nI27Qxn7QsgK7dEhg6XG8b7NbdXBABXALTnMgnX+HHnsQ8Q3nZXvnJABuVXYINXYw8QFda4tn5nJUUXy+7Iq7Gg718gAAVBoLaBAExbcjEMt5bMsLclQHwVACwkfMmH9bckiZdwCHXK6VNyV8EW7CUJ7J7NN+aa0eVxg7u1ANGfnoXlUTHtAwD995SZ4SD5VzFWnjbtUW0v7dS70nD9a30ZjzFZD8rtD5nrD4D2C8UZYfj+Pc5MT-bpjxXBXJNlhPxbrI7DQHAOTg8jdI979W0HJDQNd0oKLgCL965KkiWJ-DQpNGoDIMt-enMvEOq79au-CBg324INIGT3gFiCUfekZI4lAPNOzyAD1rAoIDW-INHKsN7Sb8sGbyMAAAK8ACp-oqDjwAC0cM8gVAEQlgyw8gVgVAKgZ2g3cAPv8AfARI0c8AUOavhBywsgC7nsV1AATAAMyjIHfyBAA)

### Screenshots or Videos (Optional)

<img width="1324" alt="image" src="https://github.com/TanStack/table/assets/20136533/313bfc8f-91f0-412c-9e26-b5ddcdff7fff">

### Do you intend to try to help solve this bug with your own PR?

Yes, I am also opening a PR that solves the problem along side this issue

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Does this only happen in certain package managers?
