### ISSUE TITLE
Column Virtualisation is not working in case we have grouped columns

### ISSUE THREAD

**Issue by umeet23** [TanStack/table#5472]
### TanStack Table version

8.8.5

### Framework/Library version

17.0.2

### Describe the bug and the steps to reproduce it

When we have grouped columns then column virtualisation does not work properly.

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

https://codesandbox.io/p/sandbox/quirky-borg-t6p4w8?file=%2Fsrc%2FmakeData.js%3A12%2C34

### Do you intend to try to help solve this bug with your own PR?

None

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
yeah, the examples in the docs don't account for this. You'll probably need a different virtualizer for each row of headers in the case of header groups.
