### ISSUE TITLE
Site not loading

### ISSUE THREAD

**Issue by devnoot** [TanStack/table#5502]
### TanStack Table version

latest

### Framework/Library version

latest

### Describe the bug and the steps to reproduce it

Visit https://tanstack.com/table/latest directly.

The site should load. Instead it throws an error, resulting in a white screen. I attached the log file with the errors.

[tanstack.com-1713763119713.log](https://github.com/TanStack/table/files/15057928/tanstack.com-1713763119713.log)

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

Website Issue

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alexisdelage** [comment]
The website seems to load correctly now, but there is still an issue with the **Migrating to V8** page (https://tanstack.com/table/latest/docs/guide/migrating):

<img width="1440" alt="image" src="https://github.com/TanStack/table/assets/103410601/f7c04783-5559-4290-8741-d6a703bd2e74">

**Comment by KushagraMehta** [comment]
https://github.com/TanStack/table/pull/5503

I already made the PR the fix this. Please review it

**Comment by SwapnilSoni1999** [comment]
I guess this needs to be reopened I'm facing same issue 
I just opened https://tanstack.com/query/latest and it showed webpage for a second and now its while blank page

**Comment by chasehelton** [comment]
> I guess this needs to be reopened I'm facing same issue I just opened https://tanstack.com/query/latest and it showed webpage for a second and now its while blank page

I am also seeing this ^

**Comment by KevinVandy** [comment]
The site is up and nominal. Though we have heard from some using older versions of browsers that they see a white screen. Probably using one of the newer es22 features now that the docs are using TanStack Start instead of Remix

**Comment by yannis-iG** [comment]
For example if you try to load the page in **DuckDuckGo** browser, works fine to me

**Comment by chasehelton** [comment]
> For example if you try to load the page [https://tanstack.com](url) in **DuckDuckGo** browser, works fine to me

This worked for me. I was using Google Chrome when experiencing the issue.

**Comment by catdad** [comment]
I have tested the latest Chrome, Safari, and Firefox. I don't think this is an "old browser" issue.

Also, I figured out that if I do to https://tanstack.com/ directly and then browser to a component (say virtual), that works. However, if I go to the URL of that component directly (say https://tanstack.com/virtual/latest) that loads a blank screen with a ton of console errors.

**Comment by umutbozdag** [comment]
It's still the same, white screen, can't see anything

**Comment by angelospanag** [comment]
Just in case this helps someone, at the time of writing, while using the latest Chrome (124.0.6367.119) and latest Firefox (125.0.3) I was facing similar issues.

The culprit was the [Dark Reader](https://darkreader.org/) extension, and when I disabled it every Tanstack URL seemed to load fine even when accessing it directly, except https://tanstack.com/virtual/latest, [same as @catdad](https://github.com/TanStack/table/issues/5502#issuecomment-2082956888).
