### ISSUE TITLE
Angular Table Column Filters and Column Grouping Examples not working

### ISSUE THREAD

**Issue by KevinVandy** [TanStack/table#5548]
### TanStack Table version

v8.17.0

### Framework/Library version

Angular 17.3

### Describe the bug and the steps to reproduce it

 [ERROR] Could not resolve "./lazy-signal-initializer"

    ../../../packages/angular-table/build/lib/esm2022/index.mjs:3:25:
      3 │ import { lazyInit } from './lazy-signal-initializer';
        ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "./proxy"

    ../../../packages/angular-table/build/lib/esm2022/index.mjs:4:29:
      4 │ import { proxifyTable } from './proxy';
        ╵                              ~~~~~~~~~

✘ [ERROR] Could not resolve "./flex-render"

    ../../../packages/angular-table/build/lib/esm2022/index.mjs:6:83:
      6 │ ...FlexRenderComponent, FlexRenderDirective, injectFlexRenderContext, } from './flex-render';
        ╵                                                                              ~~~~~~~~~~~~~~~

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

https://tanstack.com/table/latest/docs/framework/angular/examples/filters

### Do you intend to try to help solve this bug with your own PR?

Yes, I think I know how to fix it and will discuss it in the comments of this issue

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
@riccardoperra @arnoud-dv fyi, debugging why this started happening. It was fine the last time I tested it. I have not isolated the issue yet. Might just be esm build config stuff.

**Comment by arnoud-dv** [comment]
From my phone so cannot really debug atm but could the reason be that the module field in package.json is not pointing to the fesm directory?

**Comment by KevinVandy** [comment]
@arnoud-dv fixed in #5549. TIL `import` != `esm` or `esm2022`. Thanks for your help this weekend.
