### ISSUE TITLE
Does React 18 work with v6?

### ISSUE THREAD

**Issue by simkessy** [TanStack/table#5553]
### TanStack Table version

v6.11.5

### Framework/Library version

React 18 latest 

### Describe the bug and the steps to reproduce it

Seeing issues with sorting, takes multiple clicks to sort

When I change row size from small to large it doesn't show new rows 

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

.

### Do you intend to try to help solve this bug with your own PR?

None

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
V6 was only designed to work with React 16 and will receive no new updates as the last patch was over 4 years ago.

<img width="331" alt="image" src="https://github.com/TanStack/table/assets/28243511/de431597-5314-48cd-998d-4503a60031f9">
