### ISSUE TITLE
Updating a useQuery with a key crashes using React Table

### ISSUE THREAD

**Issue by herbievine** [TanStack/table#5602]
### TanStack Table version

v8.17.3

### Framework/Library version

v18.2.0

### Describe the bug and the steps to reproduce it

I have a useQuery which takes a filter as queryKey to be applied onto the API URL. When you update that key, everything breaks. This is directly correlated to the table, as otherwise all is fine.

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

https://codesandbox.io/p/sandbox/elegant-hofstadter-q83sq2?file=%2Fsrc%2FApp.tsx%3A61%2C67

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This is another classic "non-stable" data/columns reference error in your code. Give `columns` and stable reference. Don't define without either `useMemo`, or define them outside of the component. https://tanstack.com/table/latest/docs/faq#how-do-i-stop-infinite-rendering-loops
