### ISSUE TITLE
[Angular] In the example, column sorting does not work.

### ISSUE THREAD

**Issue by pimenovoleg** [TanStack/table#5663]
### TanStack Table version

8.19.3

### Framework/Library version

Angular 18

### Describe the bug and the steps to reproduce it

In the example, column sorting does not work.
https://tanstack.com/table/latest/docs/framework/angular/examples/filters

Or is there something that needs to be configured or an option that needs to be activated?

```
@if (header.column.getIsSorted() === 'asc') {
            <span> 🔼</span>
            } @if (header.column.getIsSorted() === 'desc') {
            <span> 🔽</span>
            }
```

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

https://tanstack.com/table/latest/docs/framework/angular/examples/filters

### Do you intend to try to help solve this bug with your own PR?

None

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by pimenovoleg** [comment]
Sorting works if you add a (click) with the call to header.column.toggleSorting().

```
@if (!header.isPlaceholder) {
    <div
        (click)="header.column.toggleSorting()"
        [ngClass]="{'cursor-pointer select-none': header.column.getCanSort()}"
    >
```

According to the documentation, the method should be called as described https://tanstack.com/table/latest/docs/api/features/sorting#gettogglesortinghandler.\

Its correct?

**Comment by KevinVandy** [comment]
Feel free to correct examples with a PR
