### ISSUE TITLE
To use @Tanstack Table/vue-table, you must import the core package, but the documentation does not specify this

### ISSUE THREAD

**Issue by HongxuanG** [TanStack/table#5672]
### TanStack Table version

v8.19.3

### Framework/Library version

vue@3.4.2

### Describe the bug and the steps to reproduce it

I tried to use the vue-table version but found that `getCoreRowModel` was undefined, and I found that I needed to introduce `@tanstack/table-core` to use it

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

none

### Do you intend to try to help solve this bug with your own PR?

None

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Yeah, this should not be the case. `'@tanstack/vue-table' re-exports everthing from Core
