### ISSUE TITLE
Sub components are overlapped with successive rows

### ISSUE THREAD

**Issue by huy21298** [TanStack/table#5674]
### TanStack Table version

8.19.3

### Framework/Library version

React v18.2.0

### Describe the bug and the steps to reproduce it

I'm using this library combining with @tanstack/react-virtual to build a reusable table. However, I'm struggling with this issue. This bug happens when I try to open a sub component below parent row and it comes behind next rows after that

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

https://codesandbox.io/p/sandbox/datagrid-component-fcj3t4

### Screenshots or Videos (Optional)

<img width="628" alt="Screenshot 2024-07-25 at 16 29 59" src="https://github.com/user-attachments/assets/03d74764-94b5-41a9-8ffa-4bd4435602b1">

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Yeah, you have to account for the subcomponents as their own rows. It took a ton of iterations to figure this out in my MRT libraries. Take a look at it's source code to see how I did it.
