### ISSUE TITLE
The left position of pinned columns in the sticky table is calculated incorrectly

### ISSUE THREAD

**Issue by MiqueVzvsky** [TanStack/table#5683]
### TanStack Table version

8.19.3

### Framework/Library version

18.2.0

### Describe the bug and the steps to reproduce it

Hey guys, I found an issue where the offset or size of the pinned column is being calculated incorrectly.

Referring to this example:
https://tanstack.com/table/latest/docs/framework/react/examples/column-pinning-sticky

When we make a change like the one below for any column:

> cell: (info) =>
>     '/devicexxx/devicexxx/devicexxx/devicexxx/devicexxx/devicexxx/ devicexxx/devicexxx/devicexxx/devicexxx/devicexxx/ devicexxx/devicexxx/devicexxx/devicexxx/',

And after pinning two columns as shown in the picture, as a result, we will see empty space between columns.

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

https://codesandbox.io/p/devbox/distracted-hawking-jsz4r9?file=%2Fsrc%2Fmain.tsx%3A47%2C5

### Screenshots or Videos (Optional)
![image](https://github.com/user-attachments/assets/04c486e7-183e-4489-889f-0d10b17f125f)

_No response_

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by MiqueVzvsky** [comment]
The problem is related to column width. Correctly setting minSize prevents the problem, but I don't know the exact size of the specific data in the column, so I don't think this is a solution. Any ideas on how to handle this?

**Comment by KevinVandy** [comment]
This isn't a problem with TanStack Table's width calculations, but rather how the table CSS is being applied.

One option is to give a min-width to the column as you said.

Another solution is to add `word-break: break-all` so that there is no min-width on the column at all. Or use some other kind of flex/grid styles instead of the default table CSS.
