### ISSUE TITLE
cell only displays one line

### ISSUE THREAD

**Issue by RoyMtonga** [TanStack/table#5685]
### TanStack Table version

v8.19.3

### Framework/Library version

Next 14

### Describe the bug and the steps to reproduce it

the div just shows all the items in one libe
export const mobilecolumns: ColumnDef<ProductColumnMobile>[] = [
    {
        accessorKey: "id",
        header: "Products",
        cell: ({ row }) => (
            <div className="flex flex-row ">
                <p>{row.original.category}</p>
                <p>{row.original.color}</p>
                <p>{row.original.price}</p>
            </div>
        )
    },

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

 .

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I recommend learning about CSS
