### ISSUE TITLE
onPaginationChange when set to undefined doesn't fallback to using default pagination 

### ISSUE THREAD

**Issue by Akkuma** [TanStack/table#5690]
### TanStack Table version

v8.19.3

### Framework/Library version

React 18

### Describe the bug and the steps to reproduce it

https://stackblitz.com/edit/tanstack-table-ton6ab?file=src%2Fmain.tsx

Table with `onPaginationChange` explicitly set to `undefined` will stop being able to paginate.

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

https://stackblitz.com/edit/tanstack-table-ton6ab?file=src%2Fmain.tsx

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I think this should be the functionality

**Comment by fw-amgaa** [comment]
how is this completed? this bug still exists. Is there any work around?

**Comment by wiztral** [comment]
This worked for me

```typescript
const paginationOptions = manualPagination
  ? {
      onPaginationChange: handlePaginationChange,
    }
  : {};

const table = useReactTable({
  // options
  ...paginationOptions,
});
```
