### ISSUE TITLE
Use of svelte/internal in Svelte 5

### ISSUE THREAD

**Issue by moalamri** [TanStack/table#5707]
### TanStack Table version

8.20.1

### Framework/Library version

Svelte 5

### Describe the bug and the steps to reproduce it

This is not related to the use of runs in Svelte 5 or migrating the current TanStack's codebase to Svelte 5 as it should be working fine with Svelte 4.
It is about the use of `svelte/internal` as it is no longer supported in Svelte 5 which will make TanStack unusable and a migration blocker to projects depending on it.

              The solution is to not rely on `svelte/internal` anymore. If you're solely using this for utility functions (like `identity` in your case), just copy the function into your own code and remove the import. For non-utility functions it would be good to know why you reach into internals. In the meantime, closing since it looks like you're only relying on it for utility functions.

_Originally posted by @dummdidumm in https://github.com/sveltejs/svelte/issues/12104#issuecomment-2179984454_
            

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

https://svelte-5-preview.vercel.app/#H4sIAAAAAAAACmWNwQrCQAxEfyXkUoVK76WKfoO9WQ_rNoXFbrJsUkFK_11avXl8M8ObGYcwkmJ9m5FdJKzxkhKWaO-0gr5oNMISVabs16RRn0OyU8chJskGM_hMzui6TVv3GAkWGLJEKM7mWM35Z_UVHWyti469sBpsBMd_wU6SBWHdd9xUv0MsMUofhkA91pYnWu7LBxTLfES_AAAA

### Do you intend to try to help solve this bug with your own PR?

None

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by moalamri** [comment]
After going through some PRs, I found that this issue [should be fixed with some upcoming update](https://github.com/TanStack/table/pull/5403#issuecomment-2162061705).

**Comment by alissa-tung** [comment]
> After going through some PRs, I found that this issue [should be fixed with some upcoming update](https://github.com/TanStack/table/pull/5403#issuecomment-2162061705).

I have tested it with `pnpm add @tanstack/svelte-table@alpha`, seems works well

**Comment by KevinVandy** [comment]
> > After going through some PRs, I found that this issue [should be fixed with some upcoming update](https://github.com/TanStack/table/pull/5403#issuecomment-2162061705).
> 
> I have tested it with `pnpm add @tanstack/svelte-table@alpha`, seems works well

Be aware that some breaking changes will be coming to the alpha soon though. And we don't have the v9 alpha docs visible on the TanStack website yet, but they can be browsed on GitHub.

**Comment by moalamri** [comment]
> > After going through some PRs, I found that this issue [should be fixed with some upcoming update](https://github.com/TanStack/table/pull/5403#issuecomment-2162061705).
> 
> I have tested it with `pnpm add @tanstack/svelte-table@alpha`, seems works well

I didn’t test the alpha and I didn’t know it was under development, sorry for that :)

according to @KevinVandy I better not implement it for now so I will wait for the official release.

Thank you all for the good work

**Comment by KevinVandy** [comment]
> > > After going through some PRs, I found that this issue [should be fixed with some upcoming update](https://github.com/TanStack/table/pull/5403#issuecomment-2162061705).
> > 
> > I have tested it with `pnpm add @tanstack/svelte-table@alpha`, seems works well
> 
> I didn’t test the alpha and I didn’t know it was under development, sorry for that :)
> 
> according to @KevinVandy I better not implement it for now so I will wait for the official release.
> 
> Thank you all for the good work 

You can use it, you just might want to pin the version and make sure you only upgrade intentionally.

**Comment by moalamri** [comment]
I just updated TanStack Table to alpha.10, applied all the new changes and it is rendering👍🏻 
Just a little tip, to make options `writable` and the table instance reactive as in Svelte 4 I did the following.

```typescript
let options: TableOptions<any> = $state({
    data: defaultData,
    columns: defaultColumns,
    getCoreRowModel: getCoreRowModel()
});

const table = $derived(createTable(options));
```

Maybe you want to update the examples code.
Thanks a lot 👍🏻

**Comment by dummdidumm** [comment]
If anyone's looking for a drop-in replacement that largely keeps the old API of `@tanstack/svelte-table` version 8 while using Svelte 5, I created a drop-in replacement meant as a temporary solution until you can upgrade to `@tanstack/svelte-table` version 9: https://www.npmjs.com/package/tanstack-table-8-svelte-5
