### ISSUE TITLE
Weird table sometimes

### ISSUE THREAD

**Issue by virus231** [TanStack/table#5743]
### TanStack Table version

v8.17.3

### Framework/Library version

"react": "19.0.0-rc-fb9a90fa48-20240614",

### Describe the bug and the steps to reproduce it

**First show page**
![Image](https://github.com/user-attachments/assets/f588ce48-6987-40ab-b90b-61a080cd38a7)

After reload
![Image](https://github.com/user-attachments/assets/b7a154cb-d41e-4488-ac4d-acfeb904c3c5)

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

-

### Do you intend to try to help solve this bug with your own PR?

None

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This has got to be close to the definition of a junk issue with no reproducible example or relevant code. It's going to be pretty difficult for anyone to help you with this information.
