### ISSUE TITLE
Vanilla example is not loading due to wrong urls

### ISSUE THREAD

**Issue by fatso83** [TanStack/table#5785]
### TanStack Table version

8.20.5

### Framework/Library version

Na

### Describe the bug and the steps to reproduce it

Go to the [homepage](https://tanstack.com/table/latest), scroll down to "Take it for a spin!", press Vanilla and observe 

> The url to this repository is invalid.
Please make sure the folder path in the URL exists within the repo.
If you think this is a bug, please file an issue in our repo!

The link to file an issue also seems funky. Pressing it crashes the page and it also seems wrong: https://github.com/stackblitz/core/issues/new

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

Not code

### Do you intend to try to help solve this bug with your own PR?

None

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by fsmeier** [comment]
Heyhey,

why is this marked as completed? 

it seems to still happen with https://tanstack.com/table/latest

![Image](https://github.com/user-attachments/assets/c2d2186b-8ab0-4425-8798-5a79d0b28efb)

All the best,
Florian

**Comment by fsmeier** [comment]
Related #5821
