### ISSUE TITLE
Tanstack table mutates the props passed into it

### ISSUE THREAD

**Issue by aarjithn** [TanStack/table#5820]
### TanStack Table version

8.20.5

### Framework/Library version

React 18.3.1

### Describe the bug and the steps to reproduce it

Typically in react, props are considered immutable - it is not expected that component / hook we pass into updates it.

While looks like it doesn't cause too many issues (?) for those who use redux will see below error, because redux freezes the store to prevent accidental mutations.

`Uncaught TypeError: Cannot add property id, object is not extensible`

Steps to reproduce

1. Open https://stackblitz.com/edit/sb1-syghbl?file=src%2Fcomponents%2FUserTable.tsx
2. Instead of columns2, pass columns1 to MaterialReactTable

PS: The example is of column Defs, but there could be more

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

https://stackblitz.com/edit/sb1-syghbl?file=src%2Fcomponents%2FUserTable.tsx

### Do you intend to try to help solve this bug with your own PR?

None

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by sahilrajthapa** [comment]
Hello @aarjithn, I think this issue should be created at [Material React Table](https://github.com/KevinVandy/material-react-table) repository. The mutation of props seems to occur [here](https://github.com/KevinVandy/material-react-table/blob/v3/packages/material-react-table/src/utils/column.utils.ts#L54), not in the TanStack repository.

**Comment by aarjithn** [comment]
Great catch, closing this one
