### ISSUE TITLE
Vanilla javascript table example on main website not working

### ISSUE THREAD

**Issue by RobOlejniczak** [TanStack/table#5821]
### TanStack Table version

v8.20.5

### Framework/Library version

Vanilla Javascript 

### Describe the bug and the steps to reproduce it

The attached image shows the issue when trying to view the example of using tanstack table with vanilla JavaScript.

https://tanstack.com/table/latest

I think it might not work because there is not a vanilla example in the GitHub repository. 2nd image shows all examples are there except for the vanilla JavaScript example.

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

https://github.com/tanstack/table/tree/main/examples/vanilla/basic

### Screenshots or Videos (Optional)

![Image](https://github.com/user-attachments/assets/ac2e340c-f42e-44ca-9e6d-0cb7d90a3f4d)
![Image](https://github.com/user-attachments/assets/433b4922-c7a4-4597-96f8-916d593a5c35)

### Do you intend to try to help solve this bug with your own PR?

Yes, I think I know how to fix it and will discuss it in the comments of this issue

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by fatso83** [comment]
I reported this a month ago, but @KevinVandy closed it as completed the day after - without any details of why. Seemed a bit premature, given that nothing was done, but I assumed a fix had already been merged somewhere else and was waiting to get published. Seems I was wrong?

**Comment by KevinVandy** [comment]
2 vanilla examples have been contributed
